### ISSUE TITLE
Amidst 4.7 Bug Report

### ISSUE THREAD

**Issue by johannesweber42** [toolbox4minecraft/amidst#1002]
the used operating system and version
**windows 10 home 20h2**
    the used Java version
**version 8 update 161**
    the used Minecraft version
**1.17**
    the used Amidst version
**4.7**
    the error message, if any
![image](https://user-images.githubusercontent.com/82626131/122493417-a6d5ed00-cfb5-11eb-9452-c97404e4abeb.png)

    What did you do to produce the error?
**try to run 1.17 in amidst**
    (How) can the error be reproduced?
**try to run 1.17 in amidst**
    What did you expect to happen?
it launch
    What did actually happen?
error

**Comment by Mr-Technician** [comment]
See: https://github.com/toolbox4minecraft/amidst/issues/999
