### ISSUE TITLE
4.0beta10 doesn't show both sets of coordinates for Strongholds

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#101]
I just noticed that the latest release, beta 10, doesn't display both the Overworld coordinates and the Nether coordinates when a Stronghold icon is clicked anymore.
I really felt this was a useful feature when it existed.

**Comment by Treer** [comment]
Both sets of coords are still shown:
![nether coords a4](https://cloud.githubusercontent.com/assets/6390507/13369614/01f07fba-dd4b-11e5-866d-648335d753fa.png)

But that's clearer when it's in multi-line format:
![nether coords ae](https://cloud.githubusercontent.com/assets/6390507/13369617/0ac7e10a-dd4b-11e5-88a0-bf5a1f6bbeae.png)

I'll submit a pull-request for multi-line labels today if I get time.

**Comment by BigAlanM** [comment]
I'm an idiot!!!! 
For some reason I was looking at strongholds and thinking Nether Fortresses and I EVEN typed Strongholds.
I wasn't thinking straight and got mixed up!!!

I REALLY need to crawl back under my rock.
I was hoping I could close this before anyone saw it.
I feel like such a fool.
