### ISSUE TITLE
Is there any roadmap to 1.18 experimental snapshots?

### ISSUE THREAD

**Issue by lams2135** [toolbox4minecraft/amidst#1035]
Same as the title, Is there any roadmap to 1.18 experimental snapshots? or anyway to run them with current build?

**Comment by KaiSandstrom** [comment]
Disclaimer: Not a dev.

The 1.18 experimental snapshots use an entirely different system for generating biomes, so implementing functionality in AMIDST will require a lot of work. For this reason, the devs will likely wait until the release of 1.18 (or at least until the new biome system is finalized) to implement it.

The experimental snapshots use fully 3D biome noisemaps. This means that an accurate 2D biome mapping tool would need to check the Y level of each part of the map to determine what biome will actually generate on the surface. Making this work efficiently will take too much time and effort to be worth developing for just the two experimental snapshots -- for all we know the fully 3D system could end up scrapped in the next snapshot and all that work would effectively be wasted.

**Comment by lams2135** [comment]
ack, sounds really a tough work, thank you devs
