### ISSUE TITLE
forge not detected with multimc launcher

### ISSUE THREAD

**Issue by Commandore32** [toolbox4minecraft/amidst#1037]
I'm playing on the multi mc launcher and amidst says forge not detected.

**Comment by Commandore32** [comment]
Aside from FTB over wolf, what does amidst currently support? when will multi mc be supported? FTB overwolf is very laggy for me.

**Comment by Boobies** [comment]
The answer is never, most likely. The developers have said many times that only the vanilla launcher is supported. Any 3rd party launcher that works does so "by accident" (it looks like the vanilla one as far as Amidst knows even though there is no explicit code to support it).
