### ISSUE TITLE
Crashed when trying to select profile

### ISSUE THREAD

**Issue by BlueLilyRose** [toolbox4minecraft/amidst#1044]
![20210817_141517](https://user-images.githubusercontent.com/89102303/129787314-d2d941ed-1ca2-440e-98bf-4eb9778da885.jpg)

**Comment by DanielG86** [comment]
I have the same problem, anyone knows how to fix this?

**Comment by BlueLilyRose** [comment]
I fixed my issue. Reinstall Java Runtime TM. And then change it from old Java TM to new Java TM in the open with option when you right click jar file.
