### ISSUE TITLE
Version 4.7 versions displayed but not found 

### ISSUE THREAD

**Issue by Tokeeyo** [toolbox4minecraft/amidst#1081]
I loaded up fabric 1.17.1 and this happened. I have tried installing java from their website but nothing seems to work. 

![image](https://user-images.githubusercontent.com/95041465/143470828-81bb2847-496c-44cf-afaa-465a0373fcd9.png)

update: I saw that someone installed optifine and it partially fixed it for them so I followed suit, now I have this. 
![image](https://user-images.githubusercontent.com/95041465/143475622-1fa71faf-b4bb-475f-92c7-c59bcdf8dae7.png)

**Comment by Tokeeyo** [comment]
Fixed it by following this video
https://www.youtube.com/watch?v=k_cdxi6A4FU

**Comment by bokov** [comment]
That video is private for some reason, so this issue no longer has a workaround.

**Comment by Tokeeyo** [comment]
Hello Alex F, regarding the issue I encountered, I fixed the issue simply
by installing optifine, if that's what you were referring to.

Best,
Jamie
