### ISSUE TITLE
[Feature Request] Support for custom Minecraft installation locations

### ISSUE THREAD

**Issue by y2k04** [toolbox4minecraft/amidst#1094]
This is how my Minecraft directory structure is:

 .minecraft ◣
...........assets ◣
................ indexes
..................log_c...
.........bin
.........**instances ◣
.....................Fabric 1.18.1**
.........libraries ◣
................com
................comm...
.........versions
.........webcache2

I would like to be able to select the dedicated version folder and use this software.

**Comment by MrMelon54** [comment]
Using a `.minecraft` directory also doesn't work when using an external launcher (like MultiMC/PolyMC) without having a minecraft installed via the default launcher.

Not exactly sure how this could be fixed as external launchers have their own way to manage versions and instances.

**Comment by Venem** [comment]
Could check if there is a primary .minecraft directory and if there isn't prompt the user to find it. There could be an option to change it later

**Comment by y2k04** [comment]
> Using a `.minecraft` directory also doesn't work when using an external launcher (like MultiMC/PolyMC) without having a minecraft installed via the default launcher.
> 
> Not exactly sure how this could be fixed as external launchers have their own way to manage versions and instances.

What about a check for that specific folder structure then? The other launchers have their own way to store folders so it would be easy to tell the difference possibly.

**Comment by y2k04** [comment]
> Could check if there is a primary .minecraft directory and if there isn't prompt the user to find it. There could be an option to change it later

But yeah, in the official Minecraft Launcher, you are able to choose your own folder for where it will store the instance files.

**Comment by Venem** [comment]
> What about a check for that specific folder structure then? The other launchers have their own way to store folders so it would be easy to tell the difference possibly.

Well Amidst only really looks for save folders from what I understand so if that's an issue you could manually select each save folder

**Comment by MrMelon54** [comment]
Looks like it also tries to find the directory `versions` and the launcher profiles json file.
https://github.com/toolbox4minecraft/amidst/blob/86ffd6004a3ab2a88b9325de420a596665f0df75/src/main/java/amidst/mojangapi/file/directory/DotMinecraftDirectory.java#L40
Neither of which are present when using MultiMC/PolyMC.
