### ISSUE TITLE
plsease help

### ISSUE THREAD

**Issue by killer123374** [toolbox4minecraft/amidst#1101]
![image](https://user-images.githubusercontent.com/105917791/169502661-255192ba-e781-47f9-bcc3-1d2d03099927.png)
I don't knoe what is cousing this. I try to lanch a 1.18.2 version but it doesen't whana launch it only gives me this error code.

**Comment by FeedTheChunk** [comment]
Amidst doesn't support 1.18.x

**Comment by killer123374** [comment]
Ok. Thank you for you'r time.
