### ISSUE TITLE
Add support for MultiMC/other launchers

### ISSUE THREAD

**Issue by rchard2scout** [toolbox4minecraft/amidst#126]
Currently, Amidst only checks the default install location for profiles/worlds etc. It'd be nice if you could also point it at for example a MultiMC "instances" folder, or at the .FTB folder from the FTB launcher.

I've tried to use the -mcpath or -mcjar CLI arguments, but I couldn't get them to recognise my MultiMC instances.

**Comment by stefandollase** [comment]
Amidst is [not supposed to support modded Minecraft](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#can-i-use-amidst-with-a-modded-minecraft-version). Thus, I don't think there is a point to add support for other launchers. Am I missing something?

**Comment by rchard2scout** [comment]
I solely use MultiMC to manage my Minecraft instances, both modded and vanilla. I understand the choice not to support modded MC (because that's way out of scope for a project like this), but it'd be nice to use Amidst for at least the vanilla instances.

**Comment by BigAlanM** [comment]
What does MultiMC provide that the standard MC launcher doesn't provide?
I have all my profiles listed.  Each profile designates where to save the worlds created by that version so that I don't accidentally open a world with the wrong file.
What else is needed?
I only ask this here because I don't know of another way to communicate with another member on GitHub.

**Comment by stefandollase** [comment]
@BigAlanM Your question is highly related to the topic of this issue, so there is no reason to hide it from the public ;-)

I guess the only reason why the OP is not using the Minecraft launcher is, because he has some modded Minecraft profiles which cannot be used from the Minecraft launcher, but only from MultiMC. To prevent the need for multiple launchers, he simply decided to use MultiMC for all profiles.

@rchard2scout Did I get this right? So the only reason for this request is, that you don't want to install another launcher? While I understand the desire, I don't think that this is enough of a reason for us to implement support for another launcher. This is not a simple change.

**Comment by rchard2scout** [comment]
Yup, that's pretty much right. I didn't know whether or not this change would be trivial or not, can't hurt to ask, right?

If it's more complicated than just adding a menu and a configurable instance folder, I think it's fine to close this as "Won't fix".

**Comment by stefandollase** [comment]
Yes, sadly this will be more complicated, but you are right: Asking is never a bad idea.

**Comment by sprowell** [comment]
Here's how to use Amidst with MultiMC.  **Disclaimer: This is a "works for me" solution.**

First, open the regular Minecraft (not MultiMC) and create a profile that is the same as the one you want to use in MultiMC.  Basically, you are going to let Amidst find the profile data from the regular Minecraft launcher, and then search for the save file in the MultiMC area.

Second, run Amidst and select the correct profile.  Next choose File and Open save game...  Now browse to the save game you want and open it.  Congratulations!  Works for me on Windows.

Now, if you are on a Mac MultiMC saves everything in /Applications/MultiMC.app/Contents/MacOS/instances.  Now, Amidst gets confused (it isn't using the platform file browser to find files) by the MultiMC.app package.  To get around this easily, make a symbolic link to the instances folder.  From the command line:

```
cd ; ln -s /Applications/MultiMC.app/Contents/MacOS/instances .
```

This will make a symbolic link in your home folder to the instances folder.  Then after you start Amidst just browse to the symbolic link in your home folder.  Congratulations!  Works for me on the Mac.

Linux?  Should work the same way, but I'm too lazy to try that right now.

**Comment by jexxadox** [comment]
> This will make a symbolic link in your home folder to the instances folder. Then after you start Amidst just browse to the symbolic link in your home folder. Congratulations! Works for me on the Mac.
> 
> Linux? Should work the same way, but I'm too lazy to try that right now.

So im using an ubuntu based linux, but im very new to linux, (as well as Github).

how do i use the commands? do u you mean in the terminal? i've tried extracting the .jar, ive tried locating the "mcpath" everything i can think of.  I dnt see any way to edit the "launching" commands in linux as just clicking the .jar or .exe runs it and it immediately goes to the error of "no minecraft path". these commands are so over my head i dnt even know where im missing something. please explain for a total noob how to set the mcpath in a linux ubuntu. i have a path for my 1.16.5 vanilla installation (no mods). i really dnt want to download another launcher, another java, and have another folder for all of this, *just* to run amidst. i already have like 8 duplicates of java just to run mc alone. 

sorry. im getting so frustrated. u can't just include a .deb install for us linux users?

**Comment by unsubtract** [comment]
> > This will make a symbolic link in your home folder to the instances folder. Then after you start Amidst just browse to the symbolic link in your home folder. Congratulations! Works for me on the Mac.
> > Linux? Should work the same way, but I'm too lazy to try that right now.
> 
> So im using an ubuntu based linux, but im very new to linux, (as well as Github).
> 
> how do i use the commands? do u you mean in the terminal? i've tried extracting the .jar, ive tried locating the "mcpath" everything i can think of. I dnt see any way to edit the "launching" commands in linux as just clicking the .jar or .exe runs it and it immediately goes to the error of "no minecraft path". these commands are so over my head i dnt even know where im missing something. please explain for a total noob how to set the mcpath in a linux ubuntu. i have a path for my 1.16.5 vanilla installation (no mods). i really dnt want to download another launcher, another java, and have another folder for all of this, _just_ to run amidst. i already have like 8 duplicates of java just to run mc alone.
> 
> sorry. im getting so frustrated. u can't just include a .deb install for us linux users?

Terminal command (the dollar sign is standard notation for borune shell commands, not meant to be a part of the command)
```
$ ln -s /path/to/MultiMC/instances ~/.minecraft
```
This will create a symbolic link to /path/to/MultiMC/instances (replace with your actual MultiMC install directory) in your home folder. Everything else is exactly the same.

.deb files are also used only for packages (system-wide programs and their related config files and manpages), and only for Debian/Ubuntu-based distros, they aren't some magic file that will make everything work.

**Comment by lenrik1589** [comment]
> I solely use MultiMC to manage my Minecraft instances, both modded and vanilla.

I do only use MultiMC for instance management, it's GUI just feels much nicer compared to "vanilla" launcher
Moreover it is a hassle to update vanilla launcher while in MultiMC it is literally one click operation
