### ISSUE TITLE
New install option: Homebrew cask

### ISSUE THREAD

**Issue by JMoVS** [toolbox4minecraft/amidst#128]
Amidst can now easily be installed (and even kept up to date) via homebrew casks on Mac OS:

`brew tap caskroom/cask` (assuming you have homebrew installed on your system)
`brew cask install amidst` to install amidst then. ;-)

**Comment by stefandollase** [comment]
Thanks for the information. Did you set this up? Also, how does this work? Can anybody adjust the package information? Where is the package information managed? Is there something that needs to be done to trigger an update or is it triggered by some change in this repository? If it is triggered automatically: By what exactly is it triggered?

**Comment by JMoVS** [comment]
Yes, I added it to homebrew-cask via a pull-request. This will mainly be helpful for people already using homebrew (like the nerds). Package information can be adjusted by making a pull request (https://github.com/caskroom/homebrew-cask/) is a good place to start or I can try to change some stuff.

To trigger an update, there seems to be a script to trigger it: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask

I have no experience with casks and updates (I only have experience with regular homebrew which works differently) so we'll see how it turns out.

As to "how it works": If the user has homebrew installed (http://brew.sh/), he can run `brew tap caskroom/cask` and then simply run `brew cask install amist` to install it in ~/Applications.

**Comment by stefandollase** [comment]
Thanks for the additional information and also thanks for creating this. Someone already updated the entry to Amidst v4.1. We should add an installation guide to the wiki, containing this as an alternative. Also, we should add a step about this to the "creating a release" wiki page. I added these tasks to #66, so I will close this issue.
