### ISSUE TITLE
Amidst 4.1 shows incorrect biome

### ISSUE THREAD

**Issue by stefandollase** [toolbox4minecraft/amidst#130]
Quoting @Morpheus1101 from skiphs/AMIDST#96:

>Im running a 1.9 Map, created in 1.9 Release with seed: 975338343250368 i have a base @ -556 89 8664 which when i use the app from chunkbase shows the correct biome being a taiga biome, however with amidst its trying to tell me im in a Plains BIOME

Quoting the answer by @BigAlanM:

>Strange. I just displayed "975338343250368" with Amidst v4.1 with a PCMCv1.9 profile and the location -556, 8664 is definitely in a Taiga biome.

---

I also created a map from the given seed with Amidst v4.1. Here is the screenshot. The given coordinates are at the center of the screen. It displays a Taiga biome.

![screenshot_default_975338343250368](https://cloud.githubusercontent.com/assets/981434/13749008/d7a9696c-e9ff-11e5-934e-14286b2b4c48.png)

Please ensure that you are using Amidst v4.1 with a vanilla Minecraft profile using Minecraft 1.9. Then report your findings back right here. Also, please provide a screenshot if the problem still exists.

**Comment by Morpheus1101** [comment]
Im using pure vanilla client no mods or anything, as u can see via attached screenshot im seeing something very different. 


![amidst](https://cloud.githubusercontent.com/assets/10524952/13759234/073b24ee-ea79-11e5-91da-2063d5be6168.png)

**Comment by Treer** [comment]
Looks like that difference is due to having the world type set to "Large Biomes" instead of default.

**Comment by Morpheus1101** [comment]
Hadnt noticed that, i presumed Large Biomes as thats what the world type is ... but using default then yes indeed it shows the correct biomes.  A simple thing i completely overlooked

**Comment by stefandollase** [comment]
It happens to the best of us...

Good thing we added the world type to the seed widget :P I am closing this, since it is resolved.
