### ISSUE TITLE
Can't compile without jnbt-1.3

### ISSUE THREAD

**Issue by mathuin** [toolbox4minecraft/amidst#132]
I want to use AMIDST but I don't know much about Java and I don't want to install Java 8 on my system.  So, I checked out the source code and made a Dockerfile.  The file referenced java:8, installed maven, and attempted to run 'mvn -e package'.

This was found in the scrollback:

```
Downloading: https://repo.maven.apache.org/maven2/jnbt/jnbt/1.3/jnbt-1.3.pom
[WARNING] The POM for jnbt:jnbt:jar:1.3 is missing, no dependency information available
```

This was at the end:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.748s
[INFO] Finished at: Tue Mar 15 17:29:41 UTC 2016
[INFO] Final Memory: 9M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project amidst: Could not resolve dependencies for project amidst:amidst:jar:0.0.1-SNAPSHOT: Could not find artifact jnbt:jnbt:jar:1.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project amidst: Could not resolve dependencies for project amidst:amidst:jar:0.0.1-SNAPSHOT: Could not find artifact jnbt:jnbt:jar:1.3 in central (https://repo.maven.apache.org/maven2)
```

Is the jar supposed to be in the central Maven repository?  Do you guys have it installed locally or something?  Help!  Thanks!

**Comment by mathuin** [comment]
... okay, I feel a little dumb for this.

In your Travis XML file,  you call 'mvn clean'.  That apparently installs ./lib/JNBT_1.3.jar into the .m2/repository/jnbt/jnbt/1.3 directory.  It's even obliquely referenced in the comments.

Sorry about that!  I'm going to close the issue -- but hopefully if someone else has it, they'll find this in a search and solve their problem. :-)

**Comment by stefandollase** [comment]
Good thing you figured it out :-) I have to admit, it is a little bit confusing, but I was not able to figure out a better solution for this. Just for the future if somebody finds this issue: We have a [wiki page](https://github.com/toolbox4minecraft/amidst/wiki/Building-from-Source-Code) which describes the build process.

BTW: Do you mind to provide the Dockerfile? I have not that much experience with it, but it might be useful to someone.

**Comment by mathuin** [comment]
I can do that, sure!  It's a little fragile in that the version number is hard-coded but that could be an easy PR for another contributor.

The commands necessary to build the binary:

```
docker build -t makeamidst .
docker run --rm -it -v `pwd`:/target makeamidst
```

I'll make a PR, let me know there how you'd like documentation to be added!

**Comment by stefandollase** [comment]
Thanks again. As stated in #137, I will just paste the Dockerfile right here:

```
FROM java:8
RUN apt-get update
RUN apt-get install -y maven
RUN mkdir /target
VOLUME /target
COPY . /opt/amidst
WORKDIR /opt/amidst
RUN ["mvn", "clean"]
RUN ["mvn", "package"]
CMD ["cp", "target/amidst-v4-0.jar", "/target"]
```

**Comment by mathuin** [comment]
Ah, sorry for misunderstanding!  Hopefully the Dockerfile will be helpful to someone!

**Comment by doej1367** [comment]
And for all Eclipse users like me that stumble across this problem:
Rightklick on Project > Run As > Maven clean
Rightklick on Project > Maven > Update Project...
