### ISSUE TITLE
JRELoadError

### ISSUE THREAD

**Issue by jnman078** [toolbox4minecraft/amidst#135]
When I go to start up AMIDST on my MacBook, I keep getting a 'JRELoadError' message before the program shuts down.

**Comment by stefandollase** [comment]
Can you clarify? You say that you get the error before the program shuts down. Does this mean that you can use Amidst and after you are done and close it the error occurs or does it mean that you cannot use Amidst but the only reaction you get after starting it is the error?

Next, can you please post the complete error message?

Finally, and most importantly: Which Java version do you have installed? You need Java 8.

**Comment by jnman078** [comment]
I updated Java and the program works fine now.

Thank you anyway.
