### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by tolly67p** [toolbox4minecraft/amidst#152]
When i try to open my optifine profile it just crashes

**Comment by Treer** [comment]
Yeah, as a general rule, modded profile can be supported.

If you don't already have a non-Optifine profile then create a new profile with the Minecraft launcher. Call it something like "Amidst" and just select that one when Amidst asks you for a profile. Use your normal optifine profile when playing Minecraft.

![minecraft launcher](https://cloud.githubusercontent.com/assets/6390507/14304860/0cd746e8-fbfa-11e5-8451-e5f97cdeeb03.png)


Optifine might be supported one day, see #110

Mod support is also touched on in the FAQ: [Can I use Amidst with a modded Minecraft version?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#can-i-use-amidst-with-a-modded-minecraft-version)
