### ISSUE TITLE
My amidst won't launch on windows 10.

### ISSUE THREAD

**Issue by Phoenixjdj** [toolbox4minecraft/amidst#153]
My amidst won't even start or open a window for the application, I have tried the JAR and the executable file but none of them will work. Any tips or is there something I am doing wrong?

**Comment by Phoenixjdj** [comment]
Never mind, I fixed it! What was wrong was in my folder settings I had to reset to default! :D

**Comment by stefandollase** [comment]
Good to hear this is fixed. Thus, I close this issue.
