### ISSUE TITLE
Aprendendo...

### ISSUE THREAD

**Issue by coudergames** [toolbox4minecraft/amidst#154]
Evoluir sempre!

**Comment by stefandollase** [comment]
Google translate says, this is Portuguese with the following English translation:

> ### Learning...
>
> Evolve always

I don't understand Portuguese by myself, so I can only guess that you want to thank us for developing Amidst and you hope that we keep maintaining it, did I get this right? If I did: Thanks for your support and we currently plan to maintain it for quite some time, always given we have the time to do so.

If I got you wrong, please try to express yourself in English :-P

**Comment by stefandollase** [comment]
The OP seems to have lost interest in this issue. Thus I close it.
