### ISSUE TITLE
EventQeue0.6.main

### ISSUE THREAD

**Issue by TheJarlSagan** [toolbox4minecraft/amidst#174]
Had AMIDST working with older versions, but can't get it running for 1.9 ...
From what I can discern, it's not locating the version properly. Which is strange because I'm running with a clean profile.
Could be a total bonehead issue, but any help is appreciated.

[Event0.6.main Error Log.txt](https://github.com/toolbox4minecraft/amidst/files/276051/Event0.6.main.Error.Log.txt)

**Comment by stefandollase** [comment]
Please download the latest version of Amidst from https://github.com/toolbox4minecraft/amidst/releases

**Comment by TheJarlSagan** [comment]
Ah.... Bonehead issue, like I said. Thanks for the quick response.
