### ISSUE TITLE
Trouble starting up Amidst

### ISSUE THREAD

**Issue by ethandc11** [toolbox4minecraft/amidst#182]
So i am on OS X and i installed Amidst and when i clicked on it to run it, it just said JRELoadError.
I was wondering why this is happening. also this is for the amidst-v4-2-beta2.zip

**Comment by ekevoo** [comment]
Get latest Java from Java.com

If the problem persists, run the Jar from terminal, and provide more information.

**Comment by stefandollase** [comment]
As @ekevoo said: Please download the latest Java version (Java 8 is required) and report your results back to us.

**Comment by stefandollase** [comment]
The OP seems to have lost interest in this issue. Thus I close it.
