### ISSUE TITLE
Function to find a seed with biomes in specified range around the spawn point

### ISSUE THREAD

**Issue by smartynko** [toolbox4minecraft/amidst#183]
Hi guys. I am trying to find a 1.10 seed with Jungle, Mesa, Icy Spikes, Mushroom Island, Swampland and Desert biomes close to spawn point. Something like maximum 1500 blocks from spawn point. 

The thing is there is no way to tell Amidst to iterate trough seeds and save just those with specified parameters. I would like to have this option in Amidst.

Just let me know if this is possible or not.

**Comment by stefandollase** [comment]
Amidst currently does not support to search for a seed by a given set of criteria. However, this is planned for the future, see #120. You might want to try the [SeedFinder](http://zipkrowd.com/tools.htm) by CodeRaider until this feature is part of Amidst.

**Comment by BigAlanM** [comment]
I just downloaded SeedFinder and could not get it to run a search.
It crashes with a heap error.

**Comment by stefandollase** [comment]
@BigAlanM
Thanks for the info. I never used it by myself, so I cannot help out with that issue. Maybe, you can report the issue to CodeRaider, so it can be fixed?

**Comment by jmessenger235** [comment]
CodeRaider has been AWOL for some time now. Getting support with that app is a bit pointless... If it is broken it will likely stay that way.

**Comment by stefandollase** [comment]
@jmessenger235
Thanks for the clarification. I guess, I will stop to suggest the usage of SeedFinder :-P

**Comment by jmessenger235** [comment]
A good chunk of seedfinder still works, but it is obsolete for most practical purposes as there are better tools out there. That is one reason why I have been so keen on #120. I'm also working on a separate QWH finder due to some performance issues in amidst, but that is a separate project.

**Comment by stefandollase** [comment]
I really do appreciate the interest in #120 and I would also like to push it forward, however my time is limited and so I have to priorities what I can afford to do and what has to wait. The Amidst development is a hobby for me, so it is not a high priority. It is unfortunate that this blocks the project, however the alternative is to publish something half-finished and I prefer a stable tool with less features over a unstable tool with many features. Also, I prefer maintainable code and that also takes time to develop.

**Comment by ekevoo** [comment]
@stefandollase How about just starting a git branch with the intended design stubbed out? That way other people with more time in their hands can do the bulk work.

**Comment by stefandollase** [comment]
@ekevoo
That already happened, see #120 and #129. The next step is to integrate this implementation into the existing code base. This is my part, since I have the best overview of the complete code base. I started to work on it, but I ran out of time. Just wait for it. It will be done eventually.
