### ISSUE TITLE
Can I use AMIDST biome colors in another mod?

### ISSUE THREAD

**Issue by vpontin** [toolbox4minecraft/amidst#207]
Hi!

I have plans to fix somethings for [Earth Mod](http://minecraft.curseforge.com/projects/the-earth-mod), like correct biomes and whatever. They use [this repo](https://github.com/gegy1000/EarthBiomemap) to store biome images used by the mod to generate the terrain. Each color in images represent a biome.

But i realize the biomes colors list of the repo are missing several biomes, and i realize AMIDST lists all mods and, actively developed, i think you will keep track of new MC biomes in the case Mojang adds new biomes.

So, [i created this ticket in that repo](https://github.com/gegy1000/EarthBiomemap/issues/4) asking if i could convert AMIDIST, and i created this companion ticket here to confirm if the author allows me to use his colors list on the project.

My plans, if the guys of Earthmod dont want to change their list format, is to create a automated converter of AMIDST JSON -> TXT format (maybe in lazarus) to do the dirty work.

Additionally, Is this particular color pallete would be subject of GPL, assuming the license of Earth mod is different (i really dont know what is)?

Anyway thanks in advance!

**Comment by stefandollase** [comment]
Regarding the legal issue: I am not a layer and thus I cannot provide any binding legal advice. However, I will communicate what I think about this.

In theory: The project is licensed under the GPL. This means, that everything in it, including the biome color list is licensed under the GPL. Thus, if you use the biome colors, you would have to license your own product under the GPL, strictly speaking. If I would be the only author of the biome color list, I would be able to re-license it to you, so this restriction would not apply to you. However, I am not the only author and thus this is not an option, sadly. Lastly, I am not sure whether a list of colors can be licensed at all, so there might not even be an issue.

In practice: I guess nobody will care about it :-P At least I won't care about it, but you should be aware that other people might care.

---

Here is how I suggest you to do it: First, read [this](https://github.com/toolbox4minecraft/amidst/wiki/Biome-Profiles) wiki page. Especially notice, that the syntax for the json file might change in the future. Also, the files in [this](https://github.com/toolbox4minecraft/amidst/tree/master/biome) folder are only part of the repository as an example and to support the development. They are **not** part of the Amidst jar file. Also, we might fail to update them when we update [the actual biome list in the code](https://github.com/toolbox4minecraft/amidst/blob/master/src/main/java/amidst/mojangapi/world/biome/Biome.java). This biome list is currently the single source of truth. For example, we use it to generate the [Biome Color Table](https://github.com/toolbox4minecraft/amidst/wiki/Biome-Color-Table), see [here](https://github.com/toolbox4minecraft/amidst/blob/master/src/test/java/amidst/devtools/GenerateBiomeColorImages.java).

Thus, if you really want to automate this, you might want to use the `default.json` file that is generated by Amidst when you place an empty `biome` directory next to the Amidst jar file. Be aware, that this behaviour might change in the future. Another option is to use the Java code directly to generate your color list, like we do it for the Biome Color Table. However, again, the Java code is also changed over time, so in both cases the automation will probably break from time to time.
