### ISSUE TITLE
Biome's O Plenty 

### ISSUE THREAD

**Issue by Mcdarvin81** [toolbox4minecraft/amidst#208]
Was wondering if there was anyway to at least load saved maps from biome's o plenty ? If it's impossible to generate maps with the mod

**Comment by BigAlanM** [comment]
Amidst doesn't "load" maps from world save folders regardless of whether or not the world is created with vanilla Minecraft or a modded version.  
If you want a map of the actual world as created/modified by players use another mapping program.
I'm quite satisfied with what I get using Minutor.
