### ISSUE TITLE
1.10 Taiga Villages

### ISSUE THREAD

**Issue by Alexander17101** [toolbox4minecraft/amidst#214]
Hi again! 8-D
As you might know, villages can spawn in Taiga scince 1.10.
It would be nice, when it gets added, that you can see this villages on the map.

![kjbqeee](https://cloud.githubusercontent.com/assets/14953567/17112428/4b6b048c-52a6-11e6-99ec-a694ff0a8d2d.jpg)
 
                                                                                    Alexander :D

**Comment by stefandollase** [comment]
Thanks for the heads up. However, this is a duplicate of #177 and thus I close it.

**Comment by Alexander17101** [comment]
:+1:
