### ISSUE TITLE
Same map generated for any seed entered

### ISSUE THREAD

**Issue by markturansky** [toolbox4minecraft/amidst#215]
Generating a world from `File->New From Seed` always generates the same world, regardless of the value entered.

`File->Open Saved Game` correctly shows me the Minecraft world.

I am using Java 1.8 on OSX. Minecraft 1.10.2. This happens in admidst v4-1 and v4-2-beta.

I looked for an open issue about this but didn't find one. I didn't look that hard, though.

**Comment by stefandollase** [comment]
I just tested this by myself using Minecraft 1.10.2 and Amidst v4.2-beta2. I cannot confirm the issue. Also, you are the first who reports  this behaviour. Can you provide more information? For example, which seed do you enter and which seed does it display / use?

**Comment by markturansky** [comment]
Hm. I went to make a screencast of it and, naturally, it doesn't happen now.

Nevermind!  (I could swear it happened, though...)
