### ISSUE TITLE
Is there an API for "creating" and gathering information about worlds yet developed?

### ISSUE THREAD

**Issue by MasterGuardian** [toolbox4minecraft/amidst#225]
Hey,
as the commentating is quite underreported its hard for me to read and search for an API to access to create worlds and gather information about them on code level (I want to analyze random generated worlds if they to fit a predefined pattern (maybe "take a picture of a certain area", too)

MasterGuardian

**Comment by stefandollase** [comment]
Amidst currently does not provide a public API and there will probably be changes to the internal structure of Amidst in the future. However, you might be interested in #120.

Next, you can take pictures of the currently displayed area via the GUI, but there currently is no way to automate this. If you want to automatically take a picture of a given area of a given world, you might want to create a separate feature request for it. A new command line option might be a good solution for it. Please note, that there is currently not much developer effort available for the project, so feature requests take their time.

**Comment by jmessenger235** [comment]
@stefandollase In the feature list for #120, I was thinking of adding a way to have matching seeds export a picture that would fulfill the feature request. Do you mind if I open a feature request for a command line photo export for a specific seed?

**Comment by stefandollase** [comment]
@jmessenger235
No, it's fine. Please go ahead and create it :-)
