### ISSUE TITLE
Amidst.app fails to launch, JRELoadError

### ISSUE THREAD

**Issue by remeisigma** [toolbox4minecraft/amidst#227]
This occurs in 4.0, 4.1, 4.2-beta1 and 4.2-beta2, in OSX 10.11

**Comment by stefandollase** [comment]
You need at least Java 8 to run Amidst. Please make sure you have Java 8 installed and let us know whether this solved the issue for you.

**Comment by remeisigma** [comment]
I did have Java 8, but apparently it was a faulty installation of some sort. Re-installing it worked, thanks for the tip.
