### ISSUE TITLE
1.11 Woodland Mansions

### ISSUE THREAD

**Issue by MattSturgeon** [toolbox4minecraft/amidst#233]
New rare structure has been added to Roofed Forest biomes in 1.11, the Woodland Mansions.

It would be good to add a layer for these.

---

As a sidenote, I wonder if looking into the implementation for the new `/locate` command will make finding structures easier?

**Comment by stefandollase** [comment]
Thanks for contributing to the project! Indeed, we should add the new structure.

Regarding the `/locate` command, I just added #237.

**Comment by LockManipulator** [comment]
There still doesn't seem to be a feature to find woodland mansions.
