### ISSUE TITLE
Infinite zoom

### ISSUE THREAD

**Issue by MattSturgeon** [toolbox4minecraft/amidst#236]
Add the ability to zoom in or (more importantly) out as far as desired.

This is useful on large maps where you may be looking for locations out in the 100k's or the millions, or cases where many structures are generated close together.

If this is a portential performance issue, perhaps have it as an advanced option.

A zoom reset feature may become useful, as well as an option to zoom on the center of the screen instead of cursor position.

**Comment by CubeTheThird** [comment]
Infinite zoom is already a feature. Under the settings tab, uncheck the "Restrict Maximum Zoom" box.

**Comment by MattSturgeon** [comment]
Huh, no idea why I've not noticed that... Thanks!
