### ISSUE TITLE
Warning needed for moving player

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#238]
I just discovered that, although the instructions for moving a player in a world mapped by using "Open saved game" is quite detailed, there is an important detail left out.
You need to save and close the world BEFORE you try to move the player.
If you are still playing the world Amidst will SEEM to successfully move the player but in actuality nothing will happen to his position.
(Sorry about the blank entry and abbreviated title. Lost power and Chrome crashed.)

**Comment by MattSturgeon** [comment]
?

**Comment by BigAlanM** [comment]
This issue was messed up by me and is now a duplicate.  Closing the one.
