### ISSUE TITLE
Amidst has encountered an uncaught exception on the thread Thread [Thread-8,1,main]

### ISSUE THREAD

**Issue by deon4110** [toolbox4minecraft/amidst#244]
This happens every time i load up the program

**Comment by stefandollase** [comment]
Please read [Reporting a Bug](https://github.com/toolbox4minecraft/amidst/wiki/Supporting-the-Development#reporting-a-bug) and add the requested information.

**Comment by stefandollase** [comment]
The OP seems to have lost interest in this issue. Thus I close it.
