### ISSUE TITLE
Add variable size photo export

### ISSUE THREAD

**Issue by SungMatt** [toolbox4minecraft/amidst#245]
At the moment, photo exports are based on the size of your screen. This results in blurry exports of maps, and when printed, do not have as great quality. Addition of a variable high-resolution export would be helpful, for printing usages.

**Comment by GeorgeWL** [comment]
Also,  could we have SVG image export? 

That way it scales near-infinitely up and down in size,  thanks to the images being a set of mathematical vectors.

**Comment by stefandollase** [comment]
@GeorgeWL I will have to look into that. However, that should really be a separate feature request ;-)

**Comment by moulins** [comment]
Closing as duplicate of #713.
