### ISSUE TITLE
High resolution icon

### ISSUE THREAD

**Issue by stefandollase** [toolbox4minecraft/amidst#28]
As @BigAlanM stated in #12, Amidst 3.7 had a high resolution icon of 256x256. However, the repository only contains a low resolution icon of 32x32. To bring the high resolution icon back to Amidst v4.0, someone needs to create a pull-request that contains high-resolution icon. Please replace the png-file `src/main/resources/amidst/icon.png` with the new icon. It has to be a png file.

**Comment by BigAlanM** [comment]
I converted the 130k .ico to a .png and it became a 30k file.
Here are links to both.
http://www.mediafire.com/download/4j6uxn96w6es89i/AMIDST_256.ico
http://www.mediafire.com/view/711yd1ibr6qq7av/AMIDST_256.png

In my ignorance I couldn't figure out how to upload the file(s) to Github so I'm sharing them on MediaFire.

**Comment by stefandollase** [comment]
Thanks for providing the icon. I added it to the repository in #36. Thus, it will be included in the next release.

I also looked into it. I assumed that it is possible to upload binary files via the github web interface, however this is only possible for text files, so the MediaFire solution was a good idea.
