### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by Molyfar** [toolbox4minecraft/amidst#282]
Windows 10 - Desktop - Norton security and anti-virus 360.

Norton 360 has registered the Amidst shortcut on my desktop as being "bad" although the programme itself was OK.

Please advise?

```
c:\users\clive\documents\amidst-v4-2-beta2.exe
____________________________
____________________________

                                        Developers 
                                        Not Available
                                        Version 
                                        Not Available
                                        Identified 
                                        14/08/2016 at 07:41:34
                                        Last Used 
                                        14/08/2016 at 07:41:34
                                       Startup Item 
                                        No

 Threat Details
							File Location
			            
File: C:\Users\Clive\Documents\amidst-v4-2-beta2.exe File: C:\Users\Clive\desktop\AMIDST.lnk
____________________________

File Thumbprint - SHA:
687D2E238D7F51E147598535CC2E7A519E21D362561B63AE6E14F171951483EA
____________________________
```

**Comment by stefandollase** [comment]
Did you try to remove and recreate the shortcut?

**Comment by Molyfar** [comment]
No luck and is now listing the file itself as bad. I should add that this only occurs on Norton's deep scan (Power Eraser). It doesn't occur on the full system scan. I came across this when I had other issues with my laptop.

**Comment by MattSturgeon** [comment]
Sometimes anti viruses give false positives on executables simply because they don't recognise the authour or it is not signed with a microsoft approved key

**Comment by stefandollase** [comment]
I don't think there is much we can do about it. Maybe, there is a way to tell Norton that Amidst is not a malicious program?

**Comment by Molyfar** [comment]
Thank you :-D
