### ISSUE TITLE
Logging codeformating

### ISSUE THREAD

**Issue by ArgTang** [toolbox4minecraft/amidst#290]
```java
Log.i("increasing fragment cache size from " + cache.size() + " to "		
            + (cache.size() + NEW_FRAGMENTS_PER_REQUEST));
```

```java
Log
		.i(
				"increasing fragment cache size from " + cache.size() + " to "
						+ (cache.size() + NEW_FRAGMENTS_PER_REQUEST));
```

As a  side effect of the new formatting logging statements are harder to read (IMO)

**Comment by stefandollase** [comment]
That is the one thing that I also did not like about it. However, it was a trade of: Other settings had other issues. If I remember right, the logging statements looked that way with nearly all settings.

I guess, the reason why this only happens to the (old) logging statements is, that it has very short class and method names. The good news is, that I also reworked the logging and it now has longer names. The code above now looks like this:

```
AmidstLogger.info(
		"increasing fragment cache size from " + cache.size() + " to "
				+ (cache.size() + NEW_FRAGMENTS_PER_REQUEST));
```

I think this is fine.
