### ISSUE TITLE
working without .minecraft folder

### ISSUE THREAD

**Issue by RubenNL** [toolbox4minecraft/amidst#299]
hey all,

i use a custom launcher(MultiMc), that dont use the default .minecraft folder.
is it possible to change the location of the files?

**Comment by DuelMonster** [comment]
You can use the command line option:   -mcpath

See the wiki:  https://github.com/toolbox4minecraft/amidst/wiki/Command-Line-Interface

**Comment by stefandollase** [comment]
We don't officially support other launchers than the original Minecraft Launcher. However, you might be able to get this to work by using the command line parameter as described above. Also, please have a look at #126.
