### ISSUE TITLE
Add the ability to find Woodland Mansions and Water Temples

### ISSUE THREAD

**Issue by DarthFather** [toolbox4minecraft/amidst#304]
I believe that adding this feature would be a really good move towards making the app more useful, thanks for taking the time reading my comment!

**Comment by stefandollase** [comment]
Ocean Monuments are already implemented. Just have a look at the Layers menu.

Regarding the implementation of Woodland Mansions, please have a look at #233. Also, please search for existing feature requests before creating a new one!
