### ISSUE TITLE
Requesting features for future version of AMIDST.

### ISSUE THREAD

**Issue by AndreCraft** [toolbox4minecraft/amidst#306]
Hello, I like to use AMIDST for being a help app for Minecraft. But when I saw that after v3.7 there were no updates I was sad. But recently I've seen your great work in continuing with AMIDST, but I have some suggestions:
Go back with the old AMIDST interface, that is, leave the interface as it was in v3.7. (Windows-style interface);
Add layers to disable icons for Igloos, Temples (from the Jungle and the Desert together) and Witch Huts separated on the Layers tab;
Add Woodland Mansions search and icons;
Add Languages (I can do the language PT-BR).
That's all, but thank you very much for the attention and anything to contact me.
Contact on my YT channel: https://goo.gl/DdlxM0

**Comment by stefandollase** [comment]
> Hello, I like to use AMIDST for being a help app for Minecraft. But when I saw that after v3.7 there were no updates I was sad. But recently I've seen your great work in continuing with AMIDST, but I have some suggestions:

Thanks for your appreciation :-)

> Go back with the old AMIDST interface, that is, leave the interface as it was in v3.7. (Windows-style interface);

Amidst can be used on Windows, Linux and Mac OS X. I know that previous versions of Amidst provided a platform-dependent look-and-feel. However, this caused some issues and thus we decided to provide the same look-and-feel for all platform. It is easier for us to maintain and the look-and-feel is certainly not the most important feature of Amidst. Thus, we will keep it as it is now.

> Add layers to disable icons for Igloos, Temples (from the Jungle and the Desert together) and Witch Huts separated on the Layers tab;

This might be a good idea. Can you create a new issue for this feature request?

> Add Woodland Mansions search and icons;

see #233

> Add Languages (I can do the language PT-BR).

This might be worth another feature request issue.

> That's all, but thank you very much for the attention and anything to contact me.
> Contact on my YT channel: https://goo.gl/DdlxM0

Thanks for you feedback. In general, issue trackers work better if there is only one feature request/bug report/question/... per issue. Thus, I consider this as as question issue. Again, as stated above, you should create separate feature request issues for the layer separation and the localization.
