### ISSUE TITLE
Add Languages

### ISSUE THREAD

**Issue by AndreAugustoAAQ** [toolbox4minecraft/amidst#309]
Add Languages (I can do the language PT-BR). I did not mention the request I sent before, but I'm Brazilian.

**Comment by subtank** [comment]
i can add chinese-simlpify language if you can suppored translation

**Comment by Clpsplug** [comment]
I can add Japanese if you like :)

**Comment by AndreCraft** [comment]
That's cool, but where's the file to translate? I did not find :(

**Comment by stefandollase** [comment]
Thanks for providing help to translate Amidst. However, Amidst is not yet translatable. Thus I marked this as a feature, so we might implement translatability in the future. If we do so, I will let you know in this issue.

**Comment by SuperOP535** [comment]
I can help with Swedish

**Comment by CustomOG** [comment]
I can help with Dutch
