### ISSUE TITLE
Shortcut for toggling grid layout and zooming in are identical

### ISSUE THREAD

**Issue by azuntik** [toolbox4minecraft/amidst#313]
Both the grid layout toggle and zoom in use ctrl+g for their shortcut.

**Comment by stefandollase** [comment]
Indeed. I cannot believe that I missed this, but it happened nevertheless :-/

This will probably be fixed in the next release.

**Comment by azuntik** [comment]
Sounds great! I just wanted to make sure you saw it. :)

**Comment by stefandollase** [comment]
Yes, thanks for the pointer! :-)

**Comment by stefandollase** [comment]
I changed the zoom in and zoom out shortcuts to be CTRL+K and CTRL+J, see #322.
