### ISSUE TITLE
(recognised: UNKNOWN)

### ISSUE THREAD

**Issue by Ralphismyname247** [toolbox4minecraft/amidst#315]
Whenever i try to use this mod(only tried on 1.11.2 so far), at the top of the Amidst window it says (recognised: UNKNOWN) (Note: im on Mac)

**Comment by stefandollase** [comment]
This is currently the intended behaviour. Amidst v4.2 was released before Minecraft 1.11.2. Thus, Minecraft 1.11.2 is unknown for Amidst v4.2. However, since no breaking changes were introduced into the game, Amidst still works with it.

**Comment by Ralphismyname247** [comment]
So nothing is wrong?

**Comment by stefandollase** [comment]
Indeed, nothing is wrong.
