### ISSUE TITLE
Cannot Play Minecraft (Loading Issue After Hitting Play)

### ISSUE THREAD

**Issue by wacktheduck** [toolbox4minecraft/amidst#317]
This Appears After I Select Play;

Unable to save download. jinput-platform-2.0.5-natives-windows.jar
Name: jinput-platform-2.0.5-natives-windows.jar
URL: https://libraries.minecraft.net/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
Error details: Attempting to move successful download to C:/Users\William\AppData\Roaming\.minecraft\libraries\net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
The process cannot access the file because it is being used by another process
Filename on disk: ab2e-ebab-8038-f563
Path: C:\Users\William\AppData\Local\Temp\ab2e-ebab-8038-f563
Exists: file

Help Me Please! Im Not Computer Savy

**Comment by stefandollase** [comment]
I am closing this, since it is not related to Amidst and this is not a general Minecraft support forum.

Nevertheless, have a look at [this](https://www.reddit.com/r/Minecraft/comments/6acu21/psa_download_not_saving_file_being_used_by/).
