### ISSUE TITLE
Opening world from file doesn't load and display actual world spawn point

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#32]
This has been a problem with Amidst for quite some time.
Opening a world file to get the Player's location works fine, and AFAIK always has, but I don't understand why the world spawn isn't read from the level.dat file and displayed also.

I just used the same seed to create a world in default and then in Large Biomes.
I saved each one as soon as I spawned.
I then used Amidstv4b5 (which works quite well might I add) to open and display each one.
Both maps showed the Amidst calculated world spawn NOT the actual world spawn.
The Steve Icon was several hundred meters away and mapped correctly.
The Large Biome world was displayed correctly with the correct scaling.
So I know Amidst is reading level.dat and playerdata, it's just not reading and using the stored value for world spawn.

One thing though, although Amidst v4b5 knew that it was to display a Large Biome world it didn't inform me that the world opened was, in fact, a large biome world.  That would be nice to know.

**Comment by stefandollase** [comment]
The world spawn is now read from the level.dat file.

Regarding the displaying of the world type as Large Biomes: I see that it can be interesting. However, I do not know a good location to display this information. It might be okay to display it in the seed widget, if it is only about large biomes of not, however, there are also custom worlds with very complex generator options. The generator options definitely do not fit into the seed widget, so it should be displayed somewhere else. Any ideas?

**Comment by stefandollase** [comment]
This issue is really a bug report and a feature request. The bug was fixed, so I will close this issue. If you are still interested in the feature request, please open a new issue.
