### ISSUE TITLE
Option to export structure count to file

### ISSUE THREAD

**Issue by CherryLax** [toolbox4minecraft/amidst#328]
Here's my suggestion for a way to make it easier to analyze batches of seeds quickly:

- Add a menu called Export
- Options are Export stats to list, Export stats to file, View list, and List options
- Hotkeys are Ctrl + E for Export to list and Ctrl + Shift + E for export to file
- Export stats to list will append current seed stats to a text list of saved stats
- Export stats to file will send current stats to a text file with a Save As... dialog
- View List will create a temporary text file and open it, showing all the saved stats
- Stats are saved something like this format:
- [Seed]; [#Villages]  [#Igloos] [#Dungeons] [#DesertTemples]  [#OceanMonuments] [#WitchHuts]
- Example:
- 378209395352473212;  6V  8I 1D 2J  1O 2W 2S 0M; 0.21% Ice Plains Spikes; 24.32% Ocean;
- List Options opens a dialog with checkboxes to toggle feature counts, toggle which structures are listed, option to choose percentages to measure, set the distance to measure from the spawn location, and give the option to measure from a specific coordinate.

**Comment by stefandollase** [comment]
Thanks for the suggestion. However, I don't think we will implement this. Instead, please have a look at #120. There are several other feature requests that are similar to different parts of your list.
