### ISSUE TITLE
AmidstExporter's export feature

### ISSUE THREAD

**Issue by darthvader45** [toolbox4minecraft/amidst#334]
I remember in the old days of AmidstExporter, I could export coords of the structures, and sift through them to see which ones actually spawned.  I miss this functionality, and I understand it may be in progress.  I cannot wait to see this feature and I wait with baited breath for news of it making the cut.

**Comment by stefandollase** [comment]
Thanks for expressing your interest. Porting the export functionality is discussed in #21 and #30. Also #248 contains a detailed feature request for an export functionality.

I remember @Treer wanted to port the export functionality, but at some point his contributions stopped.

@Treer: Can we have an update about your plans for the export functionality and AmidstExporter in general?

**Comment by Treer** [comment]
I'm a bit hooked on some other things at the moment and Minecraft has fallen to the side, as has my map system that used the exported coords, so I don't have any current plans to start work on porting the export feature. If someone wants to do it, they shouldn't wait for me.

**Comment by stefandollase** [comment]
@Treer Thanks for the update. I always appreciated your work, so if you ever feel like getting back to Minecraft and the Amidst development, feel free to do so :-)

@darthvader45 I guess that means that the export feature is now one of many features on a long list. Currently, there are more urgent features like #177 #233 #237, so unless someone really wants to implement the export mechanism, it will take some time.
