### ISSUE TITLE
"Amidst crashed!"

### ISSUE THREAD

**Issue by Tilepaper** [toolbox4minecraft/amidst#337]
![image](https://user-images.githubusercontent.com/25676806/27520400-0b6325b4-59d9-11e7-85a0-8e5b555450bc.png)
Happens all the time now. It's version 4.3 beta 2.

**Comment by stefandollase** [comment]
Please check if your C:\ drive is full. If it is not, please provide more details, see [Reporting a bug](https://github.com/toolbox4minecraft/amidst/wiki/Supporting-the-Development#reporting-a-bug).

**Comment by stefandollase** [comment]
The OP seems to have lost interest in this issue. Thus I close it.
