### ISSUE TITLE
Error: No profiles found

### ISSUE THREAD

**Issue by dima74** [toolbox4minecraft/amidst#342]
I have linux with java 1.8.0_141. 
I installed minecraft and create profile for 1.12 (without mods and without optifine). 
I launched this profile and played few seconds in 1.12 world.
I downloaded and ran amidst v4.3-beta2, and receive error "No profiles found":

![image](https://user-images.githubusercontent.com/6505554/29713467-132d3c26-89b8-11e7-8a8c-c945f9d300cc.png)

I understand, that if you perform the same actions, that most likely you don't get error. But can you try to guess, please, what i did wrong? Thanks a lot!

**Comment by MattSturgeon** [comment]
Without looking into the code, I'd be suspicious of whether the unicode characters in your username/home directory cause an issue. Perhaps amidst is setup to only work with ASCII for paths?

You could try making an ASCII bind mount to your home folder in the root directory and running amidst with `$HOME` set and exported to this mount point, just to rule this out as a possibility.

**Comment by MattSturgeon** [comment]
It could also be an incompatibility with the new Minecraft launcher, since AFAIK it stores profiles differently to the old one.

For either of my suggestions I would have expected to see more bug reports though.

**Comment by dima74** [comment]
@MattSturgeon, thanks for reply! Actually my home folder is `/home/dima`. Text `Домашняя папка` in the screenshot is just file manager name for this.

The problem is that i use pirate launcher, which doesn't add profiles to `launcher_profiles.json`. So I add profiles manually (`"profiles": {"1.12": {"lastVersionId": "1.12"}}`), and amidst work now. Thanks anyway!

**Comment by Ilnene** [comment]
> @MattSturgeon, thanks for reply! Actually my home folder is `/home/dima`. Text `Домашняя папка` in the screenshot is just file manager name for this.
> 
> The problem is that i use pirate launcher, which doesn't add profiles to `launcher_profiles.json`. So I add profiles manually (`"profiles": {"1.12": {"lastVersionId": "1.12"}}`), and amidst work now. Thanks anyway!

Could you show me how you did it? Thanks. I have the same issue

**Comment by dima74** [comment]
@Ilnene afair you just need to create this file (`~` is your [home directory](https://en.wikipedia.org/wiki/Home_directory))
```
~/.minecraft/launcher_profiles.json
```

with content

```
{
    "profiles": {
        "1.12": {
            "lastVersionId": "1.12"
        }
    }
}
```

(replace 1.12 with your minecraft version)

**Comment by amerikos170** [comment]
Здравствуйте помогите пожалуйста я не могу понять почему у меня не показывает версии игры вот мой скриншот 
![Безымянный45345](https://user-images.githubusercontent.com/59229367/71447452-866dff00-273f-11ea-8d4c-0b2beab1c73d.png)

**Comment by amerikos170** [comment]
Еслить ли техподдержка у этой программы?

**Comment by undefinedvalue0103** [comment]
> 
> 
> Здравствуйте помогите пожалуйста я не могу понять почему у меня не показывает версии игры вот мой скриншот
> ![Безымянный45345](https://user-images.githubusercontent.com/59229367/71447452-866dff00-273f-11ea-8d4c-0b2beab1c73d.png)

Чувак, разрабы не понимают по-русски. Поэтому отвечу я. Если юзаешь тлаунчер, попробуй вручную создать конфиг профилей. Комментарий выше как раз об этом.

---------

Dude, devs aren't understand russian. Soo.. I'm answering now. If you using TL, then try to create profiles config by hands. Comment above is about this.

**Comment by aleckeyy** [comment]
Hey, man.
Could you show me how to create the new file for minecraft pirate? Please

**Comment by luan661** [comment]
> @MattSturgeon, thanks for reply! Actually my home folder is `/home/dima`. Text `Домашняя папка` in the screenshot is just file manager name for this.
> 
> The problem is that i use pirate launcher, which doesn't add profiles to `launcher_profiles.json`. So I add profiles manually (`"profiles": {"1.12": {"lastVersionId": "1.12"}}`), and amidst work now. Thanks anyway!

Obrigado meu chapa! Funcionou perfeitamente! (minecraft 1.15.2)

**Comment by liapapaq** [comment]
> > Здравствуйте помогите пожалуйста я не могу понять почему у меня не показывает версии игры вот мой скриншот
> > ![Безымянный45345](https://user-images.githubusercontent.com/59229367/71447452-866dff00-273f-11ea-8d4c-0b2beab1c73d.png)
> 
> Чувак, разрабы не понимают по-русски. Поэтому отвечу я. Если юзаешь тлаунчер, попробуй вручную создать конфиг профилей. Комментарий выше как раз об этом.
> 
> Dude, devs aren't understand russian. Soo.. I'm answering now. If you using TL, then try to create profiles config by hands. Comment above is about this.
Здравствуйте, я к сожалению не все понял что имел в виду человек который написал конфиг, возможно это из за не правильного перевода, не могли бы вы помочь мне и написать пошаговую инструкцию, пожалуйста ?

**Comment by liapapaq** [comment]
@undefinedvalue0103 прочитайте пожалуйста сообщение выше
