### ISSUE TITLE
Toggle legend for biomes

### ISSUE THREAD

**Issue by benjaminapetersen** [toolbox4minecraft/amidst#361]
This is a feature request for consideration.  It would be handy to have a togglable overlay for labeled map colors to make discovery easier.  

Thanks for considering!

**Comment by JDHnz** [comment]
Kind of like the one you get when you click on the highlighter icon in the bottom-right corner of the screen?

**Comment by benjaminapetersen** [comment]
Exactly like that 😃 

Might update my suggestion to also add it to a top menu or use a drawer pull-out icon for discoverability (pencil didn't register to me, as a n00b to the program).

I'll close this, thanks!
