### ISSUE TITLE
exe file is broken

### ISSUE THREAD

**Issue by RepoDraghon** [toolbox4minecraft/amidst#362]
I double click on the amidst-v4-3-beta2.exe file, it acts like it loads but nothing happens... I know this happened after the Win10 updated and had this stupid app prevention thing start but I disabled it and the app still wont open...

**Comment by RepoDraghon** [comment]
The .jar seems to work, I'll use that for now

**Comment by stefandollase** [comment]
Indeed, the exe is just a wrapper for the jar file. The jar file should always work. Nevertheless, the exe file is also supposed to work and thus I will keep this issue open.
