### ISSUE TITLE
Support new 1.13 ocean biomes

### ISSUE THREAD

**Issue by MattSturgeon** [toolbox4minecraft/amidst#372]
18w08a added 8 new ocean biomes, in addition to the existing Deep Ocean and Ocean:

- (Deep) Frozen Ocean
- (Deep) Cold Ocean
- (Deep) Lukewarm Ocean
- ~~(Deep)~~ Warm Ocean

Other than Frozen Oceans being covered in a layer of ice, nothing much distinguishes these biomes yet, and they are likely to change a lot before 1.13 is out.

Regards, this issue can track new 1.13 ocean biomes, whatever their final form looks like on release.

**Comment by kokonoe77** [comment]
I really hope that the author can come back to update. I am also looking forward to 1.13.

**Comment by moulins** [comment]
1.13 snapshots don't work yet in Amidst, but there's a WIP implementation [here](https://github.com/toolbox4minecraft/amidst/tree/1-13-snapshots) (be wary, it's slow!).

In this implementation, I've used the following colors:
![Biome colors](https://i.imgur.com/omsEKuB.png)

In a world, it looks like this:
![Example](https://i.imgur.com/SwifezJ.png)

Feel free to bikeshed on it!

**Comment by TheDiamondDigger** [comment]
I'm new to all this, can you please help me. How do I actually use the 1.13 amidst? I downloaded the files but what do I do with them?

**Comment by mkalb** [comment]
> How do I actually use the 1.13 amidst? 

The current offical version does not support 1.13.
Please read the README, Wiki and FAQ.

[https://github.com/toolbox4minecraft/amidst/blob/master/README.md](https://github.com/toolbox4minecraft/amidst/blob/master/README.md)
[https://github.com/toolbox4minecraft/amidst/wiki](https://github.com/toolbox4minecraft/amidst/wiki)
[https://github.com/toolbox4minecraft/amidst/wiki/FAQ](https://github.com/toolbox4minecraft/amidst/wiki/FAQ)

**Comment by MattSturgeon** [comment]
@TheDiamondDigger you'll have to install [maven](http://maven.apache.org/download.cgi), [download](https://github.com/toolbox4minecraft/amidst/archive/1-13-snapshots.zip) the snapshot branch, then follow the [instructions](https://github.com/toolbox4minecraft/amidst/wiki/Building-from-Source-Code) for building from source.

Not sure if you need to have the [environment](https://github.com/toolbox4minecraft/amidst/wiki/Setting-up-the-Environment) setup or not (before building).

If successful you should get a working jar and exe file that can be run as normal.

**Comment by SkyBlade1978** [comment]
thanks for working on this, I'll pull down your snapshot branch and try it out tonight :)

**Comment by kylerchin** [comment]
Plz, when will a stabel jar file be released?

**Comment by darthvader45** [comment]
Same, I just hope tool hasn't gotten caught up in a RL thing that forced them to quit programming.  This is too good to waste.

**Comment by darthvader45** [comment]
Alrighty, got the version working.  If anyone wants it, I'm putting it in my Dropbox for download.  I'll edit this comment with the link once it's up.

**Comment by 0tobsam0** [comment]
@darthvader45 Seems to work and not be scam! U R my hero! THX!

(New from Seed fails for me, but Open Save Game works fine... dont know why though)

**Comment by moulins** [comment]
This is now supported in the [latest release](https://github.com/toolbox4minecraft/amidst/releases/tag/v4.3-beta4).

**Comment by darthvader45** [comment]
Awesome, thanks moulins.

Golden rule in Minecraft: Never dig straight down.
