### ISSUE TITLE
How could i build that?

### ISSUE THREAD

**Issue by vpontin** [toolbox4minecraft/amidst#373]
I'm trying to build some forks, installed eclipse and such but i dont know how to build from source.

Can somebody help me?

**Comment by moulins** [comment]
Did you look into the wiki? There is [a page](https://github.com/toolbox4minecraft/amidst/wiki/Building-from-Source-Code) which explains exactly how to build from source.

**Comment by vpontin** [comment]
Sorry, didnt see that.
