### ISSUE TITLE
Issues with latest versions and the new launcher

### ISSUE THREAD

**Issue by vpontin** [toolbox4minecraft/amidst#377]
Hi all!

AMIDST seems to not recognize propely the launcher_profiles.json created by the new Mojang Launcher.

I have these profiles set up:
![image](https://user-images.githubusercontent.com/3485505/37548247-41706c4c-2955-11e8-9187-9c17b0f82746.png)

But AMIDST loads botched:
![image](https://user-images.githubusercontent.com/3485505/37548253-48847668-2955-11e8-8f79-d0e0417c50c5.png)

And when loaded the first one profile the version says UNKNOWN version:
![image](https://user-images.githubusercontent.com/3485505/37548261-51ab1184-2955-11e8-8673-fa3196960fd6.png)

@moulins told me to file this issues here, but i dont know if this are still active...

**Comment by stefandollase** [comment]
It seems that this bug was only present in @moulins fork, since the main repo does not use his JSON parser.

Feel free to reopen if the issue still exists in the next release.

**Comment by vpontin** [comment]
Oh! Thanks a lot for the responses! I will look for updates here!

**Comment by vpontin** [comment]
Oops! Still having the issues running beta 3 from this repo:
![image](https://user-images.githubusercontent.com/3485505/38473144-3d049778-3b61-11e8-8030-3bdbc2bfe1c3.png)

From what i searched, seems like the new launcher actually hardcodes a "default" and (if you have snapshots enabled) "snapshot" profiles in the launcher, and no stores those names on JSON.

Since i have both enabled thats why the two first are blank.
