### ISSUE TITLE
SUGGESTION: Add suport for CUSTOMIZED world type

### ISSUE THREAD

**Issue by vpontin** [toolbox4minecraft/amidst#380]
Requesting here because @moulins 's fork doesnt have an issues tab.

Is there any plans to add support for [Customized](https://minecraft.gamepedia.com/Customized) world-type?
In short, this is a very powerful type added by mojang themselves on vanilla which almost everything can be tweaked, from ores spawning to terrain shape (in a way reminiscent of how TerrainControl could tweak the generation).

Not only moulins directly, but anybody forking this or even @stefandollase himself if he still have intention on work on it.

Thanks in advance!

**Comment by stefandollase** [comment]
This is a duplicate of #162
