### ISSUE TITLE
Question about how this functions.

### ISSUE THREAD

**Issue by adracamas** [toolbox4minecraft/amidst#382]
I have a pre-generated world file I wanted to examine mainly to get specific co-ordinates. This appears to generate the 'map' from the seed and not the actual world files. Is that correct?

If so, is there a way to view the world files as they are?

**Comment by BigAlanM** [comment]
Yes, but  not with Amidst.  You need to use something like Minutor.exe
Minutor reads and displays the actual blocks contained in the world files.
It will ONLY display blocks that have been created and saved in those files.
https://github.com/mrkite/minutor/releases
I suggest that Minutor be installed in a folder in the .minecraft folder.  That makes it easier to navigate to a world save folder.
