### ISSUE TITLE
Translation - Traditional Chinese (Taiwan) Support.

### ISSUE THREAD

**Issue by vungsung** [toolbox4minecraft/amidst#394]
Hello, nice to meet u guys!
This project is useful, pretty and new in my opinion.
I know a little bit about python and visual basic but nothing about Java.
Though I have tried install Eclipse Oxygen and import this project directly, it occurred 7225 errors unfortunately ... I still believe there's a way to let me put in Chinese :) Tell me if you need any support, thx.

**Comment by moulins** [comment]
Thanks for proposing to help translate Amidst, but the program doesn't support internationalization yet (see #309). I suggest you subscribe to this issue if you want to be notified if localization become possible in the future.
