### ISSUE TITLE
1.13 snapshots not working

### ISSUE THREAD

**Issue by moulins** [toolbox4minecraft/amidst#395]
As you are probably aware, because of the refactorings made by Mojang, Amidst doesn't load correctly snapshots starting with `18w06a`.

I had a quick look this weekend, thinking I could relatively easily fix the issue, but there has been **lots** of change in the Minecraft code. After grabbing the latest version of the MCP mappings, and some help from the folks at the #mcp IRC, I have a rough idea of how the new worldgen code works.

-----
## Code changes in Minecraft
The worlgen code has been completely reworked, and this will affect Amidst in several ways:
 - Biome ids are now `int`s instead of `byte`s; this shouldn't be an issue for us as already use `short`s
 - The `ChunkProviderSettings` class has been completely reworked, and is now called `OverworldGenSettings`. I didn't find a way to construct an instance from an options `String`, and I suspect there isn't one for now, as the Customized world type doesn't exist anymore (there's the new Buffet type, but I don't have a clue how it works). We can still construct a default instance by calling its constructor though.
- Minor change, the `initializeAllBiomesGenerators` method has been moved to a different class called `LayerUtil`.
- The `IntCache` class is gone, this has to do with the next change (the most annoying one).
- The big change: the layer generation works differently now, and the `GenLayer::getInts` method is also gone. I'll go in more details, because this is important.

In previous versions, when generating biome data, each `GenLayer` would create an `int` array (grabbed from the `IntCache`) and populate it, and we could simply use the array returned by the final layers to access the biome data.  
Now, the `int` arrays are replaced by instances of the `IArea` interface, which has a single method:
```java 
public interface IArea {
   int getIntAt(int x, int y); //returns the data at the given coordinate
}
```
Each layer is an `IAreaFactory`, which acts as a transformer on these `IArea` objects.
**Note:** To avoid calculating several times data at the same coordinate, Mojang use a `LazyArea`, which cache recent computed values (I'm not entirely clear on the details).

The `GenLayer` class is now a small wrapper, whose job is to drive the computation and collect the result in the final array:
```java
public class GenLayer {
   private final IAreaFactory<LazyArea> factory;

   public GenLayer(IAreaFactory<LazyArea> factory) {
      this.factory = factory;
   }

   public Biome[] getBiomeData(int x, int y, int width, int height, @Nullable Biome defaultBiome) {
      AreaDimension areadimension = new AreaDimension(x, y, width, height);
      LazyArea lazyarea = this.factory.make(areadimension);
      Biome[] abiome = new Biome[width * height];

      for(int i = 0; i < height; ++i) {
         for(int j = 0; j < width; ++j) {
            abiome[j + i * width] = Biome.getBiomeFromId(lazyarea.getIntAt(j, i), defaultBiome);
         }
      }

      return abiome;
   }
}
```

## Impact on Amidst
If the code collected the data in an `int` array as before, this would be the end of it and the changes to Amidst would be minimal, but unfortunately the `getBiomeData` method returns a `Biome` array.

I see two ways to resolve this:
### Translating back into an `int` array
We can transform back the `Biome` object into its IDs, by using the Minecraft biome registry. To avoid calling into `SymbolicObject`s all the time, we should maintain a `Map<Biome, Integer>` on our side.

#### Pros
 - It should be straightforward to implement.

#### Cons
 - I'm wary of the performance implications of making a Map lookup for each data element. We may need a specialized Map type to have good performance here.
 - It forces us to do an allocation on each call (we can have a `int[]` in the `MinecraftInterface`, but the minecraft code will allocate a new `Biome[]` on each call).

### Using the underlying `LazyArea` directly
To avoid the theoretically useless roundtrip between `Biome` and `int`, we may be able to extract the `IAreaFactory` from the `GenLayer` and use it directly to collect the data into an `int` array. As before, we cannot use the `SymbolicObject` for every `getIntAt` call, so we need to somehow hoist this out the of the loop. The only way I see for now is to use a bytecode generator to generate the bytecode for the loop at runtime, but maybe there's a better way.

#### Pros
 - Better performance: no need for Map lookup, this should be as efficient as the minecraft code.
 - No allocation: we can reuse the same `int[]` to collect the data everytime.
 - It opens avenues to get even better improvements later, for example for the single-coordinates calls in structure checks.

#### Cons
 - It's complex to implement, and we need to dynamically generate bytecode to get acceptable performance.
 - We probably need an external library to do this, something like [ASM](http://asm.ow2.io/).

**Edit:** We can maybe get to close-to-native performance by using the MethodHandle API to call the Minecraft `LazyArea`, which should be *much* easier than writing bytecode!

## Phasing out the hardcoded biome list?

These changes may also be a good opportunity to remove the Amidst biome list, and instead use the Minecraft biome registry as a source of truth, as biomes now have an unambiguous id. This would be a good first step for eventually supporting modded Forge profiles with custom biomes in the long run.  
However, it's not that simple, because we still need a biome list somewhere to specify the colors we use in the map.

## Splitting the `MinecraftInterface` and the `ClassTranslator`

Whatever option we choose, I think it is also a good time to create a new `MinecraftInterface`, as proposed in #146. Even if the two versions (old and new) have some code in common, maintaining the two in the same classes will quickly become a nightmare.  
I've pushed [a branch](https://github.com/toolbox4minecraft/amidst/tree/1-13-snapshots) with some quick-on-dirty modifications to dispatch the correct `MinecraftInterface` based on the version, with a stub for the `1.13` implementation, go criticize it! (This doesn't use `VersionFeatures` yet, as I didn't see a good way to use it here)

------

Phew, that was longer than expected!
Feel free to give your thoughts on this.

**Comment by stefandollase** [comment]
I see you did a lot of hard work there. It already looks great. It's too bad that there is such a loss in performance, but at least it works and we can always try to optimize it later. Thanks a lot.

So, I reviewed your changes up to b63014929bd86680b9c1f6892f9aa0ec9e188020, and really only in 84ab32b4b78aae913363206e8bc6d21f02649cb4 I had a question, which is if you are sure that the removed biomes are really never user in any of the supported Minecraft versions. I always left them in because I was unable to find a reliable source of truth which states which biomes exist in which version, and because they did no harm. I am just curious where to find such information.

I read the comments in this thread some time ago, but forgot about my thoughts and comments by now. Also, today my time for this project is over, so I will have to re-read it at some day.

Again, thanks for all of your work and keep going =)

**Comment by moulins** [comment]
> I had a question, which is if you are sure that the removed biomes are really never user in any of the supported Minecraft versions.

I used the biome list on the [wiki](https://minecraft.gamepedia.com/Biome#Biome_IDs), and I double-checked in the (current) Minecraft code. I don't think Mojang ever completely removed a biome (e.g. Extreme Hills Edge hasn't been generated for a long time, and the biome is still in the code), so it should be good.

**Comment by moulins** [comment]
**Note:** I saw [this post0](https://old.reddit.com/r/Minecraft/comments/8p7mvt/quad_witch_hut_finder_partial_fix_for_113) on the minecraft subreddit, which says that the generation algorithm for witch huts (and other structures) changed in 18w06a.

We should verify that it's indeed the case, and implement it.

**Comment by hjpoe** [comment]
Someone I know has had a problem with strongholds disappearing after they log out of a world for the first time. They'll go and check the new world for a stronghold, and then The next time they log in, it won't be there anymore, or anywhere in the vicinity. We checked in spectator mode. I doubt that was done on purpose.

**Comment by fwiffo** [comment]
I can volunteer handle the structure changes this weekend. I filed a separate issue for it #399

**Comment by moulins** [comment]
Thanks for proposing to help!

If you do want to do the changes yourself, you should be aware of the fact that Amidst uses a single layer for all temple-like structures (currently, Jungle Temples, Desert Temples, Igloos, and Witch Huts; see the code [here](https://github.com/toolbox4minecraft/amidst/blob/master/src/main/java/amidst/mojangapi/world/WorldBuilder.java#L141-L150)). This may make the implementation a little awkward, depending of the changes to the algorithm.

If you have questions about the Amidst code, feel free to ask. ;)

**Comment by TheTerrorByte** [comment]
Could you perhaps release a precompiled binary that works with 1.13 instead of expecting us to spend all day downloading and installing a million different things?
