### ISSUE TITLE
Seed Searcher

### ISSUE THREAD

**Issue by Easteregger** [toolbox4minecraft/amidst#396]
It would be nice if you could add a tool to amidst which searches seeds automatically after certain criterias and saves matching seeds in a document. For example that the seeds need to have certain bioms in a certain range. 

An example for what i mean is something like this: https://www.reddit.com/r/Minecraft/comments/659quu/i_built_a_minecraft_seed_search_utility_that_uses/
 
Thanks in Advance.

**Comment by moulins** [comment]
There was some discussion about it in #120, and an implementation has been started, but it never was finished, and is currently disabled.  
I'm aware of two out-of-tree implementations, which you can maybe try out (there may be others, but I don't know of them):
 - https://github.com/jmessenger235/amidst (see #169 for the syntax), which is based on an old version of Amidst;
 - https://github.com/moulins/amidst/tree/seed-filter (see [here](https://github.com/moulins/amidst/wiki/Seed-Search-(WIP)) for the syntax), which is mostly up-to-date (disclaimer: I made it :stuck_out_tongue:)

However, I wouldn't expect either one of these implementations to make it in the main version anytime soon.

**Comment by seanCodes** [comment]
@moulins It looks like there hasn't been a release yet with the v4.3-beta4 changes that were merged recently. I’d love to try out the seed filter in that fork but I don’t know how to build the app from source.
