### ISSUE TITLE
Feature Request: Search for Elytra Boats

### ISSUE THREAD

**Issue by mwalden2004** [toolbox4minecraft/amidst#398]

**Comment by moulins** [comment]
The Boats are generated as part of End Cities (the wiki said ~60% of End Cities will have a boat), so you can use the **End City** and **Likely End City** markers, and have a good chance of finding a boat.

Detecting whether a boat will spawn at a particular city would require Amidst to reimplement a big part of the structure generation code of End Cities, so it's very unlikely to happen.

**Comment by mwalden2004** [comment]
Ahh,   It'd be a lovely feature, and would save people hours of work, like
yesterday.

**Comment by mwalden2004** [comment]
I have some experince in Java,Perhaps i'll attempt it, and if I do it: i'll open a pull?

**Comment by MattSturgeon** [comment]
I'm not sure this is technically possible.

While the skeletal generation follows a purely seed-based algorithm, many details vary based on additional in-game variables and RNGs (e.g. which areas are generated and loaded).

This means that if you generate the End twice (using the same seed) you may not see the same terrain and (by extension) cities.

This is explained better in the wiki [here](https://github.com/toolbox4minecraft/amidst/wiki/The-End-map)

**Comment by mwalden2004** [comment]
Closing this in hopes to delete it.
