### ISSUE TITLE
Feature Request: Location of Buried Treasure [1.13]

### ISSUE THREAD

**Issue by ericdl** [toolbox4minecraft/amidst#402]
Minecraft 1.13 will introduce a new in-game structure called [Buried Treasure](https://minecraft.gamepedia.com/Buried_treasure). Like woodland mansions and ocean monuments, it can be found using an [explorer map](https://minecraft.gamepedia.com/Explorer_Map). It would be great if AMIDST could show the coordinates of Buried Treasure locations.

**Comment by michaelpaulsen** [comment]
and the new biomes too plz !!!! love this BTW  use it all the time

**Comment by sas8jedi** [comment]
So given you have implemented the new 1.14 Villages and the Pillager Outposts could you consider looking into this again?
There are quite a few Buried Treasures without corresponding Shipwreck or Ruin map that could be founded only with /locate or external tools/mods.
Is it the only structure from the /locate list currently not implemented in AMIDST?

**Comment by moulins** [comment]
@michaelpaulsen The new biomes have been added in 488525b2 :)

@sas8jedi Yes, this is the only missing structure in Amidst. I don't remember why I didn't implement it back when 1.13 came out, but I'll look into it (hoping it's not too hard...).
