### ISSUE TITLE
Some spawn point seems off target for versions since 18w06a

### ISSUE THREAD

**Issue by k-jiang** [toolbox4minecraft/amidst#404]
It seems that some seeds have different spawn points (default home) in 1.13-pre5/6.

e.g. `-7358205204588637752`
In 1.12.2, the spawn point is (256,128), however in 1.13-pre6, the spawn point is (167,68) in game.

Not sure it is a intended game change or a snapshot bug.

**Comment by moulins** [comment]
I tested your seed, and the first version for which the spawn point is inaccurate s `18w06a`. This coincide with the biome generation revamp, so it seems a (maybe unintended) consequence of that.

The version of Amidst which works for the latest snapshots still indicate the spawn point at (256,128), so the algorithm must have changed.

**Comment by moulins** [comment]
**Note:** This may be related to #136.
