### ISSUE TITLE
MC 1.13 - Impossible to open AMIDST

### ISSUE THREAD

**Issue by vincentsch87** [toolbox4minecraft/amidst#411]
Hello,

I'm a French mac user. I use the last version of MC 1.13 and of AMIDST. When I want to open AMIDST, I have an error message (see screenshot).

[bugAMIDST.pdf](https://github.com/toolbox4minecraft/amidst/files/2214630/bugAMIDST.pdf)

**Comment by kz5ee** [comment]
I'm getting the same thing.

![amidsterror113](https://user-images.githubusercontent.com/5105197/43039448-fe5e7fa0-8cf2-11e8-884d-1eced5b2056a.png)

**Comment by moulins** [comment]
Amidst doesn't (yet) work for Minecraft 1.13; this is #395.

If you know how to build Amidst from the sources (see the Wiki), you can try using [this branch](https://github.com/toolbox4minecraft/amidst/tree/1-13-snapshots).

Closing as duplicate.
