### ISSUE TITLE
Error while loading a profile

### ISSUE THREAD

**Issue by me616** [toolbox4minecraft/amidst#417]
Help 🌵 
![www](https://user-images.githubusercontent.com/33800039/43426989-958b76f6-940c-11e8-80a9-9cfeb05947c4.jpeg)

**Comment by moulins** [comment]
Which version of Amidst are you using, and which profile are you trying to load?

**Comment by Doctor5555** [comment]
I've got the same issue using amidst 4.2 (downloaded from sourceforge). It will not load any of the profiles that I have, including 1.12.2 and 1.13. The error shown in the screenshot above seems to be the same as the one I get when attempting to load 1.13.

**Comment by moulins** [comment]
Amidst 4.2 is an old version, can you try with the [latest version](https://github.com/toolbox4minecraft/amidst/releases/tag/v4.3-beta4)?

**Comment by stebo02** [comment]
I was having the same issue with version 4.2 but for me, it doesn't occur with v4.3-beta4

**Comment by moulins** [comment]
Well, the forge download page is maintained by a third-party, so you need to contact him/her to update the download link.

Closing this, as the bug doesn't happen on the latest version.
