### ISSUE TITLE
Location of Shipwrecks appears to be incorrect

### ISSUE THREAD

**Issue by hpoom** [toolbox4minecraft/amidst#418]
If you load seed `600000222763165` in both creative minecraft and in amidst. Fly to the location amidst reports as locations of Shipwrecks. There are no ships to be found.

You can find Shipwrecks in this seed, but none of them are at the locations reported by amidst.

Seed came [from reddit](https://www.reddit.com/r/Minecraft/comments/93indu/all_biomes_within_1k_blocks_lots_of_structures/) but I can produce the same results with random seeds also. Ocean ruins and other ocean features appear to be reported as close to their real location, but shipwrecks are incorrect from all my testing.

**Comment by fwiffo** [comment]
Is this possibly related to MC-131462? It was reintroduced in pre7 but was fixed again in 18w30a. The timing seems suspicious.
