### ISSUE TITLE
export as  a HTML file

### ISSUE THREAD

**Issue by michaelpaulsen** [toolbox4minecraft/amidst#419]
I don't know if it is possible but it'll be very cool if there was a way to export the map to HTML. It would be very useful to server owners that whant to share where the biomes in there world are but don't have the resources (or time) to make maps in game. I also see seed reviewers using this on sites like plaint minecraft

I was thinking that it could be a <canvas> tag witch use a bit map style data structure... or maybe you guys can make an 2d array (an array of arrays) of the numeral boime ids then I could write the code to display that?

**Comment by moulins** [comment]
This sounds a lot like #327, #245 or #232.
For now, you can take a screenshot of the Amidst map by using `ctrl+T`. It's not perfect (you don't get the exact coordinates of structures, for example), but this is at least a rough way to do it.

**Comment by michaelpaulsen** [comment]
I was thinking of an export screenshot to HTML feature it would be just like takeing a screenshot but you would have an html file that you can then put on to a website without having to do any coding... I dont think we'll ( I would like to help in any way i can tho im only 16 tho my dad is a professional HTML programmer so I been into this kinnda stuff since i was 6) not even have to do too much if we just are going to use a img tag... tho i was also thinking that it would have the locations too
