### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by scillablade** [toolbox4minecraft/amidst#421]
Hi, 

When I try to run the program this ask for a java 1.8.0 (this version es old now), please update the program to work well with the current java version. 

Thanks

**Comment by moulins** [comment]
Amidst should work correctly with all Java versions older than 1.8. What error message do you get exactly?

**Comment by snuk182** [comment]
OpenJDK versions over 1.8 are not supported, due to the different major/minor version numeration.
![image](https://user-images.githubusercontent.com/493209/51443157-d1d48d80-1ce4-11e9-97d8-d81ce9b387ca.png)

**Comment by moulins** [comment]
No response in 6+ months; closing this issue.
