### ISSUE TITLE
Feature request: add mob spawner layer

### ISSUE THREAD

**Issue by InsaneJ** [toolbox4minecraft/amidst#422]
Could you please add a layer to display mob spawners?

If possible could you use different icons for different kinds of spawners? I.e. a zombie icon for a zombie spawner, a skeleton icon for a skeleton spawner, etc.

**Comment by JDHnz** [comment]
This isn't really possible. See #57 for the details of why that is the case.

**Comment by moulins** [comment]
Closing as duplicate of #57.
