### ISSUE TITLE
Crash on loading seed. Minecraft 18w33a

### ISSUE THREAD

**Issue by kvan73** [toolbox4minecraft/amidst#432]
Crashes on loading this -1432235024972872834 seed or opening save file on minecraft v1.13.1. Task manager shows ever increasing java instance events. End task is only way to exit amidst. Log file attached, I think. lol
[2018-08-22-1.log.gz](https://github.com/toolbox4minecraft/amidst/files/2311487/2018-08-22-1.log.gz)

**Comment by moulins** [comment]
The crash actually happens since 18w33a (I was actually in the process of posting the issue myself :stuck_out_tongue: ).

And yeah, these errors have always been very spammy, we should do something about it...

**Comment by jgerbert1983** [comment]
Mine did the exact same thing when I tried both opening a save and a new seed.
