### ISSUE TITLE
amidst crash on loading saved file MC 1.13.1

### ISSUE THREAD

**Issue by TomOlsen** [toolbox4minecraft/amidst#434]
As soon as I try to load the saved file amidst starts producing error messages and new windows continuously.  One of the windows says amidst has crashed. I've attached a screen capture and the log files from my 3 tries.

[picture 2018-08-23 23_22_55](https://user-images.githubusercontent.com/4047580/44565314-1a375180-a72d-11e8-8773-63a10a9ca938.png)

[2018-08-23-1.log.gz](https://github.com/toolbox4minecraft/amidst/files/2317038/2018-08-23-1.log.gz)
[2018-08-23-2.log.gz](https://github.com/toolbox4minecraft/amidst/files/2317039/2018-08-23-2.log.gz)
[latest.log](https://github.com/toolbox4minecraft/amidst/files/2317040/latest.log)

**Comment by moulins** [comment]
This is a duplicate of #432.

**Comment by TomOlsen** [comment]
Thank YOU!  Just downloaded the new version, works GREAT so far!
