### ISSUE TITLE
Leave biome highlight active when menu is closed

### ISSUE THREAD

**Issue by Synetech** [toolbox4minecraft/amidst#442]
Currently, closing the biome-highlight menu will revert the display to highlighting all biomes instead of just the selected ones. This is frustrating because the menu covers a fair portion of the map, and also it is included in the screenshot.

Please make it so that the selected biomes remain active when the menu is closed.

**Comment by hippolytevalicon** [comment]
Please fix this issue, it's very boring to have the half of the map hidden by this box.
Having a way to search biomes would be nice too.
