### ISSUE TITLE
Generate entire world map

### ISSUE THREAD

**Issue by Deshiba** [toolbox4minecraft/amidst#448]
I'm playing on a world (seed= Yggdrasil) with large biomes and I tried using amidst to find where specific biomes are in relation to the spawn island.  Doing this I run into the issue where everything generated previously unloads when new area's are shown.

Is there a way where I can generate an entire minecraft world map?
If not, would you consider a  function to generate the world map as an image?

**Comment by Zitchas** [comment]
The Minecraft world is effectively infinite, or at least massively huge, and thus probably impractical.

Being able to render a specific region to an image file would be useful, though.

**Comment by moulins** [comment]
Exporting the world is already covered by #21; closing as duplicate.

P.S.: If you are only interested in biomes, you can look at your seed with the default world type and multiply every coordinate by 4 to get the larges biomes version. Some details (rivers and structures) will be differents, but this should give you a rough idea of the geography of the world.
