### ISSUE TITLE
Is there an option to locate Mushroom Fields / Field Shores?

### ISSUE THREAD

**Issue by smmmadden** [toolbox4minecraft/amidst#449]
I just installed the latest build of Amidst for the very first time, but couldn't see any option to search for Mushroom Fields and Mushroom Field Shores.  Is this a planned search option? -Thanks, Steve

**Comment by moulins** [comment]
You can use the Biome Highlighter (icon in the bottom-right) to mask all biomes except the ones you want; this'll make it easier to find them.

We don't plan to have an option to search specific biomes in the near future, but if you are ready to build Amidst from source, some implementations exist. (Look at issue #120 and at this [https://github.com/toolbox4minecraft/amidst/issues/396#issuecomment-386837393](url))

**Comment by smmmadden** [comment]
That did it, I totally missed the icon in the bottom right corner - not where I would expect to find anything. :-) Thank you very much!
