### ISSUE TITLE
Wrong stronghold locations since 18w06a

### ISSUE THREAD

**Issue by uncovery** [toolbox4minecraft/amidst#453]
I have a world here where the coordinates for the stronghold are given as 1359 / 1168, but the actual coordinates are 1359 / 958

**Comment by moulins** [comment]
Could you give us the seed and the Minecraft version used?

**Comment by uncovery** [comment]
Minecraft version is in the title :)
Seed is -6588404564181618918

**Comment by littlebroto1** [comment]
Well, I am guessing that it has something to do with the amount of stages that amidst uses. Probably, a later stage ended up shifting the stronghold to a different position. Even still, 210 blocks is a lot for it to shift and I think the biome has something to do with the shifting amount as the server finds a suitable place to fit the stronghold. (I am not an expert on the subject so this is just my speculation)
