### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by Avanxia** [toolbox4minecraft/amidst#455]
Hello,

Everytime I start  Amidst, I get the following message : see enclosed file.

I use Windows 7, minecraft 1.12.2, java edition adn Java 1.8.0 181

Best regards.

Patrice
![starting amidst](https://user-images.githubusercontent.com/43848830/46471210-8354bf00-c7d9-11e8-808c-4644e9b5daee.JPG)

**Comment by moulins** [comment]
- Are you sure you are using the latest Amidst release (v4.2-beta5)?
- Are you sure the Minecraft profile isn't modded?

**Comment by Avanxia** [comment]
Sure, last v4.2 release, on your site, no modded profile

 

De : moulins [mailto:notifications@github.com] 
Envoyé : jeudi 4 octobre 2018 17:07
À : toolbox4minecraft/amidst
Cc : Avanxia; Author
Objet : Re: [toolbox4minecraft/amidst] Launcher (#455)

 

*	Are you sure you are using the latest Amidst release (v4.2-beta5)?
*	Are you sure the Minecraft profile isn't modded?

**Comment by Avanxia** [comment]
But works with the v4.3-b5

Thanks

 

De : moulins [mailto:notifications@github.com] 
Envoyé : jeudi 4 octobre 2018 17:07
À : toolbox4minecraft/amidst
Cc : Avanxia; Author
Objet : Re: [toolbox4minecraft/amidst] Launcher (#455)

 

*	Are you sure you are using the latest Amidst release (v4.2-beta5)?
*	Are you sure the Minecraft profile isn't modded?
