### ISSUE TITLE
Amidst v4.3-beta5 completely black

### ISSUE THREAD

**Issue by horse14t** [toolbox4minecraft/amidst#456]
So I downloaded the latest version of Amidst for 1.13.1 and I tried to load my group's seed and nothing loaded. There are also no errors or anything. It's not frozen either because I can still load a new seed and use the menus and stuff but nothing ever appears.
Here's an image:
[https://orig00.deviantart.net/2d91/f/2018/279/d/e/capture_by_horse14t-dcorxi4.png](url)

My computer is Windows 10 and Minecraft is at 1.13.1

**Comment by moulins** [comment]
Which Java version are you using? (You can see at the start of the logs, in **Help > Display Log Messages**)

**Comment by horse14t** [comment]
Holly crap it just started working!
I decided to redownload it and delete the Logs file and load a random seed to mess with it a bit and after about 5 minutes it finally started generating the map! Though quite slowly.

**Comment by moulins** [comment]
Yeah, biome generation is a lot slower in 1.13 compared to previous versions.

I'll close the issue, but feel free to reopen it if the bug reappears.
