### ISSUE TITLE
Support for "unusual" minecraft folders

### ISSUE THREAD

**Issue by vpontin** [toolbox4minecraft/amidst#457]
The new launcher allows not only to point for a specific folder per profile, but with --workdir we can actually tell it [any location for the .minecraft folder we want](http://hopper.minecraft.net/help/guides/changing-work-directory/).

But amidst doesnt allow the user to point for a custom .minecraft location.

Can you add this feature? Thanks!

**Comment by moulins** [comment]
Would mirroring the launcher and adding a `--workdir` commandline argument be sufficient. If it is, it seems easy enough to add.

**Comment by vpontin** [comment]
Great!

**Comment by vpontin** [comment]
Any news about this?

**Comment by vpontin** [comment]
So the feature was already implemented (but i havent find it before) 😛 

Sorry for bothering you and thanks for the patience!
