### ISSUE TITLE
Spamming Java error 1.13.1

### ISSUE THREAD

**Issue by PaintyPaint** [toolbox4minecraft/amidst#458]
When I try to load a seed, the screen will remain black for a few seconds (though it shows my coordinates move with my cursor), but quickly spams an error message so fast that I couldn't copy and paste the error message. I couldn't close the window without using task manager to end the java process. I did get a screencap of the error message though. Unfortunately, it cuts off because it was spamming so fast I couldn't copy it all down.

![untitled drawing 1](https://user-images.githubusercontent.com/44079364/46847367-09609f00-cdb2-11e8-8f62-e3e7ba0a2a59.png)

**Comment by moulins** [comment]
This looks a lot like issue #432, which should be fixed for Amidst v4.2-beta5. Which version are you using?

**Comment by PaintyPaint** [comment]
That would probably be it! I tried downloading amidst from a few different places (I don't know much about it, I'm fairly new to this, so sorry!) and I've downloaded beta3 and beta4, along with just plain old no beta v4.2. Thanks for your quick reply, sorry for reporting what ended up being just user error!
