### ISSUE TITLE
Didn't work without internet connection

### ISSUE THREAD

**Issue by opysium** [toolbox4minecraft/amidst#459]
If i haven't a internet connection amidst is not work with 1.13 or 1.13.1, it's just work with 1.12.2 it just show me 1.12.2 version in latest version selection, i'm using latest beta for 1.13.1
Sorry for bad language

**Comment by moulins** [comment]
Without internet connectivity, Amidst will use its local version list to determine the latest Minecraft; this version may be out-of-date. However, Amidst uses the content of the Minecraft JAR to determine the actual Minecraft version, so the biomes, etc, should still be accurate.

To check that the "true" version is correct, look at the title of the Amidst window after loading a profile: it should have **(recognized: 1.13.1)** at the end.

**Comment by opysium** [comment]
Before I realized, the launch installed 1.13.2, created the profile and selected 1.13.1, and the program worked. I'm sorry, it's my fault. :)
