### ISSUE TITLE
Support for PE seed limits (random)

### ISSUE THREAD

**Issue by lolkje** [toolbox4minecraft/amidst#463]
As far as I can tell, most Pocket Edition biomes map correctly with Amidst. An option to limit the random seed lengths to PE limits would be awesome. Even if other spawns (shipwrecks etc) dont match PE, Amidst is better than nothing. Thanks!

**Comment by moulins** [comment]
This is the same feature as #27 (albeit for different reasons), so I'll close this as duplicate.
