### ISSUE TITLE
Won't load profile

### ISSUE THREAD

**Issue by FakenameBill** [toolbox4minecraft/amidst#465]
Instead of loading a profile, AMIDST displays a popup error message: 
![amidsterror](https://user-images.githubusercontent.com/10792864/48320990-07763f80-e5ed-11e8-87bc-e8780c59b198.PNG)
Another strange issue is that the default profile for "latest release" appears blank in the profile list, but every profile that I've created appears normally.
I tested this issue in the 4.3 beta 4 and beta 5. In beta 5, the profile loads but any maps produced are completely black. In beta 4, the black map would appear and the screen was immediately filled with error messages. Many were the same as the one pictured above, but the bottom-most one appeared to be some kind of log with a link to this github page at the top for reporting the error. Unfortunately it was mostly covered by other windows and I couldn't get to it to take a screenshot or copy the text.

**Comment by moulins** [comment]
Which profile were you trying to load when you got the error message?

-----

For the issue with the blank maps, could you copy/paste the logs? (You can display them by going in **Help > Display Log Messages**)

**Comment by pajicadvance** [comment]
Amidst doesn't support 1.13.2 yet, v4.3 beta 5 is up to 1.13.1 only.

**Comment by StephAChamber** [comment]
apologies, i meant 1.13.1

**Comment by aproximateknowledge** [comment]
having similar issues. using 1.13

**Comment by moulins** [comment]
No response in 6 months; closing this issue.
