### ISSUE TITLE
Ocean Ruins and Shipwrecks mapped in older releases

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#466]
I just used Amidst v4.3-beta5 to map a seed using my release 1.2.5 profile and the oceans are full of ocean ruins and shipwreck icons.
It also occurs in 1.1
This doesn't happen in 1.3.2, 1.4.2, 1.5.2, 1.6.4, 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11.2. or 1.12.2.

**Comment by moulins** [comment]
Do you have the `Enable All Layers` option selected?

When layers are force-enabled like this, they will often use the latest algorithm, even if it doesn't apply to the selected version. (Personally I think this feature should be removed, as I don't think it makes much sense, but maybe someone else find it useful?)

**Comment by moulins** [comment]
The `Enable All Layers` feature has been removed in commit 5366d94e; this bug should no longer appear.
