### ISSUE TITLE
Fails to open when .minecraft is in a non-default directory

### ISSUE THREAD

**Issue by SamPoulton** [toolbox4minecraft/amidst#467]
So I've relocated my .minecraft folder to my D drive, which means it's not in my appdata folder. As a result, Amidst tells me that I need to install Minecraft and doesn't open.

**Comment by moulins** [comment]
You need to specify the location of the `.minecraft` directory with a command-line argument (see [here](https://github.com/toolbox4minecraft/amidst/wiki/Command-Line-Interface)):
```
java -jar Amidst.jar -mcpath <yourpath>
```
