### ISSUE TITLE
Igloo and Witchhut spawning

### ISSUE THREAD

**Issue by KingParity** [toolbox4minecraft/amidst#470]
On Minecraft 1.13.2, in the seed 1988960633, there is an igloo that amidst says will spawn, but doesn't spawn at 9464 -21319, and there is a witch hut that spawned, but amidst didn't say it would at 12005 -22684

I am using amidst v4.3-beta5

**Comment by moulins** [comment]
Can't reproduce; for me, (9464, -21319) is in the ocean, and there is no structure at (12005, -22684).
Are you sure the seed and the Minecraft version are correct?
