### ISSUE TITLE
Amidst Website Version

### ISSUE THREAD

**Issue by ThePieMonster** [toolbox4minecraft/amidst#472]
Feature request for viewing a pre-selected seed from a web server. 

_Example_
Server owner enters seed into a config file
Starts web server with Amidst-Web web application in it
Website shows data that would be normally present when using Amidst

**Comment by moulins** [comment]
Amidst will probably never be a Web application; for a server owner, there are lots of tools which are more adapted and offer more features, such as [Dynmap](https://www.spigotmc.org/resources/dynmap.274/).

**Comment by ThePieMonster** [comment]
@moulins It looks like Dynmap does not support a Biome view. Just a FYI.
https://github.com/webbukkit/dynmap/issues/963
