### ISSUE TITLE
[Feature Request] Option for manual path to .minecraft directory

### ISSUE THREAD

**Issue by applefritter2** [toolbox4minecraft/amidst#479]
Hi there, I have minecraft operating under a different working directory than the standard installation path.  Amidst is unable to locate it.  Would it be possible to add a specify path prompt if the program cannot automatically locate the .minecraft directory?  Thanks!

**Comment by moulins** [comment]
You can pass the `-mcpath` argument to Amidst via the command line to specifiy the `.minecraft` folder you want to use.

See https://github.com/toolbox4minecraft/amidst/wiki/Command-Line-Interface.
