### ISSUE TITLE
Quarter vs full resolution for structure generation?

### ISSUE THREAD

**Issue by stefandollase** [toolbox4minecraft/amidst#48]
@Treer In #42 you mentioned that in the seed -1364077613 an ocean monument was missing when the quarter resolution map was used. I checked this and noticed, that we currently do use both: the quarter resolution map and the full resolution map. This is also how it is implemented in Amidst v3.7. 

Thus, I am not entirely sure whether the current behavior is correct. Maybe you can verify that?

**Comment by BigAlanM** [comment]
How is resolution changed from quarter to full and back?

**Comment by Treer** [comment]
I'll verify it, but IIRC both sized maps are employed by Minecraft for different tests, so it's not alarming for Amidst to also use both. The missing ocean monument and other structure bugs in Amidst were caused by when it *only* used the quarter-res map for all tests.

**Comment by Treer** [comment]
The ocean monument in question is present in Amidst4 (it's the one right next to the spawn), so everything's good.

**Comment by stefandollase** [comment]
Thanks for checking it :-)

@BigAlanM There is no GUI option to change the resolution. It is a mechanism that is used by the game itself. For some operations it uses a quarter resolution map of the biome data. Because of the low resolution it can perform many operations much quicker.
