### ISSUE TITLE
Handing over the Amidst project

### ISSUE THREAD

**Issue by stefandollase** [toolbox4minecraft/amidst#483]
During my studies, I was interested in how Amidst works exactly, especially how the interaction with Minecraft works, so I started to dig up the code base. After some time and a lot of refactorings, I took ownership of the Amidst project. I learned a lot from managing the project, about coding but also about project management, and I would like to say thank you for this opportunity.

I finished my studies some time ago and entered the working life. Now, I only have little remaining spare time which I need to manage more strictly. I noticed that I am not willing to spend the amount of time for the Amidst project that would be required to prevent it from starting to rot. However, it would be a shame to let the project rot. That means, it is time for me to step back.

Thus, I am happy to announce that @moulins agreed to take ownership of the project and to lead the development of Amidst. He is a member of the community which has been active in the development for quite some time.

**Comment by moulins** [comment]
Hi, I'm pleased to take the lead of this project, in which I've been invested for several years now.

I've joined the toolbox4minecraft organization as an owner, but some things still need to be done in order to finalize the project hand-over:
- [ ] Remove all mentions of the toolbox4minecraft@gmail.fr email address (@stefandollase couldn't cleanly transfer it to an physical person).
- [ ] Recover the MinecraftForum account and the forum thread (access was lost during the MinecraftForum migration).

**Comment by Zitchas** [comment]
Thank you for both of your hard work in making this very useful tool.

As a member of the community that enjoys using AMIDST, I greatly appreciate its utility and ease of functionality.

**Comment by Zombifyed** [comment]
Hi, I'm almost positive this is too soon to ask. I'm sure, as most of us are eager to see this working for the latest update. When do you expect this to be up and running for the most current version?

**Comment by MattSturgeon** [comment]
@Zombifyed [beta6](https://github.com/toolbox4minecraft/amidst/releases/tag/v4.3-beta6) has initial 1.14 support, supporting 1.14.2 shouldn't be much of an issue.

**Comment by LovesAsuna** [comment]
Considering the practicality of the software, I have moved this plugin to the China Forum. http://www.mcbbs.net/thread-725282-1-1.html Please take a look. Thank you for making the excellent software.

**Comment by moulins** [comment]
As the MinecraftForum account and thread were lost in the MinecraftForum migration, I have created new ones:
* [Forum account](https://www.minecraftforum.net/members/toolbox4minecraft)
* [Forum thread](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/2970854-amidst-map-explorer-for-minecraft-1-14)

I have also created a new contact address to replace the old one: toolbox4minecraft@outlook.com.

The README and the wiki have been updated to reflect these changes.
