### ISSUE TITLE
Illager outpost not on the map

### ISSUE THREAD

**Issue by AxelTravix** [toolbox4minecraft/amidst#485]
I just downloaded the beta 6 and it doesnt show the outpost near my spawn

seed: -872785901810337855
its located a bit north east of spawn

**Comment by archiesholland** [comment]
v4.3-beta6 does not show Pillager Outpost at 80 ~ 592
Seed: -6792108410385598455
It does, however, show a non-existent Mineshaft at those coordinates.

**Comment by moulins** [comment]
@AxelTravix What are the exact coordinates of the Outpost ? I can't find it by exploring the world.

@archiesholland Confirmed the presence of the Outpost in-game.  
As for the Mineshaft, note that they will sometimes fail to generate completely. In this case, you will only find a square room with a dirt floor at the indicated coordinates.

--------

I've added your report to the master issue #117. Please report future false negatives here.
