### ISSUE TITLE
1.14 structures not mapped to real locations

### ISSUE THREAD

**Issue by SlimeDog** [toolbox4minecraft/amidst#486]
AMIDST 4.3-beta6

Profile: 1.14
Seed: -5322040752997563589

Clean (new) installation on clean 1.14 server. Structures and biomes displayed on AMIDST map do not correspond to locations in world. More information available on request, and if needed, access to the test server to verify locations.

**Comment by SlimeDog** [comment]
Hmmm. AMIDST does correspond to a newly-generated MC 1.14 world.

**Comment by moulins** [comment]
I don't know if either Spigot or Multiverse promise to generate the same worlds as vanilla Minecraft, you should probably ask them.  
In any case, this doesn't look like a bug on Amidst's end, so I'll close this issue.

**Comment by SlimeDog** [comment]
Thanks for the review.

**Comment by HurryPeng** [comment]
Same here. I tested using the seed `31415`, and amidst generated similar maps through `1.12` to `1.14`, which were accurate for Minecraft worlds generated in `1.12` and `1.13`, but not for `1.14`. It looks like the world generation algorithm has somehow been changed in `1.14`, but amidst hasn't. All worlds are vanilla and generated on my PC, single player.

**Comment by skys215** [comment]
Same here, the generated map is different from the map I play under Spigot.
