### ISSUE TITLE
v4-2 and v4-3-beta5 none of them can load 1.14

### ISSUE THREAD

**Issue by ZL-Asica** [toolbox4minecraft/amidst#488]
<img width="937" alt="a" src="https://user-images.githubusercontent.com/40444637/57426728-fd0ec880-7252-11e9-9502-0f1105da81b8.png">
like the screenshot above, cannot load 1.14

**Comment by moulins** [comment]
You need to use the [v4.3-beta6 release](https://github.com/toolbox4minecraft/amidst/releases) to load Minecraft 1.14 profiles.
