### ISSUE TITLE
Amidst Crashes

### ISSUE THREAD

**Issue by PeacePlays** [toolbox4minecraft/amidst#497]
![Screen Shot 2019-06-06 at 1 30 14 PM](https://user-images.githubusercontent.com/49123331/59057210-810e9d00-885f-11e9-9316-3babb3f34c69.png)
 I am only able to screenshot the error message. The previous version works fine (amidst-v4-3-beta5)

**Comment by moulins** [comment]
Which version of Minecraft are you using, and when does the crash occurs exactly?

**Comment by PeacePlays** [comment]
1.13.2 and the crash occurs on selecting a world. I have tried multiple worlds.

**Comment by PeacePlays** [comment]
It will open the latest 1.14 worlds

**Comment by moulins** [comment]
This is #487, which has already been fixed for the next version. ;)
Closing as duplicate.
