### ISSUE TITLE
How to stop Bitdefender blocking AMIDST?

### ISSUE THREAD

**Issue by Immaculala** [toolbox4minecraft/amidst#500]
When I run AMIDST it isn’t recognising my profiles.
Research suggests it may be Bitdefender.
Bitdefender is asking me for “the URLs, domains or IP addresses” to add to web exceptions.

Sorry, I’m not very IT savvy and need help knowing what do I type in?

**Comment by moulins** [comment]
Amidst will query `https://launchermeta.mojang.com` to retrieve the Minecraft version list; adding this address to the BitDefender whitelist may solve your issue?

**Comment by moulins** [comment]
No response in 6 months; closing this issue.
