### ISSUE TITLE
Amidst Failing to load versions

### ISSUE THREAD

**Issue by Kelambrad** [toolbox4minecraft/amidst#502]
As of 25/06/19, Amidst wont detect the versions. 
I think its to do with the new updated launcher.

Some info,
Using the .Jar same issue.
Using the .Exe same issue. 
Extra info.
Java Edition, Minecraft files saved in Appdata/Roaming

**Comment by Master00Maniac** [comment]
I'm also having this issue. Previously, when I could choose which launcher to use, switching to the beta launcher would cause Amidst (beta 6) to be unable to see my 1.14 profiles. Switching back resolved the issue at the time, but that beta launcher is no longer opt-in, and thus I cannot resolve the issue by switching back now.

**Comment by moulins** [comment]
What do you mean exactly by "won't detect the versions"? Does Amidst crash with an error message or is the profile list simply empty?

**Comment by Kelambrad** [comment]
It displays the instances you have made inside the Minecraft Launcher, For me I have an instance for a few different versions of minecraft. Where it would say the version, it says 'Not found' and ill add this wasn't an issue before the launcher updated. Maybe the launcher update changed something?

**Comment by archiesholland** [comment]
This is the error I'm getting.  Note that I also have 1.13.2 available, so I'm 
able to access the log messages.

[amidst&latest_MC_launcher_errors.txt](https://github.com/toolbox4minecraft/amidst/files/3326899/amidst.latest_MC_launcher_errors.txt)

**Comment by iainwb** [comment]
This is because the version string for 1.14.3 has not been added to the code.

**Comment by Kelambrad** [comment]
Makes some sense to why it wouldn't, work but It does the same red box not found for all my versions of minecraft, super odd

**Comment by archiesholland** [comment]
So, working for me again, sort of.

Long story short:
Mojang has updated the Launcher again, but still acted wonky for me.
Installed clean, fresh copy of MC from minecraft.net.
Created clean, empty C:\Users\<username>\AppData\Roaming\.minecraft folder.
Installed 1.14.3-OptiFine_HD_U_F1_pre15.
Reinstalled AMIDST.
Now I get this:

![amidst](https://user-images.githubusercontent.com/23512508/60202607-eaf3e400-9818-11e9-8eae-2f7871f87ec0.png)

But it at least works again.  Kinda.
