### ISSUE TITLE
No profiles at all.

### ISSUE THREAD

**Issue by NillerESSKEETIT** [toolbox4minecraft/amidst#505]
It worked just fine 2 days ago, but now it just doesn't show any profiles. Does this have anything to do with the new Minecraft launcher? 

Please help, Niller.

**Comment by moulins** [comment]
Duplicate of #502.

The profile should work if you select a specific Minecraft version instead of "Latest snapshot/release".

**Comment by NillerESSKEETIT** [comment]
It's so much slower, than it was 3 days ago. Do you know what causes this issue?

-Niller
