### ISSUE TITLE
Amidst remarkably slower than before.

### ISSUE THREAD

**Issue by NillerESSKEETIT** [toolbox4minecraft/amidst#506]
I had a problem the last day, but that got fixed. Now it's just so much slower than it was before.

What causes this issue?

**Comment by moulins** [comment]
Slower compared to which version, and which version of Minecraft?

If you're comparing 1.14 with 1.12, the slowness is due to the changes in the Minecraft code for biome generation, which is much less efficient.

**Comment by NillerESSKEETIT** [comment]
I tried opening a 1.14.2 profile, but it's just so slow. I also used a 1.14.2 profile before I got an issue

I don't know if makes sense, or if it helps, but I tried my best. English isn't my first language.

**Comment by moulins** [comment]
No response in 6 months; closing this issue.
