### ISSUE TITLE
Request: Load possible end city chunks instead of using influence algorithm

### ISSUE THREAD

**Issue by burgerguy** [toolbox4minecraft/amidst#516]
Instead of using the current influence algorithm, reflect end chunk loading classes from the minecraft jar to load end city chunks and check their height that way. It seems pretty difficult to implement, but I remember seeing this in one of the todo's.

**Comment by moulins** [comment]
This would indeed be nice, but there are a lot of drawbacks:
- As you said, it seems difficult to implement;
- It will increase the "API surface" with Minecraft, which means more chances for Amidst to break with new Minecraft versions;
- It will probably be extremely slow.

As such, I don't see this being implemented in the foreseeable future.
