### ISSUE TITLE
Stronghold locations inconsistent

### ISSUE THREAD

**Issue by burgerguy** [toolbox4minecraft/amidst#518]
While this issue may seem the same as issue #453 and #492, those were marked as fixed and the code was modified for version 4.3. Now in 1.14.4, these stronghold locations seem to be off again. For example, in seed 5732151237465294404, amidst reports that there should be a Stronghold at 16000, 17888. However when you tp to that location and look under, there is no stronghold to be seen, and if you do /locate, the nearest one is over 1000 blocks away. I have a feeling it's due to the mc devs reverting the changed stronghold algorithm that happened in 18w06a.

EDIT:
I compared the minecraft 1.14.4 code and minecraft 1.14.3 code and found that there were no changes in generation with strongholds. I also went and loaded up the same seed in 1.14.3 and found that the same stronghold was not there. I also found that some of the strongholds were correct, but others were not. One thing that I saw with all of the mineshafts that didn't generate was that there was some other structure like a mineshaft that was in it's place. It's probably an mc bug more than an amidst bug but a check to see if any other structures are overlapping might be a good workaround.

**Comment by ChiefNerdCraig** [comment]
There is a similar example with Amidst v4.4-beta1 and Minecraft 1.15.1 on seed -1056582770: 
Amidst reports a stronghold at 14992,13760, but it is not in game (a mineshaft is though).
The closest stronghold to that point according to /locate is near 15083,12982 (confirmed in game), but it is not in Amidst.
