### ISSUE TITLE
v4.3

### ISSUE THREAD

**Issue by Arctic90x** [toolbox4minecraft/amidst#522]
I downloaded the latest update v4.3 and it's not detecting my Forge

My Forge is " **1.12.2-forge1.12.2-14.23.5.2837** "

**Comment by moulins** [comment]
Amidst doesn't support Forge profiles; use a vanilla profile instead.

**Comment by Arctic90x** [comment]
Odd because I found one that's on Curse

https://www.curseforge.com/minecraft/mc-mods/amidst-for-forge

**Comment by Arctic90x** [comment]
And I download loaded that one and it said there was an update and it brought me here

**Comment by moulins** [comment]
Amidst for Forge is a separate fork of Amidst maintained by fraenklc; you can find it [here](https://github.com/fraenkelc/amidst-forge).
