### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by LovesAsuna** [toolbox4minecraft/amidst#525]
I use multimc,but amdist can't detect my .minecraft folder

**Comment by Shadowhenge** [comment]
I have the same issue, but not using anything other than the the default launcher.  It wont detect it and theres no option to tell it where it is.

**Comment by OronDF343** [comment]
+1. I use exclusively MultiMC, would be nice to have a config file or command-line option for this.

**Comment by moulins** [comment]
Duplicate of #126.
