### ISSUE TITLE
Mineshafts in post 1.12.2 maps have many false positives

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#527]
I first noticed this in viewing maps of 1.13.2 worlds.
The number of mineshafts displayed is considerably more than when entering the same seed with 1.12.2 selected.
I just compared a 1.13.2 map to a 1.14.4 map and the mineshaft locations appear to be identical but, as I said above much more numerous than in 1.12.2.
I created a world in 1.13.2 and visited several locations where mineshafts were indicated.
1 out of 4 actually existed in that world. (I didn't make an extensive survey).
BTW:  I'm running Windows 10 and Java jre 1.8.0_221

**Comment by moulins** [comment]
This is related to #493. The mineshaft algorithm changed in 18w06a, and as I've said in the issue:
> The new algorithm has been implemented, but there are still some false positives.
> According from my understanding of the Minecraft source code, it seems like the mineshaft's central room check the blocks around it before generating.

You've seen a lot more false positives than I thought would occur, so I'll have to have look again.

**Comment by BigAlanM** [comment]
I've just discovered that[https://www.chunkbase.com/apps/mineshaft-finder]( https://www.chunkbase.com/apps/mineshaft-finder)
Seems to handle indicate the correct mineshafts in Release 1.13 and above.

**Comment by PhilipBorgesen** [comment]
> This is related to #493. The mineshaft algorithm changed in 18w06a, and as I've said in the issue:
> 
> > The new algorithm has been implemented, but there are still some false positives.
> > According from my understanding of the Minecraft source code, it seems like the mineshaft's central room check the blocks around it before generating.
> 
> You've seen a lot more false positives than I thought would occur because of this extra check, so I'll have to have look again.

As of 1.16.4 the chance to generate a Mineshaft is 0.004 and not 0.01 as Amidst currently is using. I don't know in which version the chance changed.

**Comment by moulins** [comment]
> As of 1.16.4 the chance to generate a mineshaft per chunk is 0.004 and not 0.01 as Amidst currently is using. I don't know in which version the chance changed.

Huh you're right, mineshaft chances have been at 0.004 since 1.7.2; I don't know where the 0.01 used by Amidst comes from ;D
