### ISSUE TITLE
Ability to Choose Game Folder

### ISSUE THREAD

**Issue by pjlasl** [toolbox4minecraft/amidst#530]
The application assumes the user installed the game in the .minecraft folder. If the game isn't found in the default folder location, could you display a browser folder dialog box?

I have my game installed in a different location other than .minecraft (its on a external hard drive).

**Comment by burgerguy** [comment]
This should not be too difficult to implement, considering there's already methods for setting a location for a .minecraft folder. I'll make a pull request when I hear back from @skiphs .
