### ISSUE TITLE
Amidst is not able to find .minecraft directory. 

### ISSUE THREAD

**Issue by Just2Lit** [toolbox4minecraft/amidst#536]
I just downloaded amidst-v4-3.exe but on when i run this it says: 
 Amidst is not able to find your '.minecraft' directory, but it requires a working Minecraft installation.

I do have minecraft installed but it's not in the .minecraft directory. Any idea how to fix this?

**Comment by burgerguy** [comment]
Do `-mcpath [directory to .minecraft folder]` to set a custom .minecraft path.
