### ISSUE TITLE
[suggestion] biome filter

### ISSUE THREAD

**Issue by gendalv** [toolbox4minecraft/amidst#537]
add a biome filter, where all biomes are hidden, except the selected ones from a list

**Comment by stefandollase** [comment]
https://github.com/toolbox4minecraft/amidst/wiki/Biome-Highlighter

**Comment by gendalv** [comment]
is there a ruler to measure distances on the map? or a search function that shows distances of biomes to spawn?

**Comment by stefandollase** [comment]
Regarding the ruler, there is a feature request #475. I am not aware of a feature request that, given a specific map and biome, searches for the closest location to spawn being in that biome. Either way, both are currently not implemented.

**Comment by gendalv** [comment]
Also add dungeon spawners locations please

**Comment by stefandollase** [comment]
Before asking a question, please search whether it has already been answered. Also, please use different issues for different questions.

Searching for *dungeon* yields [this](https://github.com/toolbox4minecraft/amidst/wiki/Behind-the-Scenes#why-does-amidst-not-display-dungeons) FAQ entry as well as issues #57 and #180. This answers your question pretty well.

**Comment by gendalv** [comment]
I've been just using chunkbase site and I thought that amidst would've made it redundant eventually
