### ISSUE TITLE
Include selected WorldType in screenshot

### ISSUE THREAD

**Issue by rm-code** [toolbox4minecraft/amidst#54]
Hello,

I think it would be nice to either display the selected WorldType on screen or concatenate it to the screenshot's name. This way it's easier to create multiple seeds for different world types without confusing them.

Best wishes
Robert

**Comment by stefandollase** [comment]
Thanks for the suggestion. I also think this is a good idea. A similar suggestion was made by @BigAlanM in #32 . The problem described there still remains. How do we handle custom worlds? They can have a quite long parameter text.

I think there is no point in adding the parameters to the filename. Maybe, they are also not that important to display on the screen. However, it should be possible to include just the world type in both, the filename and on the screen. We will look into this when we have the time.

**Comment by rm-code** [comment]
> How do we handle custom worlds? They can have a quite long parameter text.

Maybe just add "custom" as a type?

**Comment by stefandollase** [comment]
Yes, I guess this will work.

**Comment by stefandollase** [comment]
This will be included in the next release.

**Comment by rm-code** [comment]
Nice, thank you :+1:
