### ISSUE TITLE
Use native font on macOS

### ISSUE THREAD

**Issue by EdricChan03** [toolbox4minecraft/amidst#553]
Currently, the program looks a bit ugly on macOS as it uses the former system font - Lucida Grande.

However, newer versions of macOS use the Sans Fransisco font.

**Comment by moulins** [comment]
I *think* this is a Java Swing issue, so it probably can't be solved easily.

I'll keep this open anyway.

**Comment by burgerguy** [comment]
This can be changed with a simple look and feel adjustment. In fact, setting the look and feel to the system default would make it look much better on almost all platforms.

**Comment by moulins** [comment]
I've created PR #662, which add the possibility to select the system look and feel in the Settings menu.

@EdricChan03 Could you check if this solves your font issue?

**Comment by moulins** [comment]
@EdricChan03 

> Testing the PR locally, it seems that setting the look and feel to "System" has no effect on the default font. Here are some screenshots of the changes:
>
> \<snip>

Drat, I had hoped changing the look & feel would solve the issue.

After some looking around, I found [this blog post](https://www.pushing-pixels.org/2017/01/17/using-san-francisco-font-in-swing-applications-on-a-mac.html) which explains the underlying issue.  
Unfortunately, there doesn't seem to be a good solution to resolve this; so as this is only a minor issue, I'll close this.
