### ISSUE TITLE
Amidst Crash

### ISSUE THREAD

**Issue by Tobitanna** [toolbox4minecraft/amidst#558]
Amidst crashes on me once I try to load a map from a seed. It gives me a pop-up box with [info] stuff.
![Amidst Crash](https://user-images.githubusercontent.com/56882918/67299169-89cbdc80-f4a9-11e9-883c-2f00b3dce696.png)

**Comment by moulins** [comment]
Which version of Minecraft are you using? Amidst doesn't presently support Minecraft versions `19w36a` and higher (see #538).

**Comment by Tobitanna** [comment]
That would be why. I am on version 19w42a. When will it be updated?

**Comment by moulins** [comment]
I don't know exactly yet, but definitely before Minecraft 1.15.

In the meantime, you can use a `19w35a` profile specifically for Amidst; biomes and structures are identical to the latest snapshot.
