### ISSUE TITLE
Stop unnecessary redrawing on idle

### ISSUE THREAD

**Issue by magicus** [toolbox4minecraft/amidst#562]
Currently Amidst consumes an astonishingly amount of CPU cycles when sitting idle, and not drawing any new parts of the map. 

After some digging, I figured out that it depends on the ThreadMaster that schedules a call to onRepaintTick.run() every 20th millisecond. This in turn will cause the entire window to be redrawn, even if nothing has changed. (This is the reason for the "FPS 50" shown on the map.)

A quick test by changing this to being called every 2000 ms instead showed drastically lower CPU, confirming that this was indeed the culprit.

However, that also showed the reason for this constant redrawing: When I moved the mouse, the information widget which shows the current coordinates and biome type was only updated every 2 seconds...

So just removing the forced constant repaint is not a solution. Instead, the code needs to separate the overlay information that is caused by the user moving the mouse. This should preferably be repainted as a result of a mouse moved event, and not by a fixed 20 ms clock. The biome/world icon images from the Fragments should not be redrawn at all, if nothing has changed. 

Untangling the code to implement a more suitable way of handling graphics update will unfortunately take some effort. I intend to try to fix it, though.

**Comment by magicus** [comment]
Note that fixing this will also drastically improve Amidst performance when drawing new parts of the map. Currently the CPU has to compete between redrawing the view and calculating new biome data. On my computer, with a somewhat simple timing measurement, the time spent from starting Amidst until the initial window (I started it with a profile and seed selection from CLI to start rendering immediately) went from 25 seconds, to roughly 15 seconds, when I lowered the repaint tick to run every 2000 ms instead.

**Comment by NetLightDev** [comment]
@magicus @moulins @pfalstad
Thanks for initiating and investigating this issue!
I also noticed unnecessary CPU usage when Amidst is idle
(which causes my laptop's fan working for no reason... ;)
and can't wait for this optimization to be implemented.
