### ISSUE TITLE
Amidst generated map not matching expected world spawn.

### ISSUE THREAD

**Issue by Prolael** [toolbox4minecraft/amidst#567]
**Summary**:  
I'm quite new to using amidst, but it seems so simple that I can't figure out what I'm doing wrong.  
I have a server that I've ran for the last 2 months. I went over to the server.properties and copied the seed I had originally put in there. When I view this seed in Amidst, the region around spawn (where is being played) is nothing I recognize.

I also attempted to take the seed I had, created a new singleplayer world, and yes, this matched what I recognized as the right seed. So I go into amidst, import this singleplayer world, and the map is the same as from the seed of the server, but again, nothing recognizable.  
I went as far as to move my player next to the water in the save, loaded that and amidst shows me to be in the middle of the forest with no water within 100 blocks.

I checked if I used the right profile in amidst as the launched game, this checks out.. 

**Reproduction**:
1) open amidst, open from seed: -918787345, normal level type.
2) Start a singleplayer world with said seed.
3) Stand next to water as reference point (for example 18,-139)
4) Save the world (exit)
5) Open amidst again, now import the saved world.
6) on the dialog I chose multiplayer, but both seem to have the same result.

**Expected results**:  
When I click on my name, I should stand next to water on the map.

**Actual results**:  
When I click on my name (right next to spawn), I confirm the coordinates are the same as in game, but there is no water in sight,

I am using amidst 4.3 and profile default which is Minecraft 1.14.4, oddly enough it says (recognized: UNKNOWN) next to it.

**Comment by hjpoe** [comment]
I created a world with the seed you are using, and checked out the area that you mentioned in your reproduction. I found the water that you mentioned. This watery area is a lake. You will notice that if you look at the biome (F3), it says it is forest (red box). 

![image](https://user-images.githubusercontent.com/35583004/69990191-379fc180-1513-11ea-847c-1b77b303ac14.png)

I'm not really sure I can explain how this works, but I believe it is because this is the data that Amidst uses to generate the map.

**Comment by Prolael** [comment]
Hi, thanks for looking into my issue!  
So is it correct that these bodies of water shouldn't appear on the map amidst draws?  
That's weird, because other bodies of water do get drawn by amidst, such as oceans and rivers.

**Comment by machinesmith42** [comment]
Those are actual biomes and and are listed as such

**Comment by machinesmith42** [comment]
A small pool of water is not a biome

**Comment by Prolael** [comment]
Hi, thanks for your replies, I'll close this issue.
