### ISSUE TITLE
Pillager outposts arent in their spots

### ISSUE THREAD

**Issue by ShaDoggo** [toolbox4minecraft/amidst#577]
Amidst version: v4-3
Minecraft version used by Amidst: 1.14.4
Minecraft version used to verify existence: 1.14.4
missing structure: pillager outpost
seed:  -6775876771139909019
coordinates: -924,196
additional information: The same issue happened in adifferent outpost, its in the same seed, the cords are 1748,-412

**Comment by moulins** [comment]
Thanks for the report!

Are the Pillager Outposts present in-game, but not visible on the Amidst map, or the opposite? (visible on the Amidst map, but not present in-game)

**Comment by thegamerx1** [comment]
Title: Pillager outposts arent in their spots
Moulins: Are outposts missing?
lel
