### ISSUE TITLE
Versions not appearing

### ISSUE THREAD

**Issue by thegamerx1** [toolbox4minecraft/amidst#588]
![image](https://user-images.githubusercontent.com/34986564/70911883-13fc7100-2013-11ea-8964-a0c08a2456b1.png)
And yes i have 1.14.4 installed
![16_12_2019_javaw_2sPAEGYeZo](https://user-images.githubusercontent.com/34986564/70912150-a3098900-2013-11ea-921a-dce6d5576238.jpg)

**Comment by thegamerx1** [comment]
found the problem that could lead to a fix im in a cracked launcher and it doesnt use the profiles.json i tried to remove it to see if it generates with all versions but it doesnt. And now it says i dont have any versions Opening and launching game againd does not help could some1 send me a proper profiles.json or the devs make it check for profiles in the version folder instead of the json file?

**Comment by thegamerx1** [comment]
![image](https://user-images.githubusercontent.com/34986564/70934755-e9281200-203e-11ea-846e-88d5afaef5ba.png)
Got it working but still want a fix wont be modifing the json file every fucking to version
> My launcher_profiles.json
```
{
  "profiles": {
    "1.14.4": {
      "name": "1.14.4",
      "lastVersionId": "1.14.4",
      "allowedReleaseTypes": [
        "release",
        "snapshot"
      ]
    }
  }
}
```

**Comment by moulins** [comment]
You could try launching Amidst *via* the command line ([wiki](https://github.com/toolbox4minecraft/amidst/wiki/Command-Line-Interface)) and specifying the `-mcjar`, `-mcjson` and/or `-mcpath` arguments.
