### ISSUE TITLE
every time i enter a seed or load a random seed it crashes

### ISSUE THREAD

**Issue by Warp9000** [toolbox4minecraft/amidst#604]
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]

**Comment by moulins** [comment]
Are you using the latest release ? (v4.4-beta1)  
If so, please provide the full Amidst log (you can find it in **Help > Display Log Messages**).

**Comment by HTMLSniper** [comment]
have the same error https://pastebin.com/8dDjAyEU

**Comment by Zax927** [comment]
Same thing happens to me
