### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Schneehummel94** [toolbox4minecraft/amidst#622]
I found a bug in your program...by applying the seed 1673634123162548769 the program crashes.
i tried it  multible times and it always crashes.
Hope you can fix it. 
Version: v4.3
MC Version: 1.15.1

Edit: It doesn't work and crashes with every other seed to, i think its something wrong with the latest version of Minecraft.

**Comment by moulins** [comment]
Duplicate of #538; this is fixed in the latest release (v4.4-beta1).
