### ISSUE TITLE
Trying to open word in 1.15.1.

### ISSUE THREAD

**Issue by goradPL** [toolbox4minecraft/amidst#638]
Hi, I want to tell you about that, my Amidst doesn't work. I will be very thankful if someone can help me.
[AMIDST CRASH.txt](https://github.com/toolbox4minecraft/amidst/files/4027276/AMIDST.CRASH.txt)

**Comment by moulins** [comment]
Duplicate of #538; this is fixed in the latest release (v4.4-beta1).
