### ISSUE TITLE
Structure icons (bikeshedding)

### ISSUE THREAD

**Issue by Treer** [toolbox4minecraft/amidst#65]
In AmidstExporter I have lightened the NetherFortress icon, we may want to do the same:

![nether_fortress original](https://cloud.githubusercontent.com/assets/6390507/13032040/2e09a85a-d338-11e5-8f26-3d826f5e27ab.png) `->` ![nether_fortress](https://cloud.githubusercontent.com/assets/6390507/13032031/0142a330-d338-11e5-8c50-5af9304f871c.png)

And tried to come up with a better witchhut icon, I don't like the original icon:
![witch](https://cloud.githubusercontent.com/assets/6390507/13032103/6b7c8a7a-d33a-11e5-8896-cd96ba59808c.png)
but it's hard to do better as the witch hat makes a head too big to draw a witch the same way village icons are drawn.

![witchhut1](https://cloud.githubusercontent.com/assets/6390507/13032032/03d36756-d338-11e5-8585-a9ebd970e301.png)
![witchhut2](https://cloud.githubusercontent.com/assets/6390507/13032033/063109b8-d338-11e5-8dbe-8ddd1c1cb421.png) - many of the other structure icons just show the primary material
![witchhut3](https://cloud.githubusercontent.com/assets/6390507/13032034/08a3db12-d338-11e5-8dec-d6af02a7cbd0.png) - but a witchhut has a primary material *and* produces witches.
![witchhut4](https://cloud.githubusercontent.com/assets/6390507/13032036/0c48262e-d338-11e5-90c0-121cb54d4459.png) - actually they are built from both planks and logs.
![witchhut5](https://cloud.githubusercontent.com/assets/6390507/13032037/0e3f5786-d338-11e5-8ae0-d9d3e5b6ecc4.png) - back to logs, but with a lightened witch
![witchhut6](https://cloud.githubusercontent.com/assets/6390507/13032038/106b7990-d338-11e5-8867-73efabb4b145.png) - hat made darker

I have used the last one in AmidstExporter bcause it's more obvious to people what it is (e.g. when screenshots are posted online) but it doesn't fit the Amidst style very well.

So if anyone wants to try improving witch hut icons...

**Comment by BigAlanM** [comment]
I have no problem with the new icons.
Actually I've never cared for the the dark icons.
Yours are a definite improvement.

**Comment by stefandollase** [comment]
I also do like the new icons. I think we should take the new nether fortress icon for sure. For the Witch Hut, I prefer the cauldron.

**Comment by Treer** [comment]
![witchhut7](https://cloud.githubusercontent.com/assets/6390507/13046553/86aaa892-d42d-11e5-828a-32276ee646e3.png)

**Comment by stefandollase** [comment]
I like it :-)

**Comment by stefandollase** [comment]
I am closing this, since the new icons are included in the new release.
