### ISSUE TITLE
Menu item naming inconsistencies (macOS)

### ISSUE THREAD

**Issue by EdricChan03** [toolbox4minecraft/amidst#650]
Currently, the application has some menu item naming inconsistencies which are shown in the screenshots below:

![Screenshot of "World" menu](https://user-images.githubusercontent.com/20047125/72276738-9eb0aa00-366b-11ea-9788-a3d0872b7a1a.jpg)

A couple of issues with the menu above:

- Inconsistent capitalisation (e.g. "Save player locations" vs "Take Screenshot...")
- Menu item for a specific question (this could be moved to a help button inside of the functionality itself)

![Screenshot of "File" menu](https://user-images.githubusercontent.com/20047125/72276800-b851f180-366b-11ea-9c6b-43bd77dd4dc1.jpg)

More issues with the menu above:

- Same as before.
- There's no need for an "Exit" menu item on macOS when macOS already provides a "Quit [app]" menu item by default in the application's menu.
- Ellipses should be appropriately added to menu items following the suggestion below:
  > **Use an ellipsis whenever choosing a menu item requires additional input from the user.** The ellipsis character (…) means a dialog or separate window will open and prompt the user for additional information or to make a choice. - [Human Interface Guidelines for Menu Anatomy > Menu Item Titles](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/#menu-item-titles)

As documented in the [Human Interface Guidelines for Menu Anatomy](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/#menu-and-menu-item-titles), it suggests the following regarding naming menus/menu items:

> **Use title-style capitalization.** Title-style capitalization is used consistently for menu and menu item titles throughout the system. For more information, see [Apple Style Guide](https://help.apple.com/applestyleguide/#/apsg1eef9171).

Additionally, in v4.4-beta1 of Amidst (which introduced support for a native menu bar for macOS - see #540), the "Layers" menu does not seem to do anything until you enter a seed/random seed/open a save game. As such, I suggest that the menu should be hidden unless a seed is entered.

---

EDIT: I've forgotten about the "Settings" menu - I think it should be moved to the application menu under a menu item named "Preferences..." with a keyboard shortcut of <kbd>Command</kbd> + <kbd>;</kbd> like what most other native macOS programs use. A dialog would then show up with a set of checkboxes similar to the existing settings menu items.

**Comment by burgerguy** [comment]
Addressed some of this in PR #651

**Comment by moulins** [comment]
I've merged #651, which should address the capitalization and ellipsis issues.

The Mac OS X-specific concerns are still applicable, so I'll leave this issue open.

-----

> There's no need for an "Exit" menu item on macOS when macOS already provides a "Quit [app]" menu item by default in the application's menu.

I'm not sure having a different set of menu items depending on the OS is a good idea, but I'll consider it.

> Additionally, in v4.4-beta1 of Amidst (which introduced support for a native menu bar for macOS - see #540), the "Layers" menu does not seem to do anything until you enter a seed/random seed/open a save game. As such, I suggest that the menu should be hidden unless a seed is entered.

The "World" and "Layers" menus should be greyed-out as long as a seed has been entered. Is that not the case on OS X?

> I've forgotten about the "Settings" menu - I think it should be moved to the application menu under a menu item named "Preferences..." with a keyboard shortcut of Command + ; like what most other native macOS programs use. A dialog would then show up with a set of checkboxes similar to the existing settings menu items.

As before, having OS-specific menu items seems a bad idea. Furthermore, I find the current "Settings" menu practical; I fear that having a separate settings window will decrease the usability of the interface, at least as long as the number of settings stays small.

**Comment by moulins** [comment]
@EdricChan03 Now that #662 is merged, could you check if the "World" and "Layers" menus correctly appear greyed-out just after loading the profile?

**Comment by EdricChan03** [comment]
@moulins Sorry for the long wait! I didn't notice that you replied.

Anyways, the "World" and "Layers" menus correctly appear greyed-out when the "Default Look & Feel" is selected.

![Screenshot of Amidst menu on "Default Look & Feel"](https://user-images.githubusercontent.com/20047125/72986076-58550b00-3e22-11ea-9961-1b834a740fe5.jpg)

However, on the "System Look & Feel", the "World" and "Layers" menus are still displayed:

![Screenshot of Amidst menu on "System Look & Feel"](https://user-images.githubusercontent.com/20047125/72986060-525f2a00-3e22-11ea-8b79-290c634d4869.jpg)

 I suggest that the menus should be removed instead of being disabled.

**Comment by moulins** [comment]
> I suggest that the menus should be removed instead of being disabled.

As I've said previously, I don't want to include MacOS-specific code in Amidst, because I won't be able to test it and so it will inevitably rot with time.  
I'll close this issue as "won't fix" for now.
