### ISSUE TITLE
Amidst

### ISSUE THREAD

**Issue by Tomboy09123** [toolbox4minecraft/amidst#667]
amidst keeps crashing

**Comment by moulins** [comment]
Are you using the latest version? (v4.4-beta1)

**Comment by Tomboy09123** [comment]
yea i am, 1.15.2

**Comment by moulins** [comment]
Then, this is fixed in the latest Amidst version (v4.4-beta1). Closing as duplicate of #538.

**Comment by Tomboy09123** [comment]
How do I fix it then?

**Comment by moulins** [comment]
You can download the latest release [here](https://github.com/toolbox4minecraft/amidst/releases).
