### ISSUE TITLE
Color profiles folder name was changed.

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#69]
I just noticed that the issue Extending the documentation mentions providing documentation for the biome colors profile feature.
Has anybody else noticed that this no longer works?
Creating a "biome" folder in the folder that Amidst 4.0 resides in doesn't cause it to create a default.json file.
The last version that I'm aware of where this works is AmidstExporter v1.32.

**Comment by BigAlanM** [comment]
Dooh!
I just read the issue named  Saving screenshot crash? and noticed that at some point in time the name for the biome color profiles had been changed from "biome" to "biome-color-profiles".
Upon making that change Amidst v4.0b8 wrote the default.json and when I copied my profiles over to that folder and restarted the settings menu had the Biome color file submenu.

**Comment by stefandollase** [comment]
Yes, I changed the name during the refactoring process, however I am not that convinced anymore, that it was a good decision. I will change it back to 'biome'.

The reason to change it was, that I thought 'biome' alone was not expressive enough.

The reason to change it back is that 'biome-color-profiles' might be too expressive: If we allow more biome information than just the color in the future, the directory name does not match the contents. The second reason to change it back is to keep compatibility with Amidst v3.7.

**Comment by stefandollase** [comment]
This is fixed by #72.
