### ISSUE TITLE
won't work on multiple versions

### ISSUE THREAD

**Issue by OhnkytaBlabdey** [toolbox4minecraft/amidst#694]
I installed both 1.14.4 and 1.15.2, but the application only figured 1.15.2 version.

![image](https://user-images.githubusercontent.com/26178665/74096835-c5fd7880-4b3e-11ea-91d9-549b59c15180.png)

![image](https://user-images.githubusercontent.com/26178665/74096837-ce55b380-4b3e-11ea-9bcb-ada2809733c7.png)

**Comment by moulins** [comment]
Is this a custom launcher? Version detection is only guaranteed to work properly when using the official Minecraft Launcher.

**Comment by OhnkytaBlabdey** [comment]
yes, I used a third party launcher. Thanks a lot, I'll try an official laucner.
