### ISSUE TITLE
Alignment issue after selecting system look and feel (Windows 10)

### ISSUE THREAD

**Issue by KnapSac** [toolbox4minecraft/amidst#702]
After selecting the 'System look and feel' from the new option in the settings menu, the submenus aren't properly aligned. Instead of displaying the extra submenu to the right of the already open submenu, they overlap slightly. I have attached a screenshot displaying the error.

![image](https://user-images.githubusercontent.com/34449626/75450768-b324d980-596f-11ea-988a-9ed43f10f98b.png)

**Comment by KnapSac** [comment]
I'd like to look into fixing this, if that's alright?

**Comment by burgerguy** [comment]
May take a bit of screwing around with some nasty swing stuff, but it may be possible. You can give it a shot, but I think this is a problem with the Windows LAF as a whole, rather than specifically amidst.

**Comment by moulins** [comment]
@KnapSac Feel free to look into it, but as @burgerguy said, it's probably an issue with the Look & Feel provided by Windows.

Could you copy-paste the L&F name here? (you can find it in the logs when starting Amidst)

**Comment by KnapSac** [comment]
```
[info] Using look & feel: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
```

**Comment by KnapSac** [comment]
When using Windows Explorer I noticed that their submenus also overlap, so it may just be a design choice in Windows. Considering that I'm using the Windows L&F, I think this may actually not be a bug, but rather an intended feature. As I have no experience with swing, and it seems this is actually intended behavior, I'll not look into this for now.
