### ISSUE TITLE
Feature suggestion: Create random seed with biome at spawn

### ISSUE THREAD

**Issue by EduMenges** [toolbox4minecraft/amidst#703]
Hi,
This a suggestion to enhance the random seed generation. 
I want to create a world in which the spawn point is in a swamp biome. Currently, I need to create lots of random seed worlds until a swamp biome is generated and pick the one that I want. While for a swamp it is something doable, this is very time comsuming when someone wants to spawn in a rare biome, such as a mushmroom island.
So in the menu settings, there would be a setting called "Spawn in Biome", in which the user would be able to chose from a list of biomes. Then, everytime the generate random seed is prompt, Amidst generates random seeds until the spawn is located within the selected biome.
I think It wouldn't be a resource hungry because only the spawn chunks would need to be generated in order for the check to be valid.

**Comment by moulins** [comment]
This is #120; closing as duplicate.

**Comment by EduMenges** [comment]
> 
> 
> This is #120; closing as duplicate.

So is it going to be developed?

**Comment by moulins** [comment]
There are currently no plans for doing so, but it is on my long-term wishlist.
