### ISSUE TITLE
Request: Map marker for user-provided coordinates

### ISSUE THREAD

**Issue by LiamFry** [toolbox4minecraft/amidst#705]
It would be **very** helpful if a "sticky" pin or marker were created on the map whenever the user manually enters a set of coordinates, i.e. _World_->_Go to Coordinate ..._

I noticed Issue [#549, "_Add support for bookmarked locations_"](#549 ) - this would be even better than my suggestion! The status of #549 gives me the impression that the bookmark feature has been implemented yet I can find no such capability in Amidst v4.4; has it been added?

**Comment by burgerguy** [comment]
It has not been added because the person working on the pull request has it marked as a draft, signifying that they are not done with it yet.
