### ISSUE TITLE
Installing Amidst on custom launchers

### ISSUE THREAD

**Issue by Thompe99** [toolbox4minecraft/amidst#710]
Hi, I'm using a custom Minecraft launcher (MultiMC), and I wonder if you can use command line interface to install Amidst?

**Comment by moulins** [comment]
There is an Amidst CLI, see [this wiki page](https://github.com/toolbox4minecraft/amidst/wiki/Command-Line-Interface). You can use it to specify the locations of various Minecraft files (options `-mcjar`, `-mcpath`, `-mcjson`). 

I don't know if MultiMC has paths compatible with these options, but if it's the case, Amidst should work correctly. (Note that Amidst still required an un-modded JAR to work with)

**Comment by Thompe99** [comment]
Yes, MultiMC has an unmodded .jar and .json file, but not a .minecraft folder, is it required? If so, what is it in that folder that is required?
