### ISSUE TITLE
[Feature] Improved PNG Map Export Functionality

### ISSUE THREAD

**Issue by p3iurhgmc98h** [toolbox4minecraft/amidst#713]
This may be a duplicate of #245, but I figured I could possibly make it more explicit.

The current export functionality takes a screenshot of current AMIDST screen area. This places an upper bound on the size of images that the exporter can produce, and means that zoomed-out exports have a lower resolution in terms of blocks-in-game.

Would it possible to alter the PNG export functionality to allow the user to specify:

- The rectangular coordinate area to map (either center-span or min-max for the _x_ and _z_ coordinates).

- (Optional) The resolution to export at, specified in the number of in-game-blocks per exported pixel.

- (Optional) Create a command-line argument to automatically take a screenshot (#711).

AFAIK, when AMIDST is first opened, the zoom level is such that one screenshotted pixel corresponds to four blocks in-game. Using autohotkey scripts, I've exported and stitched a large number of screenshots at this zoom level, and the results are quite spectacular compared to a native zoomed-out screenshot.

Finally, I would like to ask commenters **not** to turn this into a request for SVG export functionality (#327/#714). Although I am not opposed to this, the PNG format is probably better for storing the inherently rasterized data that AMIDST produces (with the exception of representing toggleable map-marker icons and grids). This is shown by the image below:

![SVGdemo2](https://user-images.githubusercontent.com/60664298/76433052-2aa03300-638a-11ea-87fb-f2d1c1dc2fe8.png)

Note that although the raster-upscaled _circle_ is significantly degraded compared to the vector-upscaled one, the _rectangle_ suffers no degradation since it lies on the "pixel-grid" to begin with. The output of AMIDST (world biome data) similarly lies on a grid, and therefore can be represented using a (lossless) raster image format without _any_ loss of information/quality.

As an aside, converting an SVG image into a _**pixel-accurate**_ raster image isn't a trivial process (Inkscape, for example, antialiases on export by default.)

**Comment by moulins** [comment]
I'll keep this issue and close the other one, as this feature request is more complete ;).
