### ISSUE TITLE
Snapshot 20w11a+ aren't supported

### ISSUE THREAD

**Issue by ShoddyMaintenance** [toolbox4minecraft/amidst#719]
![Annotation 2020-03-24 172938](https://user-images.githubusercontent.com/44716003/77478858-0fefa480-6df5-11ea-85da-e6d248d40f73.png)

Is 20w12a not supported yet or is it something else?

**Comment by moulins** [comment]
This error means that the Minecraft code that Amidst uses has changed, and that Amidst needs to be updated.

P.S.: the 20w11a snapshot doesn't work either.

**Comment by GoodGuyJohn** [comment]
I literally came here to report that the program doesn't support versions newer than 20w10a. But w10a can be used as a overworld map, as this generation hasn't changed much, from what I can tell.

**Comment by EtlamGit** [comment]
Hi @moulins ,
could you please tell me what color you are planning to use for "Basalt Deltas" coming with 20w15a?

I'm developing Minecraft mapping tool Minutor and we are using the same colors than AMIDST for optional Biome overlay. Therefore I'm stuck with Biome update until AMIDST decides on the new color.

**Comment by moulins** [comment]
@EtlamGit You can see the default biome colors [here](https://github.com/toolbox4minecraft/amidst/blob/master/src/main/resources/amidst/mojangapi/default_biome_profile.json) (the wiki page isn't up-to-date yet).  
However, the colors currently used for the Nether biomes are only tentative; they may change once we add proper Nether support to Amidst.

**Comment by EtlamGit** [comment]
Ah, I was always looking into: https://github.com/toolbox4minecraft/amidst/blob/master/biome/test.json
And there Biome 173 is still missing. Thank you.

**Comment by moulins** [comment]
Fixed by #720.
