### ISSUE TITLE
No profile found in version 4.4

### ISSUE THREAD

**Issue by MatteGaliz** [toolbox4minecraft/amidst#721]
as the title says i can't find any profiles when i launch amidst even if there are multiple ones in the versions folder of .minecraft

**Comment by MatteGaliz** [comment]
none of the profiles are modded except for the optifine ones

**Comment by moulins** [comment]
Can you post the Amidst logs? (in **Help > Display Log Messages...**)

**Comment by MatteGaliz** [comment]
> Can you post the Amidst logs? (in **Help > Display Log Messages...**)

fixed by uninstalling Minecraft, deleting .minecraft folder, all temp folder and installing Minecraft again

**Comment by moulins** [comment]
Hum, weird ^^  
Closing this then.
