### ISSUE TITLE
Support for Minecraft Bedrock

### ISSUE THREAD

**Issue by lucandresenu** [toolbox4minecraft/amidst#725]
Give support to MC Bedrock's vanilla worlds please, it would be very useful for me and surely for many others.

**Comment by Delvin4519** [comment]
There is a temporary workaround you can use right now, you can use google and use the chunkbase biome finder and select bedrock limited.

**Comment by moulins** [comment]
Amidst only supports Minecraft Java Edition, as it uses the Minecraft JAR to generate the biome data.
There are no plans to support MCPE or any other Bedrock edition, as it would involve recoding the entire biome generator.

As @Delvin4519 said, your best bet is to use another tool.
