### ISSUE TITLE
Amidst immediately crashing on opening

### ISSUE THREAD

**Issue by Yamiash102** [toolbox4minecraft/amidst#728]
Out of the blue, Amidst has just not worked. I open the program, it shows up in Task Manager for half a second, then closes. Doesn't even appear as open to me. No idea what's going on, there's no crash report or anything that opens up, and as far as I'm aware, Amidst doesn't have a place to store crash logs.

Using version 4.4, have reinstalled several times now, .exe (which I've always used) doesn't work, nor does .jar. I relatively recently installed the Twitch launcher for use with a modpack, but I don't see why that would prevent Amidst from even opening. I paused my anti-virus as well, and tried opening with admin, both to no avail. I'm fresh out of ideas, and still just as confused. Any help would be appreciated. Thank you.

**Comment by moulins** [comment]
Can you open Amidst in the console (with `java -jar <amidst-file>.jar`) and copy here any errors that pop up?

**Comment by Yamiash102** [comment]
> Can you open Amidst in the console (with `java -jar <amidst-file>.jar`) and copy here any errors that pop up?

`Error: Unable to access jarfile amidst-v4-4.jar`

With file `amidst-v4-4.jar` in and outside Downloads folder, and with anti-virus on or paused. Thank you for adding labels by the way, I wasn't aware that was a thing on GitHub.

**Comment by moulins** [comment]
Make sure you are opening the terminal window in the same folder as the JAR file.

**Comment by Yamiash102** [comment]
Ah, yep, did the wrong thing the first time. My bad. Response is as follows:

`Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object`

**Comment by moulins** [comment]
No problem!
