### ISSUE TITLE
Feature request: Support for additional dimensions (added by mobs)

### ISSUE THREAD

**Issue by BowtiesAreCool** [toolbox4minecraft/amidst#732]
If possible, please consider adding support for other dimensions added to the game by mods such as Twilight Forest, The Aether, and Galacticraft. Allow the user to switch between these dimensions and the Overworld like they can with the End currently.

Even just showing biomes (without structures or other landmarks) would be incredibly useful.

**Comment by BRBosley** [comment]
That won't happen, it has been suggested by many, and they all get turned down. So, Always look for a suggestion before suggesting it, because if it has already been suggested and turned down, it will be turned down for you too. Hope this helps.
-BRB

Also, I am not the creator/owner of the mod, I have just seen this suggestion before.

**Comment by BowtiesAreCool** [comment]
> That won't happen, it has been suggested by many, and they all get turned down. So, Always look for a suggestion before suggesting it, because if it has already been suggested and turned down, it will be turned down for you too. Hope this helps.
> -BRB
> 
> Also, I am not the creator/owner of the mod, I have just seen this suggestion before.

I did search before posting but didn’t find any related requests. Perhaps you could point me to those tickets, please?

**Comment by BRBosley** [comment]
Well, from what I have seen, the Developers of Amidst will never add Support for Mods of any Kind. Every Single Feature Request involving mods get Closed. Here are some Examples:
> [In general, Amidst is not designed to support modded Minecraft versions.](https://github.com/toolbox4minecraft/amidst/wiki/Using-Amidst#why-can-i-not-use-amidst-with-a-modded-minecraft-version)
>[Modded versions are not officially supported by amidst.](https://github.com/toolbox4minecraft/amidst/issues/715#issuecomment-598299658)
>[I close this as invalid, because Amidst does not support modded Minecraft.](https://github.com/toolbox4minecraft/amidst/issues/160#issuecomment-213667508)

I would recommend if you want to use Amidst with mods, try using [Amidst for Forge](https://www.curseforge.com/minecraft/mc-mods/amidst-for-forge), which is an Unofficial Fork of Amidst for Viewing Modded Biomes in the Overworld. It doesn't support Modded Dimensions, but it is better than nothing.

**Comment by moulins** [comment]
As BRBosley said, Amidst doesn't aim to support mods; closing as invalid.
