### ISSUE TITLE
Biome search json not working

### ISSUE THREAD

**Issue by SekoiaTree** [toolbox4minecraft/amidst#734]
Currently #129 has a basic implementation. Having never worked with amidst, it took a while to figure out, but it _almost_ works now. However, even copy-pasting the example json into the input, or put search.json next to the jar does not work. It always gives the error "invalid configuration". I would like to develop this a bit more, and I'd like to get the basic thing working first.

**Comment by moulins** [comment]
Which error do you get exactly? Can you copypaste the stacktrace?

**Comment by SekoiaTree** [comment]
Dunno why, but it works now. The implementation is still missing some features/biomes, but no critical errors. I'll try and develop it a bit
