### ISSUE TITLE
Dark Forest Biome

### ISSUE THREAD

**Issue by tinkserbell** [toolbox4minecraft/amidst#740]
Hello, I could find anyone else asking about this so maybe I'm missing something obvious, but why can I not find dark forest biomes with amidst. I'd like to go looking for a mansion but cant figure out why dark forest is not included in the legend. There may be an obvious solution to this but I don't know what to do. Is there a reason dark forest is not included or is it under a different name?

**Comment by BigAlanM** [comment]
So far Amidst hasn't been updated to use the new names of the biomes.
Dark Forest is called Roofed Forest in earlier MC releases.  
You will find mansions in those.

**Comment by moulins** [comment]
As BigAlanM said, Amidst still uses the old biome names; a fix has been merged in `master` and will be included in the latest release.
