### ISSUE TITLE
Amidst does not use ram enough for very high resolution

### ISSUE THREAD

**Issue by aria1th** [toolbox4minecraft/amidst#744]
I disabled 'restrict maximum zoom' option, and zoomed out until 10,000 blocks. Then, it does not render anything else and just crashes. I have 32GB of ram but amidst only uses 2210MB of ram, which could be cause for this problem.

**Comment by moulins** [comment]
The `.exe` launcher restricts the maximum Java heap size to 2GB, to avoid inadvertently consuming too much memory and slowing the system to a crawl.

If you want to allocate more memory for Amidst, you'll need to download the JAR version [here](https://github.com/toolbox4minecraft/amidst/releases), and launch it manually from the command-line with the `-Xmx` argument:

```sh
# for example, to allocate 4GB of RAM
java -Xmx4G -jar amidst-v4-4.jar
```
