### ISSUE TITLE
exe can not find minecraft install

### ISSUE THREAD

**Issue by Jecder** [toolbox4minecraft/amidst#746]
Receiving Amidst is not able to find your '.minecraft' directory, but it requires a working mincraft installation." I do have Minecraft installed but it looks like it is in a different directory than what it is expecting. Have Minecraft for windows 10.

**Comment by moulins** [comment]
Amidst only supports Minecraft Java Edition. The Windows 10 edition is part of the Bedrock editions and isn't supported by Amidst.
