### ISSUE TITLE
Buried treasures incomplete 1.15.2

### ISSUE THREAD

**Issue by jnvsor** [toolbox4minecraft/amidst#749]
In a 1.15.2 default world with seed 2823674000408840702 there is a buried treasure at 57, 201 which does not appear in amidst.

It does appear on [chunkbase](https://www.chunkbase.com/apps/buried-treasure-finder#2823674000408840702) so the issue is with amidst.

Other buried treasures appear to be correct but I haven't checked them all of course.

**Comment by moulins** [comment]
Thanks for the report, I've added it to the master list at #117.
