### ISSUE TITLE
[Feature Request] Add Default Screenshot Save Location

### ISSUE THREAD

**Issue by Antyos** [toolbox4minecraft/amidst#751]
Currently, when you save a screenshot in Amidst, it defaults to opening the "Documents" folder. It would be really convenient to have an option to choose the default location for saving screenshots.

**Comment by moulins** [comment]
Would it be sufficient to sumply remember the latest opened folder?

**Comment by Antyos** [comment]
Yeah, I think that'd work!

**Comment by burgerguy** [comment]
gonna do this now

**Comment by moulins** [comment]
Fixed by 537c931c.
