### ISSUE TITLE
v4.4 Incorrect pillager outpost location

### ISSUE THREAD

**Issue by alexpearce92** [toolbox4minecraft/amidst#760]
Amidst v4.4 on Win10
Minecraft 1.15.2 (Java 1.8x64)
Seed -708672873581662816, Single Player (seed in Amidst matches seed in Minecraft's re-create world option)

Looks like some Pillager Outpost coords are still wrong:
- Pillager Outpost (-172, 36): there is no outpost, just a ravine
- Pillager Outpost (-1388, 596): outpost exists

**Comment by alexpearce92** [comment]
Note: seed displayed in Amidst matches seed in the re-create world option in Minecraft

**Comment by moulins** [comment]
This is an expected false positives, and can't really be fixed.

What happens is that the ravine is preventing the Outpost from being generated; however, Amidst doesn't generate the actual terrain (it would be too slow), doesn't see that a ravine is here, and reports that the Outpost is present.

These false positives can also be observed with villages, which won't generate if the terrain is too hilly.

**Comment by alexpearce92** [comment]
Makes sense. Thank you!
