### ISSUE TITLE
Error #2

### ISSUE THREAD

**Issue by Gergely9135** [toolbox4minecraft/amidst#763]
![Error](https://user-images.githubusercontent.com/33695813/82557857-c8736380-9b6c-11ea-9a82-139723c88d63.png)

**Comment by James103** [comment]
It's crashing because Minecraft 1.16 is currently not supported for Amidst. Try again with the next Amidst release or use Minecraft 1.15.2.

**Comment by Narzaum** [comment]
I have the same problem
