### ISSUE TITLE
Features, sort profile selector, disable anti-aliasing, labels

### ISSUE THREAD

**Issue by Delvin4519** [toolbox4minecraft/amidst#765]
It appears that when you have the profile selector, it sorts profiles based on the random string of numbers and letters in the launcher profiles json, instead of by name or version release date. This means if I have several versions in my launcher profiles, it is often out of sequential/alphabetical order in the profile selector.

Also for image exporting uses, is there a way to disable anti-aliasing or the labels in the grid? This is for image exporting so that way there would be solid colors and grid on the exported biome map image. This way exporting image is more useful.

Anti aliasing right now, number labels stuck on the grid. We have hover over coordinates already.

![image](https://user-images.githubusercontent.com/23464599/83644128-eda99e00-a57e-11ea-9483-7b72f94f0b6c.png)

Anti aliasing disabled, this allows easy useful image exporting
![image](https://user-images.githubusercontent.com/23464599/83644223-0d40c680-a57f-11ea-9cfa-6610b5011576.png)

**Comment by moulins** [comment]
You can use the new "Export biomes" feature of Amidst v4.5-beta1 to export an image containing only biome data.
