### ISSUE TITLE
Seed searching problems

### ISSUE THREAD

**Issue by Weimil** [toolbox4minecraft/amidst#767]
My name is Weimil

And I'm trying to use amidst to search a seed using the seed searcher but I can't make it run. I'm trying to find a very specific seed with these properties a quad witch hut, a mushroom field biome in the spawn surrounded by the ocean, at least 2 double witch huts "near" spawn and a double ocean temple if it is possible.

I write thissimple json file:
```
{
    "continuousSearch": true,

    "structureFilters": [

        {"distance": 2048, "structure": "Quad Witch Hut", "minimum": 1},
        {"distance": 16384, "structure": "Dual Witch Hut", "minium": 2, "score": 10},
        {"distance": 2048, "structure": "Ocean Monument", "minium": 2, "score": 1}
    ], 

    "biomeFilters": [

        {"distance": 512, "biomes": ["Mushroom Island", "Mushroom Island M"]},
        {"distance": 4096, "biomes": ["Mesa (Bryce)", "Mesa Plateau F M", "Mesa Plateau M", "Mesa Plateau"]}
    ]
}
```
But im not sure how can i run it, and [this](https://github.com/toolbox4minecraft/amidst/wiki/Command-Line-Interface) is not very helpful at least for me.

I try to run it with this command but it crash:
```
java -jar amidst-v4-4.jar -mcjson "config/config_001.json" -mcjar "/home/weimil/.minecraft/versions/1.15.2/1.15.2.jar"
```
[Crash report](https://paste.ofcode.org/vB34kChQ8xBk2cK6gzfJvu)

Thanks in advance and sorry for my inglish.

**Comment by Weimil** [comment]
Can someone help me?

**Comment by moulins** [comment]
The seed search feature is only half-implemented and cannot be used without modifying the code directly.

You should use a dedicated tool, for example [here](https://github.com/Zodsmar/SeedSearcherStandaloneTool).

**Comment by hjpoe** [comment]
@Weimil I don't know if you're still trying to do this, but I noticed that you seem to have spelled the word "minimum" wrong twice.
