### ISSUE TITLE
Blank screen when attempting to open any profile.

### ISSUE THREAD

**Issue by solonovamax** [toolbox4minecraft/amidst#771]
When trying to run amidst and selecting any of the profiles (excluding modded/etc.), it will display a blank screen with no UI. (see attached image)

I've run it with versions 1.8.9 (used a forge version of 1.8.9, but then jumped to underlying version), 1.12.2 (used optifine to get to underlying), 1.14.4 (same thing), and 1.15.2 (for this I used the actual *vanilla* 1.15.2 version). For all of those, it showed a blank screen with no UI.

I'm currently using an alternate .minecraft location with the `-mcpath` flag. (I wanted to use my multimc location and that didn't work, so I used a backup of my old .minecraft (I can't use the mc launcher because that is broken, but that's another issue altogether))

I've created a pastebin with the relevant logs here: https://pastebin.com/8UyLSnvk (I cut out the part about it not being able to find a valid version dir for xxx profile, because it's long and useless because none of those profiles are relevant.)

I have a bit of rambling in brackets, but I'm leaving it there since it adds context to some of the things. Also, sorry for the bad formatting; I'm tired. If you need any more info, feel free to let me know and I'll be happy to provide.

![image](https://user-images.githubusercontent.com/46940694/84967082-1aae9280-b0e1-11ea-98ae-9a96f8a713e4.png)

**Comment by burgerguy** [comment]
Is there any sort of menu bar that shows up anywhere? Usually, you would create a world from there under the File menu.

**Comment by moulins** [comment]
There should be a menu at the top of the window for creating a new world. Does `Ctrl+R` does anything? (It should create a new world with a random seed).

**Comment by solonovamax** [comment]
Sorry, I missed your messages since github decided not to notify me. No, there was no menu bar.

`ctrl` + `r` allows me to (I assume) randomly generate a seed and view the world for that seed, but I cannot find any way to view a set seed. Only I run `ctrl` + `r`, I'm also able to see "World" and "Layers" on the menu bar, but nothing else. Upon clicking on one of the two, the rest of the menu bar shows. ("File", "World", "Layers", Settings", and "Help") Once I do this, I'm able to generate a new world from a seed.

Also, because I felt I might know what the issue was, I tested it with java 11 instead of my default of java 8. It seems that with java 11, it worked perfectly fine but when I use java 8 these issues appear. Is there official support for java 8, or no?

Pictures:
`ctrl` + `r`:
![image](https://user-images.githubusercontent.com/46940694/85869834-3c231480-b79a-11ea-8f28-07b08b0de448.png)
Non-populated menu bar:
![image](https://user-images.githubusercontent.com/46940694/85869902-56f58900-b79a-11ea-9838-7a2680636c80.png)

**Comment by hjpoe** [comment]
ctrl + n should allow you to create a new world from a seed.

**Comment by solonovamax** [comment]
I jsut checked, `ctrl` + `n` does allow me to create a new world, although it is still a workaround from using the UI.

**Comment by moulins** [comment]
Java 8 should definitely be supported.

Can you post the full Amidst log ? (You can get it in **Help > Display Log Messages...**)
Also, maybe try changing the Look & Feel in the **Settings** menu.

**Comment by solonovamax** [comment]
[Here](https://pastebin.com/rsAqA7x0) is a log of me running amidst, then selecting an profile with the version `1.15.2`, then exiting because there is no UI.
[Here](https://pastebin.com/YQQyzrVN) is a full log of me first opening it, selecting the profile with the version `1.15.2` using `ctrl` + `n` to create a new world (there was no UI), changing the look & feel to system instead of default, amidst restarting, then creating a new world with `ctrl` + `n` (there was still no UI.), and finally exiting.
(These logs are complete, as I just piped the content to a file and then copied that into pastebin.) 

The logs I gave before were just full logs, with this garbage cut out.
```
[warning] java.io.FileNotFoundException: cannot find valid profile directory for launcher profile 'PvP - LiteLoader + Forge 1.8.9': /home/solonovamax/.minecraft.1.8.9/
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidProfileDirectory(DotMinecraftDirectoryService.java:107)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:49)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Also, changing the look and feel did not do anything, as it seems java doesn't follow my gtk or qt themes.

**Comment by solonovamax** [comment]
It seems that the issue is the same thing as #704 and you have tagged that as "wont fix". Should I close this issue?

**Comment by moulins** [comment]
You're right, I'll close this as duplicate.

Does the solution in [this comment](https://github.com/toolbox4minecraft/amidst/issues/704#issuecomment-599014959) fixes the issue?
