### ISSUE TITLE
Error opening world: NBT TAG_LongArray not supported

### ISSUE THREAD

**Issue by PKMWM1** [toolbox4minecraft/amidst#777]
I updated to the newest version of AMIDST, which is v4.5beta1, and am trying to load my world, but I am still getting an error. 
![AMIDST Error Pic](https://user-images.githubusercontent.com/20786416/85790695-e5f89780-b6ed-11ea-8c05-521a8a2dd5aa.png)
Just to clarify, I am trying to open a world from 1.16.1 in AMIDST version 4.5 Beta 1, which is supposed to add support

**Comment by moulins** [comment]
Ouch, this is annoying :/

Basically, the library we use to read the `level.dat` file (JNBT) is old and unmaintained, and doesn't support the Long Array NBT tags (which were added in Minecraft 1.12, but weren't present in the `level.dat` file until now). You should still be able to open your world by manually entering the seed.

------

We have 3 solutions to fix this (in decreasing order of preference):
- find a new properly-maintained NBT library and port our code to it
- patch JNBT ourselves to add TAG_LongArray support
- reimplement NBT parsing ourselves

I'll have to look into this ;)
