### ISSUE TITLE
Incorrect locations for strongholds that are further away in a 20w21a+ world

### ISSUE THREAD

**Issue by TheRealWormbo** [toolbox4minecraft/amidst#785]
Amidst: 4.5-beta1
Minecraft: 1.16.1

Using world seed 14916203336864 (entered manually, since loading world save file does not work), Amidst generates a stronghold icon at -9952, -4368:
![Amidst stronghold location](https://user-images.githubusercontent.com/7620864/85923024-f5134d00-b887-11ea-82c6-801007b30c98.png)
This stronghold location displayed by Amidst is the same for 1.15.2 and 1.16.1 profiles.

When creating a world with the same seed in Minecraft 1.16.1, that location has no stronghold. Instead, it is at -10296, -4584 – about 400 blocks away:
![Minecraft stronghold location](https://user-images.githubusercontent.com/7620864/85923049-183dfc80-b888-11ea-90de-11efb848e2c2.jpg)
When creating the world in Minecraft 1.15.2 instead, that stronghold location is correct.

I tested a couple of other strongholds on that seed, and coordinates of strongholds from the inner three rings seem to match, while coordinates for all tested strongholds from the fourth ring and beyond were off by a significant amount in the world generated in 1.16.1.

**Comment by moulins** [comment]
Thanks for the report!

**Comment by moulins** [comment]
After bisection, I found that the stronghold first changed place in Minecraft 20w21a.

**Comment by taurose** [comment]
They removed bamboo jungles from valid biomes list, since the code now relies on OverworldBiomes.POSSIBLE_BIOMES which misses those biomes. So the valid biomes should be the same again as in 1.13.

I tried to report this in https://bugs.mojang.com/browse/MC-188821 but it got a bit off-track :)

**Comment by moulins** [comment]
Thanks for finding the root cause!  
I've just made a fix for Amidst and reported https://bugs.mojang.com/browse/MC-199298 (with the offending stronghold) to track a potential fix.
