### ISSUE TITLE
Support for Beta 1.7 and earlier

### ISSUE THREAD

**Issue by FakenameBill** [toolbox4minecraft/amidst#786]
I'm planning to make a video about the history and development of Minecraft's biome system, and I would really like to be able to use an AMIDST-style visualization of the old biomes from before Beta 1.8. Several years ago I remember asking about this on the old Minecraft Forums thread. Whoever was in charge of development at the time said that they had worked on a prototype for this, but that it stopped working at Beta 1.6 and needed to temporarily load actual chunks to find the locations of oceans and lakes. Unfortunately I haven't been able to find this thread, but I did save a screenshot posted by the developer at the time (using Beta 1.3):
![Amidst Zoom B1 3](https://user-images.githubusercontent.com/10792864/85936230-77bafd00-b8c6-11ea-90d7-968c9c96ca86.png)
If this request is deemed out-of-scope, then if the current developers still have access to this prototype build with support for Beta 1.3, I would really appreciate getting access to it.

I'm no expert on how exactly Minecraft generates terrain, but as far as I understand, these old biomes were determined by the intersections of two Perlin noise generators, which is the same way terrain height was determined. In that case, couldn't the height map be used to determine which parts of the map are underwater without loading the chunks? Just a thought.

**Comment by moulins** [comment]
You can find the pre-b1.8 prototype on the [support_early_betas](https://github.com/toolbox4minecraft/amidst/tree/support_early_betas) branch. It's pretty outdated compared to the current Amidst version, but it should still be working. (see #374)

I'm not knowledgable enough about Beta terrain generation, so I can't tell you if chunk data is necessary or not for determining terrain height. I won't have to time to look into it, but I would gladly accept a PR adding support with acceptable speed!
