### ISSUE TITLE
Não é possível abrir level.dat na 1.16.1 (não testei 1.16)

### ISSUE THREAD

**Issue by GabrielOsvair** [toolbox4minecraft/amidst#787]
![Sem título](https://user-images.githubusercontent.com/67530921/85937714-3d585c80-b8d4-11ea-883c-36eb3c3fe246.jpg)

**Comment by GabrielOsvair** [comment]
Utilizando windows 10 x64 e java 8 atualizado.

**Comment by BlaCoiso** [comment]
Looks like jnbt doesn't support TAG_Long_Array, these are used to store block states

**Comment by GabrielOsvair** [comment]
Eu posso corrigir ou só em uma nova atualização?

**Comment by moulins** [comment]
Closing as duplicate of #777.
