### ISSUE TITLE
Still cannot load 1.16.1 worlds in latest branch

### ISSUE THREAD

**Issue by ZeroHanekoma** [toolbox4minecraft/amidst#792]
![wCZCbY8mIk](https://user-images.githubusercontent.com/67618133/86077805-8843b280-ba41-11ea-93df-cf016b4c6120.png)

This is keeping me from cheating super hard in Hardcore Survival, I appreciate it but I assume something is wrong.

Using latest branch, 4-5 Beta 1.  Still getting same error as the previous version.  Are there temporary files or something I should delete?

**Comment by moulins** [comment]
Amidst only works with vanilla profiles made with the official Minecraft Launcher.

**Comment by ZeroHanekoma** [comment]
This is attempting to launch with vanilla 1.16 but OK.
Sigma5 is for version 1.15.2, which actually loads in Amidst because it defaults to the vanilla Jar.

**Comment by ZeroHanekoma** [comment]
> 
> 
> Amidst only works with vanilla profiles made with the official Minecraft Launcher.

This is attempting to launch with vanilla 1.16 but OK.
Sigma5 is for version 1.15.2, which actually loads in Amidst because it defaults to the vanilla Jar.
