### ISSUE TITLE
Piglin bastions and nether fortresses

### ISSUE THREAD

**Issue by machinesmith42** [toolbox4minecraft/amidst#794]
Since the spawning logic of the nether fortress has changed to be biome dependent does amidst reflect this?
Also have bastions been added

**Comment by moulins** [comment]
For now, Bastions and Fortresses both show as Nether Fortresses in Amidst.

Making the distinction between the two requires adding support for Nether biomes, so there's some work to do!

**Comment by machinesmith42** [comment]
I saw nether biome colors in amidst

**Comment by Shepard** [comment]
I think they also made Nether Fortresses rarer in one of the snapshots so I guess this needs adjusting anyway.

**Comment by machinesmith42** [comment]
Has anything changed?

**Comment by burgerguy** [comment]
@machinesmith42 See my response on #692. TLDR, this will happen eventually.
