### ISSUE TITLE
A bug in Amidst 4.0 or in PCMCv1.9????

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#80]
I'm been recommending Amidst to people on the Minecraft forums for years.
I just received this PM from a member there.
I haven't, as yet, tried it myself but figured I should give those here a heads up.
Here's the PM:
******************************************
Seed 6705423713563488490
I saw this a few days back and was interested.

http://www.minecraftforum.net/forums/minecraft-discussion/seeds/2615190-6705423713563488490-if-you-cant-survive-on-this?comment=2
I used MoreCommands /setspawn to move my spawn south and a little west (-500//1964). I was hoping for a mix of jungle and desert temples (didn't happen).
When I reopened the modified seed with amidst and found it most interesting that strongholds moved too.
Were you aware of this?
Just a gee whiz...
Lou
*********************************************
Is it possible that there is a bug in MC1.9 that causes the stronghold locations to change when spawn is moved?

EDIT:  As usual I may have jumped the gun on this.  It's quite possible that the user isn't aware that 1.9 has more strongholds and that the first ring is farther away and he used two different profiles by accident.  I replied to his PM asking if this might be the case.

**Comment by BigAlanM** [comment]
Turned out to be cockpit error.
ie: User shoot himself in the foot.

**Comment by stefandollase** [comment]
Good thing this resolved itself :-P
