### ISSUE TITLE
[4.5 beta 3] Opening the Highlight Biomes pane while using an old biome profile that is missing the new Nether biomes causes error message spam and an eventual crash

### ISSUE THREAD

**Issue by JuniorJedi490** [toolbox4minecraft/amidst#806]
Opening the highlight biomes pane (in the lower right-hand corner) with a 1.16.1 Minecraft profile while using a biome profile from 4.4 causes a large amount of error messages to pop up, potentially crashing the PC.
The error messages begin with: amidst.mojangapi.world.biome.UnknownBiomeIdException: unsupported biome index detected: 170/171/172/173, take up the full height of my screen, and don't seem to stop being generated.
I got a crash report too, but because of the sheer volume of error messages I couldn't select the window bearing the crash report and am therefore unable too paste it here.
Killing the process using the Task Manager caused the crash report window to close too.
Attached is the biome profile causing the issue. It's in a zipped folder because GitHub supposedly doesn't support the .json file type.
[surface_colors.zip](https://github.com/toolbox4minecraft/amidst/files/4880708/surface_colors.zip)

The biome profile was automatically modifed from what it looked like in 4.4, and is missing lines for biomes with IDs from 170-173. Manually adding colours for biome IDs 170-173 fixes the issue.

**Comment by moulins** [comment]
I've fixed the code, so that instead of having a new error message displayed for each missing biome each frame, you only get the messages once.

I'm not sure automatically using default values in biomes profiles is a good idea, so I'll leave the error messages for now.
