### ISSUE TITLE
Biome map resolution lower than actual world map even when full resolution is selected

### ISSUE THREAD

**Issue by nsluhrs** [toolbox4minecraft/amidst#808]
Hello,

The blocks on the biome map seem to be much larger than the actual biome granularity. I exported the biome map from VoxelMap and that has block level granularity where as amidst seems to have 4x4? block level granularity. Maybe this is really a feature request but I didn't see any mention of the biome map being low resolution. 
What I expected to happen was seeing the full granularity when I selected full resolution, what I actually saw was 

I have created an overlay of the VoxelMap export and the corresponding amidst biome map export. 
With the overlay
![biome_map_overlay](https://user-images.githubusercontent.com/12732512/87046200-d76aaf80-c1c6-11ea-8635-0a499b89722e.png)
Without overlay
![biome_map_no_overlay](https://user-images.githubusercontent.com/12732512/87046209-dafe3680-c1c6-11ea-8599-f52798cf56f1.png)
I am running on windows, with minecraft 1.16.1 using amidst v4.5 beta3, java version "9.0.4", though this seems to be present regardless of minecraft/amidst version. 
the seed I am using is -676194426 and the area in question is just north of 0,0 
The error can be reproduced simply by exporting the map at full resolution. the VoxelMap can be produced by using that mods map export feature while in biome display mode.

**Comment by James103** [comment]
Minecraft only stores biomes for a given chunk at a resolution of 4 blocks per data point in each dimension (X, Y, and Z). Amidst currently does not do any post-processing on the biome map to upscale it, but VoxelMap does. This is why you get the 4 blocks per biome data point resolution in Amidst, compared to block-by-block granularity in VoxelMap.

**Comment by moulins** [comment]
As @James103 said, Amidst doesn't upscale the Minecraft biome map, mainly for performance reasons.

If you do need full biome resolution, you can use the **World > Export Biomes to Image** feature to create a PNG file (check the "Full resolution" checkbox).

**Comment by burgerguy** [comment]
This shouldn't have been closed so early. I just tested it (with full resolution checked) and it's still outputting at quarter resolution. I'm looking into it now to see what the issue is, and I'll be making a PR.
