### ISSUE TITLE
User reports "white screen" with v4.0

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#81]
From: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262200-v3-7-amidst-strongholds-village-biome-etc-finder?page=254#c5119
****************************
Hrmm, I'm stumped! The "new" version of Amidst - the beta 8 version of 4.0 won't work for me at all. I'm on PC, and have tried with several different versions of minecraft - 1.8.8 1.8.9 1.0 pre1 and some snapshots from 2014. I get the profile selection screen, hit whichever profile I want to test, and then it just opens a white screen with no menus or anything, just the white window. No error messages or anything, just a white screen showing me how dirty my monitor is =P

Tried with what I think is the "old" amidst (amidst exporter) and that one opens up normally and can be used.

Anyone have any ideas what's going wrong?

*edits* I did try both the .exe and the .jar just in case it made a difference somehow!
****************************
I don't have anything constructive to tell him.
Old version of JAVA?

**Comment by Treer** [comment]
Yup, I have the same issue on my PC at work: AmidstExporter works, Amidst4 is just a white window.

Googling around it sounded like an old version of Java, but my Java was up to date when I first noticed it, and I've just updated Java now to double check - no change.

My money is on this being a video acceleration issue. My work PC has a cheap video card and whatever drivers Windows 10 saw fit to use. 

I never figured out [why AmidstExporter was accelerated on a virtual machine at home, but not Amidst4](https://github.com/toolbox4minecraft/amidst/issues/43#issuecomment-174761525), but these issues are probably related.

**Comment by Treer** [comment]
OK, definitely looking like a driver bug - if I drag the window across to the second monitor as soon as it appears, the content of the window appears.

**Comment by BigAlanM** [comment]
The user updated his video driver and that didn't help.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262200-v3-7-amidst-strongholds-village-biome-etc-finder?page=254#c5121

**Comment by Talyda** [comment]
Hiya!  I'm the one having the problem (and it's she, not he BTW - but I'm used to the assumption after being a gamer for many many years =P)  If there's any other info I can give to help work it out, just yell.  Been using Amidst for a long time, but the "old" one (Skidoodle's), not this new one. I may actually go use my husband's PC while he's at work today just so I can see what this one is like - and find the right seed for what I am wanting to do! =)

PC is running Win7 64 bit, and the graphic card is a Sapphire Radeon HD7870 2GB - Java and graphic drivers both up to date.

Thanks for looking into it!

**Comment by stefandollase** [comment]
Thanks for reporting this. As @Treer already said, we already noticed issues with the drawing, but we did not have that much information. I just took the time and installed my windows machine to investigate the issue.

While I did not get the white screen bug, I think I found a fix for #43. It might also be a fix for this issue, however I will wait for @Treer 's response in #43.

**Comment by stefandollase** [comment]
@Talyda Can you try the new release Amidst v4.0-beta9 and tell us whether the issue still exists?

Also, do you have multiple monitors? If yes, did you try to drag the window to the other monitor?

Also, it would be useful to have more debug information. Can you tell us your Acceleration percentage? To find it follow these steps:

* load any profile
* generate a random world
* in the menubar click `Settings` > `Show Debug Information`
* you will find the value in the bottom right of the window with the title **Acceleration**

**Comment by Talyda** [comment]
I wrote in that other thread - sorry if it was the wrong spot. I only have the one monitor. Can't get to the debug info cos I cant see it - is there anyway to get the debug info to show in the dos-type window that opens at the same time as the beta9?

**Comment by stefandollase** [comment]
Thanks for the additional information. Of course you are right: You cannot see the Acceleration value :-P Currently, there is no way to print the value to the logging output, which is the dos-box. Also, thanks for mentioning the dos-box. It is not supposed to show up. I will remove it in the next release.

Don't worry about posting to other issues. It is all fine. We are happy about every piece of information that helps us fixing bugs. The information you provided is indeed helpful.

Nevertheless, I will quote your post here and remove it over there, since the issues indeed seem to be two different issues.

Quoting @Talyda from #43:

>I'm not sure where I should write this - so forgive me please if this is the wrong spot! 

>I downloaded the beta 9 as well, and still the same problem, but there is a difference between beta 8 & beta 9 - in beta 8 I can use Ctrl+N & Ctrl+R to create a map, and Ctrl+C to copy the seed - I just can't see any of it. 

>I tried also using Alt to open the menu (Alt+H for example to open the help menu) just to see if they worked, in Beta 8 I get an error ding as soon as I hit the letter - as if the menu bar just isn't there for me to open at all. But in Beta 9 I can open the menu - Alt+H down arrow twice and I get the "about" box pop up - all of which is still white.  Not sure if that is useful info for you at all, but chucking it in here in case it is! =)

**Comment by Talyda** [comment]
Don't know why I didn't think of this before, but reading Treer's comments on the other thread got me thinking, so I disabled my graphic card, let windows just use its default drivers for screen display, and now it works - so seems like definitely a problem with the graphic card/drivers?  

With windows using its generic drivers my acceleration is 0%  I re-enabled the graphic card while amidst was still open, and it's displaying fine - I can load new maps, zoom in and out, scrolll around a bit, and they show up ok (acceleration still at 0%) but as soon as I close amidst and open it up again, I'm back to all white.

Tried it a few times to make sure it wasn't a fluke!  At least I can use it now, even if it's a little fiddly to do so! =P  More than happy to keep testing and trying other things if you want me to to see if you can get a fix =)

**Comment by Talyda** [comment]
Thank you guys very much!  Beta 10 fixed my white screen =)

**Comment by stefandollase** [comment]
Wow, this was quick. I did not even finish writing the release notes :-D

Thanks for the feedback, I just wanted to ask you, whether it is fixed. Thanks for your patience and all the information.

**Comment by Treer** [comment]
Beta 10 fixed the white-screen on my work PC as well.
