### ISSUE TITLE
Amidst freezes when I zoom out

### ISSUE THREAD

**Issue by TypicalHog** [toolbox4minecraft/amidst#810]
I have 32 GB of RAM. Every time I zoom out past a certain point it just gives up. It's not even using 2 GB of RAM.

**Comment by moulins** [comment]
Java won't use more than 2GB by default; you need to increase the default heap size by launching the JAR from the command-line:
```shell
java -jar amidst-v4-5-beta3.jar -Xmx8G # for 8GB of RAM
```
