### ISSUE TITLE
Amidst crashed zooming out (ubuntu xenial 64)

### ISSUE THREAD

**Issue by reynaldo666** [toolbox4minecraft/amidst#815]
The GUI asked me to report this bug. I was zooming out and it crashed.
Message:

[info] Amidst v4.5-beta3
[info] Current system time: 2020-07-14 19:35:16.107
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.4.0-185-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '11.0.7'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: '/home/reynaldo/.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] using minecraft launcher profile 'Latest version' with versionId '1.16.1'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/home/reynaldo/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/home/reynaldo/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/home/reynaldo/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/home/reynaldo/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j:66.1 at file:/home/reynaldo/.minecraft/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
[info] Found library com.mojang:javabridge:1.0.22 at file:/home/reynaldo/.minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/home/reynaldo/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/home/reynaldo/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/home/reynaldo/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/home/reynaldo/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/home/reynaldo/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/home/reynaldo/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/home/reynaldo/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/home/reynaldo/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.17 at file:/home/reynaldo/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
[info] Found library com.mojang:datafixerupper:3.0.25 at file:/home/reynaldo/.minecraft/libraries/com/mojang/datafixerupper/3.0.25/datafixerupper-3.0.25.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/home/reynaldo/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.6.25 at file:/home/reynaldo/.minecraft/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/home/reynaldo/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/home/reynaldo/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/home/reynaldo/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/home/reynaldo/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/home/reynaldo/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/home/reynaldo/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/home/reynaldo/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/home/reynaldo/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/home/reynaldo/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/home/reynaldo/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Recognised Minecraft Version 1.16 with the magic string "bqedae$adaianoamczutlgm$aabp[Jablaaruxczyvauuadsuwcva".
[info] Reading 1.16.1.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class Util: v
[info] Found class WorldGenSettings: cix
[info] Found class ResourceKey: ug
[info] Found class Biome: bre
[info] Found class NoiseBiomeProvider: brg$a
[info] Found class OverworldBiomeZoomer: btf
[info] Found class Registry: gl
[info] Class search complete.
[info] Loading classes...
[info] unable to find the real class constructor ug.<init>(java.lang.String) -> ResourceKey.<init>
[info] Classes loaded.
[info] Minecraft load complete.
[info] Creating world with seed '923989580270532329' and type 'Default'
[info] Using the following generator options: 
[info] Not writing to seed history file, because it does not exist: history.txt
[info] loading player locations
[info] using player from level.dat
[warning] Unsupported dimension name: "minecraft:overworld". Falling back to Overworld.
[info] increasing fragment cache size from 0 to 1024
[info] fragment cache size increased to 1024
[info] increasing fragment cache size from 1024 to 2048
[info] fragment cache size increased to 2048
[info] increasing fragment cache size from 2048 to 3072
[info] fragment cache size increased to 3072
[info] increasing fragment cache size from 3072 to 4096
[info] fragment cache size increased to 4096
[info] increasing fragment cache size from 4096 to 5120
[info] fragment cache size increased to 5120
[info] increasing fragment cache size from 5120 to 6144
[info] fragment cache size increased to 6144
[info] increasing fragment cache size from 6144 to 7168
[info] fragment cache size increased to 7168
[info] increasing fragment cache size from 7168 to 8192
[info] fragment cache size increased to 8192
[info] increasing fragment cache size from 8192 to 9216
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at amidst.fragment.constructor.ImageConstructor.createBufferedImage(ImageConstructor.java:30)
	at amidst.fragment.constructor.ImageConstructor.construct(ImageConstructor.java:25)
	at amidst.fragment.FragmentCache.construct(FragmentCache.java:60)
	at amidst.fragment.FragmentCache.requestNewFragments(FragmentCache.java:50)
	at amidst.fragment.FragmentCache.increaseSize(FragmentCache.java:42)
	at amidst.fragment.FragmentManager.requestFragment(FragmentManager.java:30)
	at amidst.fragment.FragmentGraphItem.createFragmentGraphItem(FragmentGraphItem.java:381)
	at amidst.fragment.FragmentGraphItem.createBelow(FragmentGraphItem.java:366)
	at amidst.fragment.FragmentGraphItem.createFirstColumn(FragmentGraphItem.java:194)
	at amidst.fragment.FragmentGraphItem.createOrRemoveColumnsLeft(FragmentGraphItem.java:141)
	at amidst.fragment.FragmentGraphItem.adjustRowsAndColumns(FragmentGraphItem.java:102)
	at amidst.fragment.FragmentGraph.lambda$adjust$0(FragmentGraph.java:51)
	at amidst.fragment.FragmentGraph$$Lambda$2332/0x00000001009c9040.apply(Unknown Source)
	at amidst.util.Lazy.replaceWithValue(Lazy.java:43)
	at amidst.fragment.FragmentGraph.adjust(FragmentGraph.java:51)
	at amidst.gui.main.viewer.FragmentGraphToScreenTranslator.adjustNumberOfRowsAndColumns(FragmentGraphToScreenTranslator.java:57)
	at amidst.gui.main.viewer.FragmentGraphToScreenTranslator.update(FragmentGraphToScreenTranslator.java:36)
	at amidst.gui.main.viewer.Drawer.updateTranslator(Drawer.java:153)
	at amidst.gui.main.viewer.Drawer.draw(Drawer.java:126)
	at amidst.gui.main.viewer.Viewer$ViewerComponent.paintComponent(Viewer.java:33)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)

**Comment by moulins** [comment]
The Amidst process ran out of memory; try again after increasing the maximum Java heap size.
