### ISSUE TITLE
Amidst not recognising later Minecraft versions

### ISSUE THREAD

**Issue by subLime1248** [toolbox4minecraft/amidst#818]
After downloading v4.5 beta 3, Amidst is only recognising versions up to 1.14.4 and snapshot 20w06a, as though I am using an earlier version. The 'latest version' and 'latest snapshot' profiles display as the versions previously mentioned and any profiles on later versions show as 'not found'. I have tried reinstalling and this happened when using both the jar and exe, as well as the other 2 beta versions of v4.5.
This does not seem to affect the overworld or end, but nether fortress coordinates are way off.

**Comment by moulins** [comment]
This was fixed in the latest release, so I'll close this issue.
