### ISSUE TITLE
Regenerating world removes highlights

### ISSUE THREAD

**Issue by tecc** [toolbox4minecraft/amidst#832]
The title says it all, mostly.
When I regenerate a world (more specifically, random world) the highlights I've set are cleared.
I'd rather have them kept.

**Comment by burgerguy** [comment]
Fixed in #830, just hasn't been pulled yet.

**Comment by tecc** [comment]
Aha.
That's good.

**Comment by moulins** [comment]
Duplicate of #824, closing.
