### ISSUE TITLE
Can't create a Biome Profile

### ISSUE THREAD

**Issue by KarlosWGeek** [toolbox4minecraft/amidst#834]
No matter where I create a _"biome"_ or _"biomes"_ folder, there are no options to _"Switch Profile..."_
I tried creating on the .minecraft folder, on the mods folder where **amidst-forge-1.12.2-0.6.2.jar** was located, on the 1.12.2 folder where **amidst-4.3-beta2-all.jar** was located, and nothing works.

I'm playing on a large modpack (230 mods), and I use **amidst** to find specific biomes that are too far away for mods like _Nature's Compass_ to work with, and are hard to find by just walking. On the modpack there's Realistic Terrain Generator, Biomes o' Plenty and Climate Control/Geographicraft, so I mainly use "Amidst Overworld" rather than "Launch Amidst".

**Comment by moulins** [comment]
We aren't affiliated with amidst-forge, which is maintained by fraenkelc here: https://github.com/fraenkelc/amidst-forge.  
You should open an issue here instead.
