### ISSUE TITLE
I can't use AMIDST for 1.16.1

### ISSUE THREAD

**Issue by SMHerobrine** [toolbox4minecraft/amidst#837]
If I select a 1.16.1 profile then it shows this image: https://sm-master-wikis-beta.fandom.com/wiki/File:Error_03.08.2020_17_06_23.png

But other versions like 1.15.2 and below work.

BTW I don't have Optifine Installed.

**Comment by BigAlanM** [comment]
Amidst V4.5-beta3 works quite well with Release 1.16.1.
Download it from https://github.com/toolbox4minecraft/amidst/releases

**Comment by SMHerobrine** [comment]
Ok thanks
