### ISSUE TITLE
I don't know what to do, please help me!

### ISSUE THREAD

**Issue by Mateusz7073** [toolbox4minecraft/amidst#840]
Im using TLauncher for playing Minecraft, and recently I have created a modpack for minecraft version 1.12.2. It includes Climate Control/Geographicraft, and to make sure that I have generated worlds properly as I wanted I really need to use Amidst. But for some unknown to me reasons it cant find needed profiles. Can someone guide me what should I do, or what Im doing wrong?
![1](https://user-images.githubusercontent.com/64229729/89540208-06436800-d7fd-11ea-8e30-312bccbd7251.png)
![2](https://user-images.githubusercontent.com/64229729/89540216-08a5c200-d7fd-11ea-9a12-84534fe7fcff.png)

**Comment by moulins** [comment]
Amidst doesn't really support custom launchers. You can sometimes get them to work by providing the correct command line parameters (see [here](https://github.com/toolbox4minecraft/amidst/wiki/Command-Line-Interface)), but there is no guarantees.

The easiest way is to use have the vanilla launcher ^^
