### ISSUE TITLE
pillager outpost not correct in 1.16

### ISSUE THREAD

**Issue by OhnkytaBlabdey** [toolbox4minecraft/amidst#841]
I'm using amidst v4.5-beta3
my server version is 1.16.1 it also used fabric
seed is `-5001852661533124467`
amidst said that at coord [164,-684] there is a pillager outpost, but in game there is no such structure nearby.

**Comment by burgerguy** [comment]
This is due to some changes with how pillager outposts detect villages in 1.16. I’m working on some major structure changes and this will be fixed when that gets finished and merged.
