### ISSUE TITLE
Amidst 4.5 beta 3 doesn't work with minecraft 1.16.2 - when can we expect a NEW update to include this version?

### ISSUE THREAD

**Issue by mgt62** [toolbox4minecraft/amidst#844]

**Comment by burgerguy** [comment]
I'll work on a PR now, but I'm not sure when it will be accepted or when the next release comes out. I'm gonna guess that it'll be in a week, but take it with a grain of salt.

**Comment by mgt62** [comment]
Thank you! It’s a great tool for minecraft!

**Comment by moulins** [comment]
Fixed in f644cd9, closing.

Regarding the release date, I'll probably release Amidst v4.5 this week-end, barring any unexpected surprises ;).

**Comment by mgt62** [comment]
Hi!
 
Any plans to update the BEST Minecraft app out there? I’m using Minecraft 1.19.2 and unfortunately it doesn’t work with the current version (Amidst version 4.7) I have of Amidst. 
 
Please…
 
Thanks, Mike
