### ISSUE TITLE
Issues with amidst on all versions, not able to run it. 

### ISSUE THREAD

**Issue by nise7en** [toolbox4minecraft/amidst#851]
Can anyone tell me what I am doing wrong here?
![Screen Shot 2020-08-15 at 10 39 20 AM](https://user-images.githubusercontent.com/69725799/90315826-21406700-dee4-11ea-8034-2eddd0ed4e17.png)

**Comment by JuniorJedi490** [comment]
Duplicate of issue #852 (Crash upon loading a 1.12.2 profile or snapshot)

**Comment by nise7en** [comment]
Figured it out, played 1.16 with v4-5-beta3
