### ISSUE TITLE
Crash upon loading a 1.16.2 profile or snapshot

### ISSUE THREAD

**Issue by fonyo** [toolbox4minecraft/amidst#852]
![image](https://user-images.githubusercontent.com/10072275/90317285-291dfc80-df20-11ea-9e56-d3e96ffcad11.png)

**Comment by JuniorJedi490** [comment]
Try creating a Minecraft profile that uses the 1.16.1 version, for now?

**Comment by moulins** [comment]
Duplicate of #844, closing.
