### ISSUE TITLE
Amidst crashed with optifine 

### ISSUE THREAD

**Issue by mahfy3w** [toolbox4minecraft/amidst#888]
I tried opening my 1.7.2 optifine profile and it crashed. Is it supposed to crash? If so, sorry for wasting your time. If it isn't, then there's a problem. Here's the crash log
`[info] Amidst v4.6
[info] Current system time: 2020-08-31 15:58:21.55
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_251'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
[info] using '.minecraft' directory at: 'C:\Users\mahfu\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Successfully loaded remote version list.
[info] using minecraft launcher profile 'OptiFine' with versionId '1.7.2-OptiFine_HD_U_F7'
[info] Loading libraries.
[info] There are no updates available.
[info] Found library optifine:OptiFine:1.7.2_HD_U_F7 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.7.2_HD_U_F7/OptiFine-1.7.2_HD_U_F7.jar
[info] Found library net.minecraft:launchwrapper:1.12 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
[info] Found library com.mojang:netty:1.6 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar
[info] Found library java3d:vecmath:1.3.1 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
[info] Found library net.sf.trove4j:trove4j:3.0.3 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library net.sf.jopt-simple:jopt-simple:4.5 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
[info] Found library com.paulscode:codecjorbis:20101023 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library com.paulscode:codecwav:20101023 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library com.paulscode:libraryjavasound:20101123 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library com.paulscode:librarylwjglopenal:20100824 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
[info] Found library com.paulscode:soundsystem:20120107 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library io.netty:netty-all:4.0.10.Final at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
[info] Found library com.google.guava:guava:15.0 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar
[info] Found library org.apache.commons:commons-lang3:3.1 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
[info] Found library commons-io:commons-io:2.4 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.google.code.gson:gson:2.2.4 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
[info] Found library com.mojang:authlib:1.3 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.3/authlib-1.3.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.0-beta9 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.0-beta9 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
[info] Found library org.lwjgl.lwjgl:lwjgl:2.9.0 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar
[info] Found library org.lwjgl.lwjgl:lwjgl_util:2.9.0 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar
[info] Found library org.lwjgl.lwjgl:lwjgl-platform:2.9.0 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-windows.jar
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20131017
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20131017
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl-platform:2.9.1-nightly-20131017
[info] Found library net.java.jinput:jinput-platform:2.0.5 at file:/C:/Users/mahfu/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
[info] Finished loading libraries.
[crash] Amidst has encounted an uncaught exception on the thread Thread[WorkerExecutor-3,1,main]
[crash] java.lang.SecurityException: class "ov"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:269)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:260)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:255)
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:33)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:26)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:22)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:142)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by moulins** [comment]
Amidst doesn't support Optifine, or modded profiles. Use a vanilla Minecraft profile instead.
