### ISSUE TITLE
Bitdefender markes v4.6 as malware and deletes it.

### ISSUE THREAD

**Issue by Uhilom** [toolbox4minecraft/amidst#892]
Tried add a picture of the problem but can't find a way to post it so this is what Bitdefender says:
"The file C:\Users\Benjamin\Downloads\amidst-v4-6.exe is infected with Gen:Suspicious.Cloud.2.WzZ@aiUWaupG and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean."

**Comment by ZachTheDev** [comment]
Can confirm.
Downloaded v4.6
From BD: `Detection ID: SuspiciousBehavior.9061958A604A5EB`

**Comment by BigAlanM** [comment]
I've been running Amidst v 4.6  since the day after it was released.
I've run it on several different vanilla MC profiles from 1.6.4 through 1.16.2 with no problems.
Norton, Kaspersky, and Windows Security all believe it to be safe.
I suspect Bitdefender is getting a false positive.

**Comment by Uhilom** [comment]
I would agree 

> I've been running Amidst v 4.6 since the day after it was released.
> I've run it on several different vanilla MC profiles from 1.6.4 through 1.16.2 with no problems.
> Norton, Kaspersky, and Windows Security all believe it to be safe.
> I suspect Bitdefender is getting a false positive.

I suspect it's a false positive as a system scan gave nothing but still gives problems with quarantine and reset files etc..

**Comment by Zitchas** [comment]
I might suggest uploading the file that triggered the warning to [https://www.virustotal.com/gui/](https://www.virustotal.com/gui/) just to get another opinion on it. Always a chance that your particular download got infected somehow.

**Comment by burgerguy** [comment]
If if makes you feel better, you can always build an EXE for yourself with the guide in the wiki [here](https://github.com/toolbox4minecraft/amidst/wiki/Building-from-Source-Code). VirusTotal doesn't detect it for me, but make sure to always download versions from the [releases](https://github.com/toolbox4minecraft/amidst/releases) page on GitHub, as it could have been injected with something unwanted by a different distributor.

**Comment by moulins** [comment]
This isn't something we can do anything about, so I'll close this issue.
