### ISSUE TITLE
Exporting structures cordinates

### ISSUE THREAD

**Issue by milutinke** [toolbox4minecraft/amidst#898]
Hi, it would be really useful if we could export the coordinates of currently rendered structures to JSON for usage in other tools.

**Comment by burgerguy** [comment]
Currently you can export as a CSV with [StructureFinder](https://github.com/burgerguy/StructureFinder), but I haven't updated that in a while. Eventually I'll work on transferring the features from it to amidst, probably after all of my other PRs are merged.

**Comment by milutinke** [comment]
Okay.
Thank you for your time :)
