### ISSUE TITLE
Amidst detects only 1.12.2 version 

### ISSUE THREAD

**Issue by DropOfAWater** [toolbox4minecraft/amidst#902]
Hello,
I'm having problem, amidst on my computer detcts only minecraft 1.12.2, I also checked if (amidst) version is up to date.
In app it looks like this:
![94368781-5d233a80-00e6-11eb-820c-1074c78c843d (1)](https://user-images.githubusercontent.com/71978548/94481807-9e941280-01d8-11eb-93ae-9ee190992c7d.png)

Edit: I got this error after launcher uptade.

**Comment by moulins** [comment]
Amidst doesn't modded Minecraft profiles.
