### ISSUE TITLE
"Amidst is not able to find your '.minecraft' directory."

### ISSUE THREAD

**Issue by qerqeq** [toolbox4minecraft/amidst#910]
Whenever I execute the jar file ("java -jar amidst-v4-6.jar") I get the error in the title as the file fails to initialize. When trying to specify the path to my Minecraft directory with the -mcpath parameter ("java -jar amidst-v4-6.jar -mcpath ~/.var/app/com.mojang.Minecraft/.minecraft") I get the same issue regardless. I am using Ubuntu Linux and the Minecraft Flatpak repository.

Does anyone know what I'm doing wrong? Thank you.

**Comment by DrHackberry** [comment]
Hi qerqeq,
I just encountered the same issue. 
The Minecraft Flatpak's `.minecraft` si simply not equivalent to the original installation's `.minecraft`.
Try something like this : `java -jar amidst-4.6.jar -mcpath ~/.var/app/com.mojang.Minecraft/data/minecraft/`

**Comment by moulins** [comment]
Closing, since the previous comment gives the solution.
