### ISSUE TITLE
Custom Minecraft directory support

### ISSUE THREAD

**Issue by forkiesassds** [toolbox4minecraft/amidst#918]
I use a 3rd party launcher called MultiMC which does not use the typical .minecraft scheme and instead uses an instance system where each instance gets it's own .minecraft folder that the program can not detect as it expects %appdata%/.minecraft which causes an .minecraft not found error.

**Comment by forkiesassds** [comment]
Why is this option only an CLI thing?

**Comment by moulins** [comment]
Unfortunately, proper MultiMC support is more involved than just changing the location of the `.minecraft` directory, see #126.
