### ISSUE TITLE
Could there potentially be added support for overlaying waypoints and geometric graphics like Geogebra 

### ISSUE THREAD

**Issue by charlesathon** [toolbox4minecraft/amidst#921]
Potentially overlaying cartesian lines like X=-50000 or X=-Y or even circles like (X-4000)^2 + (Y-8000)^2 = 100 or something. 

Also to be able to name locations and waypoints and then save all of one's changes to a map that can be later added to rather than just a screenshot would be extremely useful.

Thanks

**Comment by moulins** [comment]
This is the same feature as #475, closing as duplicate.
