### ISSUE TITLE
Convert Minecraft maps to Minetest worlds

### ISSUE THREAD

**Issue by Pantyhose-X** [toolbox4minecraft/amidst#942]
I wish Amidst had this feature

Example
https://forum.minetest.net/viewtopic.php?f=12&t=13709&sid=64ab4a65e2791ce2b615a536130c7014

https://forum.minetest.net/viewtopic.php?f=14&t=14271&sid=3cd2c3fc6dedd9d79bdc4bf396b1b7d9

**Comment by moulins** [comment]
This is out-of-scope, as Amidst has only very basic save-file reading capabilities (basically, just enough to get the world seed and players positions), and never reads the actual world data.
