### ISSUE TITLE
Menu shortcuts use 'ctrl' on OS X

### ISSUE THREAD

**Issue by moulins** [toolbox4minecraft/amidst#98]
Because the menu shortcut keymask is hardcoded inside AmidstMenuBuilder.java and LayersMenu.java, all the shortcuts use ctrl instead of cmd on OS X.

I already have a fix commited on my fork which should be ready to merge. (https://github.com/moulins/amidst/tree/menu-fix-shortcuts)

**Comment by stefandollase** [comment]
Thanks for contributing code :-) Did you read the wiki entry [Writing Code](https://github.com/toolbox4minecraft/amidst/wiki/Supporting-the-Development#writing-code)? When you did, please [create a pull-request from your branch](https://help.github.com/articles/creating-a-pull-request/).

**Comment by moulins** [comment]
Okay, I made a pull request with my changes. :) ( #99 )
